/* ============================================================
   CHESS: the course
   Eight stages from the board to a tournament programme, built the
   way a strong player's knowledge is actually organised: rules,
   material, tactics, openings, endgames, strategy, calculation,
   and the numbers (Elo, engine evaluations, decision quality).
   Every rule lesson has a drill verified by the engine; the Play
   board grades every move you make.
   ============================================================ */
(function () {
  var LESSONS = {};
  function add(L) { LESSONS[L.id] = L; return L; }
  function board(fen, cap, opts) { return Object.assign({ t: "board", fen: fen, caption: cap }, opts || {}); }

  /* ---------------- stage 0: the board ---------------- */
  add({ id: "ch_board", mode: "chnot", pass: 8, of: 10, title: "The board and the names of the squares", sub: "Files, ranks, algebraic notation", gist: "Sixty-four squares with names, white square on the right, queen on her colour. Learn the names first: every lesson, book and engine speaks in them.",
    blocks: [
      { t: "p", x: "The board is set so each player has a white square in the bottom right corner. Files are the columns, lettered a to h from White's left; ranks are the rows, numbered 1 to 8 from White's side. A square is file then rank: e4 is the fourth square up the e-file. Pieces are written K, Q, R, B, N (knight), and pawns by their square alone." },
      board("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", "The starting position. White queen on d1 (a light square), black queen on d8 (dark): queen on her own colour."),
      { t: "rule", x: "move = piece letter + destination:  Nf3, Bb5, Qxd5 (x = capture), e4 (a pawn)\ncastling: O-O (kingside), O-O-O (queenside) · check: + · mate: #", note: "When two of the same piece can reach a square, add the file or rank: Nbd2, R1e2. Pawn captures name the file they came from: exd5." },
      { t: "tbl", head: ["Symbol", "Meaning"], rows: [["K Q R B N", "king, queen, rook, bishop, knight"], ["x", "captures"], ["+ / #", "check / checkmate"], ["=Q", "promotes to a queen: e8=Q"], ["O-O / O-O-O", "castles short / long"], ["1-0, 0-1, ½-½", "White wins, Black wins, draw"]] },
      { t: "key", x: "Files a–h left to right from White, ranks 1–8 up from White. Square = file + rank. Piece letter + destination, x for a capture, + and #." },
      { t: "how", drill: "Notation", ask: "Click e4. Which square is marked?", steps: ["Find the file letter along the bottom, the rank number up the side.", "On a flipped board (Black's view) the letters run right to left: find a1 first."], tip: "Say the square name every time you move a piece, in your head, for a week. After that you read notation like prose." }
    ] });
  add({ id: "ch_pieces", mode: "chmove", pass: 8, of: 10, title: "How the pieces move", sub: "Six pieces, six rules", gist: "Rook along lines, bishop along diagonals, queen both, knight in an L over anything, king one step, pawn forward and captures sideways.",
    blocks: [
      { t: "tbl", head: ["Piece", "Moves", "Notes"], rows: [["King ♔", "one square in any direction", "may never move into check; castles once"], ["Queen ♕", "any distance along a rank, file or diagonal", "the strongest piece, worth about nine pawns"], ["Rook ♖", "any distance along a rank or file", "two rooks on the seventh rank are a classic win"], ["Bishop ♗", "any distance along a diagonal", "stays on its colour forever; the pair covers both"], ["Knight ♘", "two squares one way, one square sideways", "jumps over pieces; always lands on the other colour"], ["Pawn ♙", "one square forward, two from its start; captures one square diagonally forward", "promotes on the last rank; en passant"]] },
      board("8/8/8/3N4/8/8/8/8 w - - 0 1", "A knight on d5 reaches eight squares: b4, b6, c3, c7, e3, e7, f4, f6. On the rim it reaches four at most. 'A knight on the rim is dim.'", { mark: ["b4", "b6", "c3", "c7", "e3", "e7", "f4", "f6"] }),
      { t: "rule", x: "sliders (Q R B) stop at the first piece in the way; they capture an enemy there, never pass it\nthe knight ignores everything in between", note: "A piece 'attacks' every square it could move to, including squares it could capture on. The pawn is the exception: it attacks diagonally but moves straight." },
      { t: "p", x: "Three special moves. Castling: the king moves two squares toward a rook and the rook jumps over it, allowed only if neither has moved, nothing is between them, and the king is not in check, does not pass through check, and does not land in check. En passant: a pawn that has just moved two squares can be captured by an enemy pawn beside it as if it had moved one, on that move only. Promotion: a pawn reaching the last rank becomes a queen, rook, bishop or knight, your choice, usually a queen." },
      { t: "key", x: "Q R B slide and stop at the first piece. N jumps, two-and-one, to the other colour. K one step, never into check. Pawns forward one (two at first), capture diagonally, promote at the end." },
      { t: "how", drill: "How the pieces move", ask: "Click a square this piece can move to.", steps: ["Identify the piece.", "Trace its lines or its L.", "Click any legal destination; the drill accepts all of them."], tip: "Blocked lines and pins are where beginners go wrong. If a move would leave your king in check, it is not legal at all." }
    ] });
  add({ id: "ch_check", mode: "chcheck", pass: 8, of: 10, title: "Check, checkmate, stalemate", sub: "How games end", gist: "Check is an attack on the king and must be answered. Checkmate ends the game. Stalemate, no legal move and not in check, is a draw, and it throws away more won games than any other rule.",
    blocks: [
      { t: "p", x: "When your king is attacked you are in check and must get out of it at once, in one of three ways: move the king, capture the checking piece, or block the line (not possible against a knight or a pawn, or a double check). If none works, it is checkmate and you have lost." },
      board("6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1", "Ra8 is checkmate: the rook checks along the eighth rank, the king's own pawns take away f7, g7, h7, and nothing can block or capture. The back-rank mate."),
      { t: "rule", x: "check: king attacked → move, capture, or block\ncheckmate: in check, no escape → game over\nstalemate: not in check, no legal move → draw", note: "Other draws: threefold repetition of the position, fifty moves without a capture or pawn move, insufficient material (king and a minor piece cannot mate), and agreement." },
      board("7k/5Q2/6K1/8/8/8/8/8 b - - 0 1", "Black to move: not in check, and no legal move. Stalemate, a draw, with a queen up. The queen must leave the king one square until the last moment."),
      { t: "warn", x: "A double check (two pieces checking at once, usually from a discovered attack) can only be met by a king move. It is the most forcing move in chess." },
      { t: "key", x: "Out of check by move, capture or block. No escape = mate. No move and no check = stalemate = draw. Check your opponent's legal moves before you cage the king." },
      { t: "how", drill: "Check", ask: "Is the side to move in check? Which piece gives check?", steps: ["Find the king.", "Look along every line to it: diagonals, file, rank, and the eight knight squares.", "A pawn checks diagonally, from the side it moves toward."], tip: "Scan from the king outward, not from the pieces inward. It is faster and you miss less." }
    ] });

  /* ---------------- stage 1: material ---------------- */
  add({ id: "ch_value", mode: "chvalue", pass: 8, of: 10, title: "What the pieces are worth", sub: "1, 3, 3, 5, 9", gist: "Pawn 1, knight 3, bishop 3, rook 5, queen 9. The scale decides most trades, and the exceptions are where chess understanding starts.",
    blocks: [
      { t: "p", x: "The point values are an average over many positions, first stated in the eighteenth century and confirmed by every engine since (Stockfish's internal values are close to 1 / 3.1 / 3.3 / 5 / 9.5 in the middlegame). They answer the beginner's question in most positions: is this trade good? Give up fewer points than you take and it usually is." },
      { t: "tbl", head: ["Trade", "Points", "Verdict"], rows: [["knight for rook", "3 for 5", "winning the exchange: good"], ["rook for two minors", "5 for 6", "slightly bad in the middlegame, often fine in the endgame"], ["queen for two rooks", "9 for 10", "roughly even; the rooks prefer open files and a safe king"], ["queen for three minors", "9 for 9", "even on paper; three pieces usually beat a queen when coordinated"], ["bishop for knight", "3 for 3", "even; the bishop pair is worth about half a pawn extra"], ["two pawns for a minor piece", "2 for 3", "bad, unless the pawns are passed and advanced"]] },
      { t: "rule", x: "P 1 · N 3 · B 3 · R 5 · Q 9\nthe bishop pair ≈ +0.5 · a passed pawn on the 6th ≈ a minor piece", note: "Values shift with the position: knights love closed positions and outposts, bishops love open diagonals, rooks love open files and the seventh rank." },
      { t: "key", x: "1, 3, 3, 5, 9. Count before every trade. Bishop pair, passed pawns and activity adjust the count, never replace it." },
      { t: "how", drill: "Trades", ask: "Good, bad or even?", steps: ["Add the points you give.", "Add the points you get.", "Compare."], tip: "Say the numbers out loud: 'three for five, good'. In a month you will not need to." }
    ] });
  add({ id: "ch_count", mode: "chmat", pass: 7, of: 10, title: "Counting the material", sub: "Fast and exact", gist: "Who is ahead and by how much, in under ten seconds. Every evaluation of a position begins with this count, and under time pressure most players get it wrong.",
    blocks: [
      { t: "p", x: "Count by type, not by square: queens, then rooks, then minor pieces, then pawns, for each side, and take the difference. Strong players do not count at all in familiar positions because they track every capture as it happens; while you are learning, count every time, and the tracking will follow." },
      { t: "ex", title: "Worked example", facts: [["White", "Q, R, B, N, 5 pawns"], ["Black", "Q, 2R, B, 4 pawns"]], steps: ["White: 9 + 5 + 3 + 3 + 5 = 25.", "Black: 9 + 10 + 3 + 4 = 26.", "Black is up one point: a rook for a knight and a pawn, the exchange for a pawn."], punch: "A one-point difference is a real edge, not a decisive one. A three-point edge, a clean piece, usually wins with care." },
      { t: "key", x: "Queens, rooks, minors, pawns, each side, difference. Ten seconds, every position." },
      { t: "how", drill: "Counting material", ask: "White minus Black on the 1/3/3/5/9 scale.", steps: ["Queens: 9 each.", "Rooks: 5 each. Minors: 3 each. Pawns: 1 each.", "Subtract Black's total from White's."], tip: "Count the pieces that are missing from the starting set rather than the ones present. It is faster: 'Black has lost a knight and two pawns.'" }
    ] });

  /* ---------------- stage 2: tactics ---------------- */
  add({ id: "ch_fork", mode: "chfork", pass: 7, of: 10, title: "The fork", sub: "One piece, two targets", gist: "A fork attacks two things at once; only one can be saved. Knights fork best, pawns fork cheapest, and the queen forks king and loose piece all day.",
    blocks: [
      { t: "p", x: "Tactics are forcing sequences that win material or mate, and the fork is the first and most common. The attacker moves to a square from which it attacks two targets; the defender moves one, the other falls. The best targets are the king (the check forces the reply) and an undefended, or loose, piece." },
      board("2r1k3/8/8/3N4/8/8/8/4K3 w - - 0 1", "Nc7+ forks the king and the rook on c8. Black must move the king, and the rook is lost.", { mark: ["c7"] }),
      { t: "rule", x: "fork = one move attacking two targets\nbest: check + loose piece · knight fork: targets on the other colour from the knight", note: "A knight on a light square only attacks dark squares. If the king and queen sit on the same colour, no knight can fork them on the next move." },
      { t: "p", x: "Pawn forks are the cheapest: a pawn worth one attacks two pieces worth three or more, and whatever the defender does, a pawn trades for a piece. Queen forks of king and rook decide thousands of games a day online. Look for them every time a piece is loose." },
      { t: "key", x: "Loose pieces drop off (Nunn). Before every move, list your opponent's undefended pieces and ask which square attacks two of them." },
      { t: "how", drill: "Forks", ask: "Find the knight fork.", steps: ["List the enemy pieces worth more than a knight, and the king.", "Find the squares that attack two of them.", "Check the forking square is not attacked, then play it."], tip: "Knight forks come from the squares a knight's move away from both targets. Picture the two L-shapes and look for where they cross." }
    ] });
  add({ id: "ch_pin", mode: "mixed", pass: 7, of: 10, title: "Pins, skewers, discovered attacks", sub: "The line tactics", gist: "A pin fixes a piece in front of a more valuable one; a skewer is a pin in reverse; a discovered attack unmasks a line by moving a piece off it. All three come from the sliding pieces.",
    blocks: [
      { t: "p", x: "A pin: a bishop, rook or queen attacks a piece that cannot move without exposing something worth more behind it. Against the king the pin is absolute (the pinned piece may not legally move at all). A pinned piece is a target: attack it again, it cannot run. A skewer is the same geometry the other way round: the valuable piece is in front, and when it moves the piece behind is taken." },
      board("4k3/8/8/8/8/8/4n3/4R1K1 w - - 0 1", "The black knight on e2 is pinned to the king by the rook: it cannot move. White attacks it again and it falls.", { mark: ["e2"] }),
      { t: "p", x: "A discovered attack: a piece moves off a line and the piece behind it attacks. The moving piece can do its own damage at the same time, and if the uncovered attack is on the king it is a discovered check, which lets the moving piece take almost anything. A double check, both pieces checking, can only be met by a king move." },
      { t: "rule", x: "pin: attacker — pinned piece — bigger piece behind\nskewer: attacker — bigger piece — smaller piece behind\ndiscovery: move the front piece, the back piece attacks", note: "All three need a line. Rooks on files, bishops on diagonals, queens on both: look for two enemy pieces on one line, and the line tactic is usually there." },
      { t: "warn", x: "A pinned piece does not defend. If your knight is pinned to your king, the square it 'guards' is not guarded, and the opponent can walk in. Count pinned pieces out of your defence." },
      { t: "key", x: "Two enemy pieces on one line: pin, skewer or discovery. Pinned pieces are targets and do not defend. Discovered checks win material." },
      { t: "how", drill: "Mixed tactics", ask: "Find the fork, the mate, or the best move.", steps: ["Checks, captures, threats, in that order.", "Look for enemy pieces sharing a line.", "Calculate the forcing reply before you play."], tip: "The checkpoint mixes this stage's drills, like a real game does." }
    ] });
  add({ id: "ch_mate1", mode: "chmate1", pass: 7, of: 10, title: "Mate in one", sub: "The patterns", gist: "Back rank, smothered, queen-and-king, bishop-and-queen on h7: a dozen patterns cover most mates you will ever play or allow. Learn them so you see them without looking.",
    blocks: [
      { t: "tbl", head: ["Pattern", "Shape", "Typical mate"], rows: [["Back rank", "king on the last rank behind its own pawns", "Ra8# / Qd8#"], ["Smothered", "king boxed in by its own pieces", "Nf7#"], ["Scholar's", "queen and bishop on f7/f2 early", "Qxf7#"], ["Queen next to the king", "queen adjacent, protected", "Qg7# with a bishop or king behind"], ["Anastasia's", "knight on e7, rook on the h-file", "Rh3# after Qxh7+ Kxh7"], ["Arabian", "rook and knight in the corner", "Rh7# with Nf6"], ["Boden's", "two bishops on crossing diagonals", "Ba6# against a queenside-castled king"], ["Damiano's", "pawn on g6, queen on the h-file", "Qh7#"]] },
      board("6rk/6pp/8/4N3/8/8/8/6QK w - - 0 1", "Smothered mate geometry: if the queen reaches g8 with check and is taken by the rook, Nf7 is mate because the king's own pieces fill every square. Philidor's legacy.", { mark: ["f7"] }),
      { t: "rule", x: "every mate in one is a check\nlist the checks, for each ask: king move? capture? block?", note: "Three questions per check. If all three are no, it is mate. This is how the drill verifies its answers, and it is how you should too." },
      { t: "key", x: "Mate in one: checks only, three questions each. Back rank, smothered, Qh7 with support, Scholar's: see the shape, not the moves." },
      { t: "how", drill: "Mate in one", ask: "Play the mating move.", steps: ["List every check.", "For each: can the king move, can the checker be taken, can it be blocked?", "Play the one with three no's."], tip: "The drill generates positions and verifies the mate with the engine; the curated ones are the classical patterns. Both count." }
    ] });
  add({ id: "ch_mate2", mode: "chmate2", pass: 3, of: 4, title: "Mate in two", sub: "Forcing sequences", gist: "A forcing first move, then mate whatever the reply. The skill is seeing every reply, which is calculation, the thing that separates levels.",
    blocks: [
      { t: "p", x: "A mate in two is a first move after which every legal reply allows mate in one. The first move is usually a check, a capture, or a threat that cannot be ignored (a sacrifice that drags the king out, a quiet move that cuts off a square). The method is exhaustive: for each candidate first move, list every reply and find the mate after each; if one reply has no mate, the candidate fails." },
      board("5r1k/6pp/8/4N3/8/1Q6/B7/7K w - - 0 1", "Qg8+! Rxg8 (forced: the bishop on a2 covers g8 so the king cannot take) Nf7#. A queen sacrifice to force a smothered mate.", { mark: ["g8", "f7"] }),
      { t: "rule", x: "candidate = check, capture or threat\nfor every reply, find the mate; one escape and the candidate fails", note: "Kotov's tree: candidate moves first, then calculate each branch once, carefully, rather than the same line five times." },
      { t: "key", x: "Forcing first move, every reply answered. Calculate each branch once, to the end." },
      { t: "how", drill: "Mate in two", ask: "Play the first move.", steps: ["List the forcing candidates.", "For each, list Black's replies.", "Find the mate after each reply; play the candidate that always mates."], tip: "Write the variations down when you practise. The habit of seeing every reply is the habit that stops you blundering." }
    ] });
  add({ id: "ch_best", mode: "chbest", pass: 6, of: 8, title: "Find the best move", sub: "CCT and the engine's verdict", gist: "Positions where one move is clearly best, graded by the engine. Checks, captures, threats: the discipline that finds most of them.",
    blocks: [
      { t: "p", x: "Most decisive moves in games below master level are tactics the loser never considered, because they did not look at the forcing moves first. The habit that fixes it: at every move, before anything else, list the checks, the captures and the threats, for both sides. Then calculate the ones that look promising. The drill gives positions where the engine finds one move worth at least 2.5 pawns more than the next; your job is to find it the same way." },
      { t: "rule", x: "CCT: Checks · Captures · Threats, yours and theirs, before any other move\nblunder check: after choosing, ask what their best CCT reply is", note: "Forcing moves narrow the tree; quiet moves widen it. Look where the tree is narrow first." },
      { t: "key", x: "Checks, captures, threats, both sides, every move. Then the blunder check." },
      { t: "how", drill: "Best move", ask: "Find the move the engine rates clearly best.", steps: ["CCT for you.", "Calculate the most forcing line to a quiet position.", "Count the material and the king safety at the end; play the best."], tip: "Thirty seconds of CCT per move, for every move of every game you play, is the single biggest rating gain available below 1800." }
    ] });

  /* ---------------- stage 3: openings ---------------- */
  add({ id: "ch_openprin", mode: "quiz", pass: 4, of: 5, title: "Opening principles", sub: "Centre, development, king safety", gist: "Three principles cover the first ten moves of every opening ever played: fight for the centre, bring the pieces out, castle. Memorised lines come later, and only on top of these.",
    quiz: [
      { q: "In the opening, which should usually come first?", options: ["Castling", "Developing the knights and bishops", "Moving the queen out early", "Pushing the a- and h-pawns"], answer: "Developing the knights and bishops", explain: "Pieces before pawns and queen; knights before bishops is the old rule of thumb." },
      { q: "Why is the centre (d4, e4, d5, e5) worth fighting for?", options: ["Pieces there control the most squares and reach both wings", "It is closest to the opponent's king", "Pawns there cannot be attacked", "It wins material automatically"], answer: "Pieces there control the most squares and reach both wings", explain: "A knight in the centre reaches eight squares; in the corner, two." },
      { q: "Which is the usual mistake?", options: ["Castling by move ten", "Moving the same piece twice in the opening without reason", "Playing e4 or d4 first", "Developing a knight to f3"], answer: "Moving the same piece twice in the opening without reason", explain: "Every tempo spent moving a developed piece again is a tempo the opponent spends developing a new one." },
      { q: "A 'gambit' is", options: ["A pawn sacrificed in the opening for development or initiative", "A checkmate pattern", "A trade of queens", "An endgame technique"], answer: "A pawn sacrificed in the opening for development or initiative", explain: "Queen's Gambit, King's Gambit, Evans Gambit: a pawn for time." },
      { q: "After 1.e4 e5 2.Nf3, what does Nf3 do?", options: ["Attacks the e5 pawn and develops toward the centre", "Prepares to castle queenside", "Threatens mate", "Defends d4"], answer: "Attacks the e5 pawn and develops toward the centre", explain: "Develop with a threat when you can: the opponent must respond, and you gain time." }
    ],
    blocks: [
      { t: "p", x: "The opening is about getting the pieces to good squares quickly and safely. Control the centre with pawns (e4, d4 or their mirror), develop knights and bishops toward it, castle early, connect the rooks, and only then start a plan. Do not move the queen out early (it gets chased and you lose time), do not move the same piece twice without reason, and do not grab pawns that cost development." },
      { t: "tbl", head: ["Principle", "Why"], rows: [["Occupy or control the centre", "Central pieces reach both wings; the opponent's are cramped"], ["Develop knights and bishops, then castle", "Every undeveloped piece is a piece that cannot fight"], ["Don't move the same piece twice", "Tempo: each move is a unit of time, and time is the opening's currency"], ["Keep the queen home until the minors are out", "An early queen gets attacked by developing moves and loses tempi"], ["Castle by move ten, usually short", "An uncastled king in an open centre loses to tactics"], ["Connect the rooks", "Development is complete when the back rank is clear between them"]] },
      { t: "rule", x: "tempo = one move of time\na developing move that also threatens something gains a tempo", note: "Gambits trade a pawn for two or three tempi. In an open position, a tempo is worth about a third of a pawn, so the trade can be fair." },
      { t: "key", x: "Centre, development, king safety, connect the rooks. Pieces before pawns, knights before bishops, castle before move ten." }
    ] });
  add({ id: "ch_openings", mode: "chopen", pass: 8, of: 10, title: "The openings you will meet", sub: "Sixteen names and their ideas", gist: "You do not need to memorise lines to recognise the families: the Italian, the Spanish, the Sicilian, the French, the Queen's Gambit, the Indians. Each has one idea.",
    blocks: [
      { t: "tbl", head: ["Moves", "Opening", "The idea"], rows: CH_OPENINGS },
      { t: "p", x: "A practical repertoire at club level: as White, 1.e4 and the Italian Game against 1...e5, with a simple system against the Sicilian (the Alapin, 2.c3) and the French (the Advance, 3.e5). As Black, 1...e5 against 1.e4 and the Queen's Gambit Declined or the Slav against 1.d4. Learn the first eight moves and the typical plans; play the resulting middlegames a hundred times each. Depth in a few lines beats breadth in many." },
      { t: "rule", x: "learn ideas and typical plans first, exact moves second\nreview every opening you play with an engine: the first new move is the lesson", note: "Lichess's opening explorer shows what masters play from any position, free. Use it after games, not during." },
      { t: "key", x: "Sixteen families, one idea each. A narrow repertoire played deeply. Review the first new move of every game." },
      { t: "how", drill: "Openings", ask: "Which opening is this?", steps: ["Look at the first pawn moves: e4 or d4 decides the family.", "Then the key piece move: Bb5, Bc4, c4, Nf6 and g6…", "Match the name."], tip: "Say the opening's idea with its name: 'Ruy Lopez, pressure on e5'. The idea is what you play with." }
    ] });

  /* ---------------- stage 4: endgames ---------------- */
  add({ id: "ch_kq", mode: "quiz", pass: 4, of: 5, title: "King and queen, king and rook", sub: "The basic mates", gist: "Drive the king to the edge with the big piece, bring your own king up, deliver mate without stalemating. Every player must be able to do both in under a minute.",
    quiz: [
      { q: "In the king-and-queen mate, the queen should", options: ["Stay a knight's move away from the enemy king and shrink its box", "Check on every move", "Stay on the back rank", "Trade itself for the last pawn"], answer: "Stay a knight's move away from the enemy king and shrink its box", explain: "The knight's-move distance means the queen is never capturable and cuts off the most squares; no checks are needed until the end." },
      { q: "The biggest danger in the king-and-queen mate is", options: ["Stalemate", "Losing the queen to a fork", "Running out of moves", "Perpetual check"], answer: "Stalemate", explain: "Always leave the lone king one square until your own king arrives." },
      { q: "In the king-and-rook mate, the rook mates the king", options: ["On the edge, with the kings facing each other in opposition", "In the centre", "By checking on every move", "Only with help from a pawn"], answer: "On the edge, with the kings facing each other in opposition", explain: "Cut the king off with the rook, bring your king to the opposition, then check along the edge." },
      { q: "If the enemy king steps away from the opposition in the rook mate, you should", options: ["Make a waiting move with the rook along its rank", "Give check at once", "Move your king back", "Offer a draw"], answer: "Make a waiting move with the rook along its rank", explain: "The rook tempo move forces the king back into opposition or further to the edge." },
      { q: "Which of these cannot force mate against a lone king?", options: ["King and two bishops", "King and bishop", "King and rook", "King and queen"], answer: "King and bishop", explain: "A single minor piece, or two knights (without help), cannot force mate." }
    ],
    blocks: [
      { t: "p", x: "King and queen versus king: use the queen a knight's move away from the enemy king to shrink its box without checking (no stalemate possible while it has squares), bring your king up to the opposition, and mate on the edge. Twelve moves at most. King and rook: cut the king off on a rank or file with the rook, bring your king to the opposition, and check along the edge; when the king steps aside, make a rook waiting move. Twenty moves at most." },
      board("7k/8/5QK1/8/8/8/8/8 w - - 0 1", "Queen on f6, kings on h8 and g6: Qf8 or Qg7 is mate. The queen covered the box without ever checking, the king arrived, and the mate took one move."),
      { t: "rule", x: "queen: knight's move away, shrink the box, king up, mate on the edge\nrook: cut off, opposition, check on the edge, waiting move if needed", note: "Practise both against the engine in Play from a bare position until you can do each in under a minute without thought." },
      { t: "key", x: "Big piece shrinks the box, king comes up, mate on the edge. Leave a square until the end. Never stalemate." }
    ] });
  add({ id: "ch_square", mode: "chsquare", pass: 8, of: 10, title: "The square of the pawn", sub: "Can the king catch it?", gist: "A passed pawn races a king. Draw a square from the pawn to its queening square: if the king is in it, or can step in, the pawn is caught.",
    blocks: [
      { t: "p", x: "The square rule answers in one glance what would otherwise take counting: imagine a square whose one side runs from the pawn to its promotion square. If the defending king, with the move, can step into that square, it catches the pawn; otherwise the pawn queens. A pawn on its starting square counts as if one rank further on, because it can move two." },
      board("8/8/8/8/k7/8/4P3/4K3 w - - 0 1", "White to move, e2–e4: the square runs e4–e8–a8–a4. The king on a4 is on its corner. White to move gets the pawn to e5 first, shrinking the square to e5–e8–b8–b5, and a4 is outside: the pawn queens. Black to move, Kb5 steps in and catches it."),
      { t: "rule", x: "d = the pawn's moves to queen (one fewer from the start rank)\nk = the king's moves to the queening square\nking catches if k ≤ d (pawn to move) or k ≤ d + 1 (king to move)", note: "King-move distance is the larger of the file and rank differences: a king moves diagonally as fast as straight. Arriving on the queening square as the pawn promotes still catches it." },
      { t: "key", x: "Draw the square. In it, or stepping in: caught. Outside: queens. Start rank counts one further." },
      { t: "how", drill: "The square rule", ask: "Can the king catch the pawn?", steps: ["Count the pawn's moves to queen.", "Count the king's moves to the queening square (diagonals count as one).", "Compare, allowing for who moves first."], tip: "Trust the rule, then verify the hardest cases by counting. In ten positions it is a reflex." }
    ] });
  add({ id: "ch_opp", mode: "chopp", pass: 8, of: 10, title: "The opposition", sub: "King against king", gist: "Kings one square apart on a line, the other side to move: that side must give way. The opposition decides king-and-pawn endings, which decide more games than any other.",
    blocks: [
      { t: "p", x: "Two kings cannot stand next to each other, so when they face each other with one square between, whoever must move has to step aside and let the other through. Having the opposition means it is your opponent's move in that stance. In a king-and-pawn ending it decides whether your king reaches the key squares in front of the pawn, which decides whether the pawn queens." },
      board("8/8/8/3k4/8/3K4/8/8 w - - 0 1", "Kings on d3 and d5, White to move: Black has the opposition. White must step to c3, e3, c2, d2 or e2, and Black's king advances. With Black to move, White has it."),
      { t: "rule", x: "opposition: same file or rank, one square between, the OTHER side to move\nwith a pawn: get your king to the key squares (two ranks in front of the pawn) and it queens", note: "Distant opposition: an odd number of squares between the kings on a line. Diagonal opposition works the same way. The rule of thumb: put your king on a square of the same colour as the enemy king's, when it is their move." },
      board("8/8/4k3/8/8/4K3/4P3/8 w - - 0 1", "The key squares for a pawn on e2 are d4, e4, f4. White to move: Ke4! takes the opposition and the key square; the pawn will queen. Black to move: Ke5 takes it, and it is a draw."),
      { t: "key", x: "Face the king with one square between and make them move. Key squares in front of the pawn win; the opposition gets you there." },
      { t: "how", drill: "The opposition", ask: "Click the square that takes the opposition.", steps: ["Find the enemy king.", "The square two away on the same file or rank, if your king can reach it.", "Click it."], tip: "The square of the same colour, when it is their move. Check the colour before you count." }
    ] });
  add({ id: "ch_rook", mode: "quiz", pass: 4, of: 5, title: "Rook endings: Lucena and Philidor", sub: "The two positions every player must know", gist: "Rook and pawn against rook is the most common ending in chess. Lucena wins it, Philidor draws it, and both are three moves of technique.",
    quiz: [
      { q: "In the Lucena position (attacking king in front of its pawn on the seventh, defending king cut off), the winning method is", options: ["Build a bridge: put the rook on the fourth rank to shield the king from checks", "Push the pawn immediately", "Trade rooks", "Give perpetual check"], answer: "Build a bridge: put the rook on the fourth rank to shield the king from checks", explain: "Rook to the fourth (or fifth) rank, king steps out, the rook interposes against the checks, the pawn queens." },
      { q: "In the Philidor position (defender's king in front of the pawn, pawn not yet on the sixth), the drawing method is", options: ["Keep the rook on the third rank until the pawn advances, then check from behind", "Attack the pawn with the king", "Trade rooks at once", "Check from the side immediately"], answer: "Keep the rook on the third rank until the pawn advances, then check from behind", explain: "The third-rank rook stops the attacking king from advancing; once the pawn reaches the sixth, the rook goes to the first rank and checks from behind forever." },
      { q: "Rook endings are drawn most often because", options: ["Rooks give endless checks and a lone king cannot hide", "Rooks are weak pieces", "Pawns cannot promote with rooks on the board", "The fifty-move rule"], answer: "Rooks give endless checks and a lone king cannot hide", explain: "Activity and checking distance decide rook endings; an active rook draws a pawn down." },
      { q: "'Rooks belong behind passed pawns' means", options: ["Behind your own passed pawn to push it, behind the enemy's to stop it", "In front of the pawn", "Beside the king", "On the same file as the enemy king"], answer: "Behind your own passed pawn to push it, behind the enemy's to stop it", explain: "Tarrasch's rule: behind the pawn the rook gains scope as the pawn advances." },
      { q: "In a rook ending, a rook on the seventh rank", options: ["Attacks pawns and ties the king to the back rank", "Is usually a mistake", "Only matters with a queen", "Cannot give check"], answer: "Attacks pawns and ties the king to the back rank", explain: "The 'pig on the seventh' is worth a pawn in most positions." }
    ],
    blocks: [
      { t: "p", x: "Rook endings are half of all endings. Two positions carry most of the theory. Lucena: the attacker's king is in front of its pawn on the seventh rank and the defender's king is cut off; the win is to 'build a bridge' with the rook on the fourth rank so the king can step out of the checks. Philidor: the defender's king sits in front of the pawn and the rook stays on the third rank, preventing the enemy king from crossing; when the pawn advances to the sixth, the rook drops to the first rank and checks from behind. Draw." },
      board("1K1k4/1P6/8/8/8/8/r7/2R5 w - - 0 1", "Lucena: White's king is stuck in front of its pawn. Rc4! then Kc7, and when the checks come the rook interposes on c4 (the bridge). The pawn queens."),
      board("4k3/8/8/4PK2/8/r7/8/1R6 b - - 0 1", "Philidor: Black's rook on the third rank holds. If e6, then Ra1 and checks from behind: the white king has no shelter. A draw."),
      { t: "rule", x: "Lucena: rook to the 4th, king out, bridge → win\nPhilidor: rook on the 3rd until the pawn hits the 6th, then checks from behind → draw\nTarrasch: rooks behind passed pawns", note: "Learn these two cold; then Dvoretsky's Endgame Manual for the rest. Rook activity beats a pawn." },
      { t: "key", x: "Lucena wins, Philidor draws, rooks behind passed pawns, active rook over material." }
    ] });

  /* ---------------- stage 5: strategy ---------------- */
  add({ id: "ch_pawns", mode: "quiz", pass: 4, of: 5, title: "Pawn structure", sub: "Philidor: pawns are the soul of chess", gist: "Pawns cannot go back, so their arrangement is the long-term truth of a position. Isolated, doubled, backward, passed: each kind has a value and a plan.",
    quiz: [
      { q: "An isolated pawn (no friendly pawn on either adjacent file) is", options: ["A weakness to blockade and attack, but it gives its owner open files and space", "Always winning", "Impossible to attack", "Worth two pawns"], answer: "A weakness to blockade and attack, but it gives its owner open files and space", explain: "Blockade it with a knight and attack it; the side with the isolani must attack before the endgame." },
      { q: "A passed pawn is", options: ["A pawn with no enemy pawn in front of it or on the adjacent files ahead", "Any advanced pawn", "A pawn that has captured", "A pawn on the seventh rank"], answer: "A pawn with no enemy pawn in front of it or on the adjacent files ahead", explain: "Nothing but pieces can stop it; its value rises every rank it advances." },
      { q: "'Doubled pawns' are", options: ["Two friendly pawns on the same file", "Two pawns side by side", "A pawn pair in the centre", "Pawns on the second rank"], answer: "Two friendly pawns on the same file", explain: "They cannot defend each other and one is often lost in the endgame; but they can open files and control squares." },
      { q: "A backward pawn is weak because", options: ["It cannot be defended by another pawn and the square in front of it is an outpost for the enemy", "It cannot move", "It is doubled", "It is on the edge"], answer: "It cannot be defended by another pawn and the square in front of it is an outpost for the enemy", explain: "The 'hole' in front of a backward pawn is where enemy knights live." },
      { q: "A pawn majority on one wing suggests", options: ["Advancing it to create a passed pawn", "Trading it off", "Keeping it still", "Moving the king there"], answer: "Advancing it to create a passed pawn", explain: "A healthy majority produces a passed pawn; the minority on the other wing can attack to create weaknesses (the minority attack)." }
    ],
    blocks: [
      { t: "p", x: "Pieces move; pawn structures last. Learn the kinds: isolated (no neighbour on either side, a weakness and a source of activity), doubled (two on a file, cannot protect each other), backward (left behind its neighbours, the square in front is a hole), passed (nothing can stop it but pieces), and the chain (pawns on a diagonal, attacked at the base). Each kind tells both sides what to do for the next twenty moves." },
      { t: "tbl", head: ["Structure", "Weakness", "Plan for the owner", "Plan against"], rows: [["Isolated pawn", "cannot be defended by a pawn", "attack with pieces before the endgame; use the open files", "blockade the square in front, trade pieces, win it in the ending"], ["Doubled pawns", "one is usually lost late", "use the half-open file they created", "fix them and attack the front one"], ["Backward pawn", "the hole in front", "trade it or advance it when possible", "occupy the hole with a knight"], ["Passed pawn", "none; it is a strength", "push it, support it with rooks behind", "blockade it with a knight or king"], ["Pawn chain", "the base", "attack on the side the chain points to", "attack the base with pawn breaks"]] },
      { t: "rule", x: "attack a chain at its base · blockade a passed pawn · pieces belong where the pawns point\nan outpost = a square that cannot be attacked by an enemy pawn", note: "Nimzowitsch's My System is the book on all of this: blockade, overprotection, the passed pawn's 'lust to expand'." },
      { t: "key", x: "Read the pawns first. Weaknesses are permanent; pieces are not. Put knights on outposts, rooks on open files, bishops on long diagonals, and pawns in a plan." }
    ] });
  add({ id: "ch_pieces2", mode: "quiz", pass: 4, of: 5, title: "Good pieces, bad pieces", sub: "Activity, the bishop pair, knights vs bishops", gist: "Material is the count; activity is the quality. A bad bishop behind its own pawns is worth less than a knight on an outpost, and the position tells you which.",
    quiz: [
      { q: "A 'bad bishop' is one", options: ["Whose own pawns stand on its colour, blocking it", "That has been traded", "On the long diagonal", "That gives check"], answer: "Whose own pawns stand on its colour, blocking it", explain: "Pawns on the bishop's colour make it a 'tall pawn'. Put your pawns on the opposite colour from your bishop." },
      { q: "Knights are usually better than bishops when", options: ["The position is closed and there are outposts", "The position is open", "Pawns are on both wings", "The endgame is near"], answer: "The position is closed and there are outposts", explain: "Knights jump over blocked pawns; bishops need open diagonals and love pawns on both wings." },
      { q: "The bishop pair is strong because", options: ["Together they cover both colours and no square is safe", "They are worth four each", "They cannot be traded", "They attack the king directly"], answer: "Together they cover both colours and no square is safe", explain: "About half a pawn's worth in open positions; the side without the pair should keep it closed or trade one." },
      { q: "'Rooks on open files' matters because", options: ["An open file leads to the seventh rank and the enemy camp", "Rooks cannot move on closed files", "It protects the king", "It wins pawns automatically"], answer: "An open file leads to the seventh rank and the enemy camp", explain: "Doubled rooks on an open file invade the seventh and tie the enemy to defence." },
      { q: "The principle of two weaknesses says", options: ["One weakness can be defended; attack a second and the defence breaks", "Never have two weaknesses", "Trade when you have two weaknesses", "Weaknesses only matter in the endgame"], answer: "One weakness can be defended; attack a second and the defence breaks", explain: "Switch the attack between two targets faster than the defender can switch the defence." }
    ],
    blocks: [
      { t: "p", x: "Positional judgement is the habit of asking, for each piece, how many useful squares it has and whether it can get more. Bishops want open diagonals and pawns on the opposite colour. Knights want outposts (squares no enemy pawn can attack) and closed positions. Rooks want open files and the seventh rank. The king wants pawn cover in the middlegame and activity in the endgame. The side with better-placed pieces has the initiative, and the initiative is worth material." },
      { t: "rule", x: "bishop: pawns on the other colour · knight: outposts, closed centre · rook: open files, 7th rank\nbishop pair ≈ +0.5 in open positions · two weaknesses beat one", note: "Steinitz: the side with the advantage must attack, or the advantage evaporates. Evaluate, then act on what you found." },
      { t: "key", x: "Count the material, then grade each piece's activity. Improve your worst piece. Create a second weakness." }
    ] });

  /* ---------------- stage 6: calculation and the numbers ---------------- */
  add({ id: "ch_calc", mode: "quiz", pass: 4, of: 5, title: "Calculation and blunder-proofing", sub: "Candidate moves, the tree, time", gist: "How strong players think: list the candidates, calculate each once to a quiet position, evaluate, then run the blunder check before touching a piece.",
    quiz: [
      { q: "Kotov's method begins with", options: ["Listing the candidate moves before calculating any of them", "Calculating the first move you see as deeply as possible", "Checking the clock", "Counting material"], answer: "Listing the candidate moves before calculating any of them", explain: "Think Like a Grandmaster: the tree is wide first, then deep, and each branch is calculated once." },
      { q: "A 'quiet position' at the end of a line is one where", options: ["There are no more forcing moves to consider, so it can be evaluated", "Both sides have castled", "No pieces have been traded", "The queens are off"], answer: "There are no more forcing moves to consider, so it can be evaluated", explain: "Calculate until the forcing moves run out, then judge the position; the engine's quiescence search does exactly this." },
      { q: "The blunder check is", options: ["After choosing a move, ask what the opponent's most forcing reply is", "Playing quickly to avoid time trouble", "Checking the material count", "Looking at the whole board for undefended pieces"], answer: "After choosing a move, ask what the opponent's most forcing reply is", explain: "Checks, captures and threats for the opponent, after your intended move, before you play it." },
      { q: "Time management: the most time should go to", options: ["Critical positions where the choice changes the evaluation", "The opening", "Recaptures", "Every move equally"], answer: "Critical positions where the choice changes the evaluation", explain: "Spend when the game turns; move quickly when the move is obvious or forced." },
      { q: "Pattern recognition improves fastest by", options: ["Solving many tactical puzzles with immediate feedback, spaced over time", "Reading about openings", "Playing only long games", "Watching streams"], answer: "Solving many tactical puzzles with immediate feedback, spaced over time", explain: "Ericsson's deliberate practice: thousands of patterns, each tested, corrected and revisited. That is what the drills here do." }
    ],
    blocks: [
      { t: "p", x: "Calculation is a trained skill with a method. First, candidate moves: the forcing ones (checks, captures, threats) and the two or three positional ones that fit the plan. Second, calculate each candidate once, down the most forcing line, to a quiet position. Third, evaluate those positions (material, king safety, activity, structure) and pick the best. Fourth, the blunder check: what is their best forcing reply to my move? Only then move." },
      { t: "rule", x: "candidates → calculate each once → evaluate the quiet positions → blunder check → move\nspend time where the evaluation forks; play forced moves fast", note: "De Groot's studies of grandmasters found they do not calculate more moves than club players; they look at better ones, because they recognise more patterns. Patterns come from puzzles, spaced." },
      { t: "key", x: "Candidates, one calculation each, evaluate, blunder check. Patterns from thousands of spaced puzzles. Time on the critical moves." }
    ] });
  add({ id: "ch_elo", mode: "chelo", pass: 7, of: 10, title: "Elo: the mathematics of rating", sub: "Expected score and the update", gist: "Your rating predicts your score against any opponent, and every game moves it by K times the surprise. It is the same logistic model the engine uses to turn evaluations into odds.",
    blocks: [
      { t: "p", x: "Arpad Elo's system models each player's strength as a number such that the expected score of A against B is a logistic function of the difference. A 400-point gap means roughly 10 to 1 odds; 200 points about 3 to 1; 100 points about 64%. After a game, each player's rating changes by K times (actual score minus expected score), with K from 10 (established masters) to 40 (new players)." },
      { t: "rule", x: "E_A = 1 / (1 + 10^((R_B − R_A) / 400))\nR_A' = R_A + K × (S_A − E_A)", note: "Lichess and chess.com use Glicko-2, which adds a rating deviation (uncertainty) that makes new ratings move fast and settled ratings move slowly. Same idea, better statistics." },
      { t: "tbl", head: ["Rating gap", "Expected score of the higher player"], rows: [["0", "50%"], ["100", "64%"], ["200", "76%"], ["300", "85%"], ["400", "91%"], ["600", "97%"]] },
      { t: "ex", title: "Worked example", facts: [["You", "1400"], ["Opponent", "1600"], ["Result", "you win"], ["K", "20"]], steps: ["E = 1 / (1 + 10^(200/400)) = 1 / (1 + 3.16) = 0.24.", "Change = 20 × (1 − 0.24) = +15.2.", "Had you lost: 20 × (0 − 0.24) = −4.8."], punch: "Beating a stronger player pays three times what losing to one costs. The system rewards playing up." },
      { t: "key", x: "E = 1/(1+10^(diff/400)). Change = K(S − E). 100 points ≈ 64%, 200 ≈ 76%, 400 ≈ 91%." },
      { t: "how", drill: "Elo", ask: "Expected score, or the rating change.", steps: ["Difference over 400, as a power of ten.", "E = 1 over (1 + that).", "Change = K × (S − E)."], tip: "Anchor on the table: 100 → 64, 200 → 76, 400 → 91. Interpolate." }
    ] });
  add({ id: "ch_eval", mode: "chwp", pass: 7, of: 10, title: "Reading an engine", sub: "Centipawns, win probability, and your accuracy", gist: "+1.5 is not 'one and a half pawns', it is about 72% winning chances. Every grade the Play board gives you comes from the drop in that probability.",
    blocks: [
      { t: "p", x: "Engines report evaluations in centipawns (hundredths of a pawn) from White's view: +1.00 means White is better by about a pawn's worth. The useful translation is to winning chances, with a logistic curve: 0 is 50%, +1 about 65%, +2 about 80%, +3 about 90%, and it flattens from there. A move's quality is the drop in winning probability from the best move to the one played, which is how lichess, chess.com and this app grade moves." },
      { t: "rule", x: "win% ≈ 50 + 50 × (2 / (1 + e^(−0.00368 × cp)) − 1)\ngrade: drop ≤ 2% Best · ≤ 6% Good · ≤ 12% Inaccuracy · ≤ 25% Mistake · more: Blunder", note: "Accuracy over a game is a function of the average centipawn loss: 103 × e^(−0.0435 × ACPL) − 3. An ACPL of 20 is about 90% accuracy, club level; 10 is master level." },
      { t: "tbl", head: ["Eval", "Win chance"], rows: [["0.0", "50%"], ["+0.5", "57%"], ["+1.0", "65%"], ["+2.0", "80%"], ["+3.0", "90%"], ["+5.0", "97%"]] },
      { t: "p", x: "Why it matters: a 'mistake' at +5 that drops to +3 costs almost nothing (97% to 90%), while the same two-pawn drop from +1 to −1 costs 30 points of probability. Precision matters most in balanced positions. Spend your time there." },
      { t: "key", x: "Centipawns → win probability via the logistic curve. Grades are probability drops. Balanced positions deserve the most care." },
      { t: "how", drill: "Evals to odds", ask: "What are White's winning chances?", steps: ["Anchor: +1 is 65, +2 is 80, +3 is 90.", "Interpolate; negative evals mirror around 50."], tip: "After every game in Play, look at your worst move's drop. That number is the lesson." }
    ] });

  /* ---------------- stage 7: the pro path ---------------- */
  add({ id: "ch_pro", mode: "none", title: "From club to master: the programme", sub: "What to study, in what proportion, and how to measure it", gist: "Tactics until 1500, endgames and calculation to 2000, openings and deep strategy after. The ratio matters more than the hours.",
    blocks: [
      { t: "p", x: "The evidence from coaches and from the data on millions of online games is consistent: below 1500, games are decided by tactics the loser did not see, so the fastest gain is pattern training with feedback (puzzles, spaced) plus the blunder check in every game. From 1500 to 2000, endgame technique and calculation depth decide; from 2000 up, opening preparation and positional understanding. Playing long games and reviewing every one with an engine, looking for the first mistake, is the thread through all of it." },
      { t: "tbl", head: ["Rating", "Study mix", "Play", "Books"], rows: [["< 1200", "70% tactics, 20% endgames, 10% openings (principles only)", "15+10 games, review each", "Bobby Fischer Teaches Chess; Chess Tactics for Students (Bain)"], ["1200–1600", "50% tactics, 25% endgames, 15% strategy, 10% openings", "30-minute games, one a day", "Silman's Endgame Course (to your level); Logical Chess Move by Move (Chernev)"], ["1600–2000", "35% tactics/calculation, 25% endgames, 25% strategy, 15% a narrow repertoire", "classical games, tournaments", "My System (Nimzowitsch); Reassess Your Chess (Silman); Dvoretsky's Endgame Manual"], ["2000+", "calculation (Aagaard), deep opening prep, annotated master games", "rated tournaments", "Grandmaster Preparation series; Zurich 1953 (Bronstein); Kasparov's My Great Predecessors"]] },
      { t: "rule", x: "every game reviewed: find the first mistake, name the pattern, add it to the drills\npuzzles daily, spaced: the tactics rating here is your pattern store", note: "Lichess (free) for puzzles, the opening explorer and analysis; Stockfish is built into it. Chessable for spaced-repetition opening and endgame courses, which use the same Leitner idea as this app." },
      { t: "p", x: "The level page tracks two numbers: your move quality against the engine (the same grading as the Play board, over your last hundred moves) and a tactics rating that moves like Elo as you solve the drills. Beat each engine level, raise the tactics rating past 1500, and keep the accuracy above 85%: that is the club-to-expert road, measured." },
      { t: "key", x: "Tactics first, then endgames and calculation, then openings. Review every game. Measure with the tactics rating and the accuracy, and raise both." }
    ] });

  var PATH = [
    { title: "The board", sub: "Rules and notation", blurb: "The names of the squares, how each piece moves, and how games end.", ids: ["ch_board", "ch_pieces", "ch_check"] },
    { title: "Material", sub: "The count", blurb: "What the pieces are worth and how to count a position in ten seconds.", ids: ["ch_value", "ch_count"] },
    { title: "Tactics", sub: "Forks, pins, mates", blurb: "The patterns that decide most games: forks, line tactics, mate in one and two, and finding the best move by checks, captures, threats.", ids: ["ch_fork", "ch_pin", "ch_mate1", "ch_mate2", "ch_best"] },
    { title: "Openings", sub: "Principles and families", blurb: "Centre, development, king safety, and the sixteen openings you will actually meet.", ids: ["ch_openprin", "ch_openings"] },
    { title: "Endgames", sub: "Technique", blurb: "The basic mates, the square rule, the opposition, and the two rook endings every player must know.", ids: ["ch_kq", "ch_square", "ch_opp", "ch_rook"] },
    { title: "Strategy", sub: "Pawns and pieces", blurb: "Pawn structure as the long-term truth, and how to judge each piece's quality.", ids: ["ch_pawns", "ch_pieces2"] },
    { title: "Calculation and the numbers", sub: "Thinking, Elo, engines", blurb: "The calculation method, the mathematics of rating, and how to read an engine's evaluation and your own accuracy.", ids: ["ch_calc", "ch_elo", "ch_eval"] },
    { title: "The pro path", sub: "Club to master", blurb: "The study mix by rating, the books, and how the level page measures the road.", ids: ["ch_pro"] }
  ];

  var FORMULAS = [
    { id: "ch_pts", name: "Piece values", topic: "Material", lesson: "ch_value", f: "P 1 · N 3 · B 3 · R 5 · Q 9", anchors: [["bishop pair", "+0.5"], ["rook for minor", "+2, 'the exchange'"]], note: "An average; activity and structure adjust it." },
    { id: "ch_sq", name: "The square rule", topic: "Endgames", lesson: "ch_square", f: "king catches if k ≤ d (pawn to move) or k ≤ d + 1 (king to move)", anchors: [["start rank", "counts one further"]], note: "King distance is the larger of file and rank difference." },
    { id: "ch_oppf", name: "Opposition", topic: "Endgames", lesson: "ch_opp", f: "same line, one square between, other side to move", anchors: [["key squares", "two ranks in front of the pawn"]], note: "Same-colour square as the enemy king, when it is their move." },
    { id: "ch_elof", name: "Expected score", topic: "Rating", lesson: "ch_elo", f: "E = [1 // 1 + 10^{(R_{B} − R_{A}) / 400}]", vars: [["R_A, R_B", "the two ratings"]], anchors: [["+100", "64%"], ["+200", "76%"], ["+400", "91%"]], note: "" },
    { id: "ch_upd", name: "Rating update", topic: "Rating", lesson: "ch_elo", f: "R' = R + K · (S − E)", vars: [["K", "10 to 40"], ["S", "1 win, ½ draw, 0 loss"]], anchors: [["1400 beats 1600, K 20", "+15"]], note: "" },
    { id: "ch_wpf", name: "Win probability", topic: "Engines", lesson: "ch_eval", f: "win% = 50 + 50 · (2 / (1 + e^{−0.00368 · cp}) − 1)", vars: [["cp", "centipawns for the side"]], anchors: [["+100", "65%"], ["+200", "80%"], ["+300", "90%"]], note: "Grades are drops in this number." },
    { id: "ch_accf", name: "Accuracy", topic: "Engines", lesson: "ch_eval", f: "accuracy = 103.17 · e^{−0.0435 · ACPL} − 3.17", vars: [["ACPL", "average centipawn loss per move"]], anchors: [["ACPL 10", "≈ 96%"], ["ACPL 20", "≈ 90%"], ["ACPL 50", "≈ 81%"]], note: "The lichess formula." },
    { id: "ch_knight", name: "Knight reach", topic: "The board", lesson: "ch_pieces", f: "centre 8 squares · edge 4 · corner 2", anchors: [["a knight on the rim", "is dim"]], note: "" },
    { id: "ch_cct", name: "CCT", topic: "Tactics", lesson: "ch_best", f: "Checks · Captures · Threats, both sides, every move", anchors: [], note: "Then the blunder check." },
    { id: "ch_mates", name: "Mate in one test", topic: "Tactics", lesson: "ch_mate1", f: "for each check: king move? capture? block?", anchors: [["three no's", "mate"]], note: "" },
    { id: "ch_lucena", name: "Lucena and Philidor", topic: "Endgames", lesson: "ch_rook", f: "Lucena: rook to the 4th, bridge → win · Philidor: rook on the 3rd, then checks from behind → draw", anchors: [], note: "Rooks behind passed pawns." },
    { id: "ch_tempo", name: "Tempo", topic: "Openings", lesson: "ch_openprin", f: "1 tempo ≈ ⅓ pawn in open positions", anchors: [["a gambit", "a pawn for 2–3 tempi"]], note: "" }
  ];
  var GLOSSARY = [
    ["fork", ["forks", "double attack"], "One move that attacks two targets at once.", "ch_fork"],
    ["pin", ["pinned", "pins"], "A piece that cannot move without exposing a more valuable piece behind it.", "ch_pin"],
    ["skewer", ["skewers"], "A line attack on a valuable piece that wins the piece behind it when it moves.", "ch_pin"],
    ["discovered attack", ["discovery", "discovered check"], "Moving a piece off a line so the piece behind it attacks.", "ch_pin"],
    ["loose piece", ["loose", "hanging"], "An undefended piece: the usual target of a fork.", "ch_fork"],
    ["back rank", ["back-rank mate"], "The first or eighth rank; a king trapped there by its own pawns is mated by a rook or queen.", "ch_check"],
    ["stalemate", [], "No legal move and not in check: a draw.", "ch_check"],
    ["tempo", ["tempi"], "One move's worth of time. Gaining a tempo means making a useful move that forces the opponent to waste one.", "ch_openprin"],
    ["gambit", ["gambits"], "A pawn sacrificed in the opening for development or initiative.", "ch_openprin"],
    ["outpost", ["outposts"], "A square that cannot be attacked by an enemy pawn, ideal for a knight.", "ch_pawns"],
    ["passed pawn", ["passed pawns", "passer"], "A pawn with no enemy pawn ahead of it on its file or the adjacent files.", "ch_pawns"],
    ["isolated pawn", ["isolani", "isolated"], "A pawn with no friendly pawn on either adjacent file.", "ch_pawns"],
    ["opposition", [], "Kings facing with one square between, the other side to move.", "ch_opp"],
    ["Lucena", ["Lucena position"], "The winning rook-and-pawn position: king in front of the pawn, bridge with the rook.", "ch_rook"],
    ["Philidor", ["Philidor position"], "The drawing rook-and-pawn position: rook on the third rank, then checks from behind.", "ch_rook"],
    ["centipawn", ["centipawns", "cp"], "A hundredth of a pawn, the unit of engine evaluations.", "ch_eval"],
    ["ACPL", ["average centipawn loss"], "The average, per move, of how much your moves fell short of the engine's best.", "ch_eval"],
    ["Elo", ["rating"], "The rating system in which the expected score is a logistic function of the rating gap.", "ch_elo"],
    ["candidate moves", ["candidates"], "The short list of moves worth calculating, written before any of them is calculated.", "ch_calc"],
    ["CCT", ["checks, captures, threats"], "The order in which to look at forcing moves, for both sides, every move.", "ch_best"],
    ["the exchange", ["win the exchange"], "A rook for a minor piece, about two points.", "ch_value"]
  ];
  var READING = [
    { g: "Start here", items: [["Bobby Fischer Teaches Chess", "Fischer, Margulies, Mosenfelder. Programmed mate patterns. Still the fastest first book."], ["Logical Chess: Move by Move", "Irving Chernev. Every move of thirty-three games explained. The book for the first thousand points."], ["Chess Tactics for Students", "John Bain. The patterns, one page each, with exercises."]] },
    { g: "Endgames and strategy", items: [["Silman's Complete Endgame Course", "Jeremy Silman. Organised by rating, so you learn only what your level needs."], ["My System", "Aron Nimzowitsch. Blockade, overprotection, the passed pawn, prophylaxis: the vocabulary of positional chess."], ["How to Reassess Your Chess", "Jeremy Silman. Imbalances: how to evaluate a position and make a plan from it."], ["Dvoretsky's Endgame Manual", "Mark Dvoretsky. The reference. Blue-highlighted positions are the ones to know cold."]] },
    { g: "Calculation and the mind", items: [["Think Like a Grandmaster", "Alexander Kotov. Candidate moves and the tree of analysis."], ["Thought and Choice in Chess", "Adriaan de Groot. The study that showed masters see, not calculate, more."], ["Grandmaster Preparation: Calculation", "Jacob Aagaard. For 2000 and up."], ["Peak", "Anders Ericsson. Deliberate practice, with chess as the central example."]] },
    { g: "Tools", items: [["Lichess", "Free: puzzles with a rating, analysis with Stockfish, the opening explorer, and every game you play saved. The analysis board is where to review games."], ["Chessable", "Spaced-repetition courses for openings and endgames: the same Leitner idea as this app."], ["Stockfish", "The engine, open source. The grading in Play is a small cousin of it."]] }
  ];
  var RANKS = [{ xp: 0, name: "Pawn" }, { xp: 300, name: "Knight" }, { xp: 1000, name: "Bishop" }, { xp: 2500, name: "Rook" }, { xp: 5000, name: "Queen" }, { xp: 9000, name: "King" }, { xp: 15000, name: "Master" }, { xp: 25000, name: "Grandmaster" }];

  registerCourse({
    id: "chess", name: "Chess", short: "CH", glyph: "♞", kind: "chess", color: "#34A96F",
    tagline: "Rules to master, with an engine that grades every move.",
    blurb: "The board, material, tactics verified by the engine, openings, endgame technique, strategy, calculation, and the mathematics of rating and evaluation. Play graded games against six engine levels; a tactics rating that moves like Elo.",
    path: PATH, lessons: LESSONS, drills: CH_DRILLS, formulas: FORMULAS, glossary: GLOSSARY, reading: READING, ranks: RANKS,
    apply: [{ id: "play", label: "Play the engine", blurb: "Six levels, every move graded", min: 15 }, { id: "rush", label: "Tactics rush", blurb: "Ten rated puzzles", min: 8 }]
  });
})();
