/* ============================================================
   SPANISH: the data
   Vocabulary in frequency-ordered sets, paradigm tables, word-order
   and pronunciation data, dialogues, graded readers, dictation and
   writing. Row: [word, gloss, part of speech, forms, example, example gloss]
   Latin American pronunciation is the default (seseo); the voseo of
   Argentina and the vosotros of Spain are noted where they matter.
   ============================================================ */

var ES_VOCAB = {
  es_v1: [
    ["yo", "I", "pron", "me (me), mi/mis (my)", "Yo soy Erik.", "I am Erik."],
    ["tú", "you (informal)", "pron", "te (you), tu/tus (your); vos in Argentina", "¿Cómo te llamas?", "What's your name?"],
    ["él", "he", "pron", "lo (him), su (his)", "Él vive en Madrid.", "He lives in Madrid."],
    ["ella", "she", "pron", "la (her), su (her)", "Ella es profesora.", "She is a teacher."],
    ["usted", "you (formal)", "pron", "takes the él/ella verb form", "¿Usted es de Canadá?", "Are you from Canada?"],
    ["nosotros", "we", "pron", "nosotras (f.), nos (us), nuestro (our)", "Nosotros jugamos hockey.", "We play hockey."],
    ["ellos", "they", "pron", "ellas (f.), los/las (them), su (their)", "Ellos están aquí.", "They are here."],
    ["hola", "hello", "phrase", "", "¡Hola! ¿Qué tal?", "Hi! How's it going?"],
    ["adiós", "goodbye", "phrase", "hasta luego = see you later", "Adiós, hasta mañana.", "Bye, see you tomorrow."],
    ["gracias", "thank you", "phrase", "muchas gracias; de nada = you're welcome", "Muchas gracias por la ayuda.", "Thanks a lot for the help."],
    ["por favor", "please", "phrase", "", "Un café, por favor.", "A coffee, please."],
    ["sí", "yes", "adv", "", "Sí, claro.", "Yes, of course."],
    ["no", "no / not", "adv", "before the verb", "No sé.", "I don't know."],
    ["y", "and", "conj", "e before i-/hi-", "Café y leche.", "Coffee and milk."],
    ["ser", "to be (identity, origin, time)", "verb", "soy, eres, es, somos, sois, son", "Soy estudiante.", "I am a student."],
    ["estar", "to be (location, state)", "verb", "estoy, estás, está, estamos, estáis, están", "Estoy cansado.", "I am tired."],
    ["tener", "to have", "verb", "tengo, tienes, tiene, tenemos, tenéis, tienen", "Tengo un perro.", "I have a dog."],
    ["llamarse", "to be called", "verb", "me llamo, te llamas, se llama", "Me llamo Ana.", "My name is Ana."],
    ["bien", "well / fine", "adv", "muy bien = very well", "Estoy bien, gracias.", "I'm fine, thanks."],
    ["qué", "what", "pron", "", "¿Qué es esto?", "What is this?"],
    ["quién", "who", "pron", "quiénes (pl.)", "¿Quién es?", "Who is it?"],
    ["dónde", "where", "adv", "adónde = where to", "¿Dónde vives?", "Where do you live?"],
    ["cómo", "how", "adv", "", "¿Cómo estás?", "How are you?"],
    ["por qué", "why", "adv", "porque = because", "¿Por qué no?", "Why not?"],
    ["cuándo", "when", "adv", "", "¿Cuándo es el partido?", "When is the game?"],
    ["también", "also / too", "adv", "tampoco = neither", "Yo también.", "Me too."],
    ["perdón", "sorry / excuse me", "phrase", "disculpe (formal), lo siento = I'm sorry", "Perdón, ¿dónde está la estación?", "Excuse me, where is the station?"],
    ["un poco", "a little", "adv", "", "Hablo un poco de español.", "I speak a little Spanish."],
    ["mucho", "much / a lot / very", "adv", "mucha, muchos, muchas as an adjective", "Muchas gracias.", "Thanks a lot."],
    ["de", "of / from", "prep", "del = de + el", "Soy de Canadá.", "I'm from Canada."]
  ],
  es_v2: [
    ["ir", "to go", "verb", "voy, vas, va, vamos, vais, van; ir a + inf = going to", "Voy a casa.", "I'm going home."],
    ["venir", "to come", "verb", "vengo, vienes, viene, venimos, venís, vienen", "¿Vienes mañana?", "Are you coming tomorrow?"],
    ["ver", "to see", "verb", "veo, ves, ve, vemos, veis, ven", "Te veo.", "I see you."],
    ["decir", "to say / tell", "verb", "digo, dices, dice, decimos, decís, dicen", "¿Qué dices?", "What are you saying?"],
    ["hacer", "to do / make", "verb", "hago, haces, hace, hacemos, hacéis, hacen", "¿Qué haces hoy?", "What are you doing today?"],
    ["tomar", "to take / drink", "verb", "regular -ar", "Tomo un café.", "I'm having a coffee."],
    ["dar", "to give", "verb", "doy, das, da, damos, dais, dan", "Dame el libro.", "Give me the book."],
    ["saber", "to know (a fact, how to)", "verb", "sé, sabes, sabe, sabemos, sabéis, saben", "No sé.", "I don't know."],
    ["conocer", "to know (a person, a place)", "verb", "conozco, conoces, conoce…", "¿Conoces a Juan?", "Do you know Juan?"],
    ["pensar", "to think", "verb", "pienso, piensas, piensa, pensamos, pensáis, piensan (e→ie)", "Pienso que sí.", "I think so."],
    ["querer", "to want / love", "verb", "quiero, quieres, quiere, queremos, queréis, quieren", "Quiero agua.", "I want water."],
    ["poder", "can / be able to", "verb", "puedo, puedes, puede, podemos, podéis, pueden (o→ue)", "¿Puedes ayudarme?", "Can you help me?"],
    ["deber", "must / should", "verb", "regular -er", "Debo irme.", "I must go."],
    ["vivir", "to live", "verb", "regular -ir", "Vivo en Toronto.", "I live in Toronto."],
    ["trabajar", "to work", "verb", "regular -ar", "Trabaja en un banco.", "He works at a bank."],
    ["comer", "to eat", "verb", "regular -er", "Comemos a las dos.", "We eat at two."],
    ["beber", "to drink", "verb", "regular -er", "Bebo agua.", "I drink water."],
    ["dormir", "to sleep", "verb", "duermo, duermes, duerme, dormimos, dormís, duermen", "El niño duerme.", "The child is sleeping."],
    ["leer", "to read", "verb", "regular -er; leyó, leyeron in the past", "Leo un libro.", "I'm reading a book."],
    ["escribir", "to write", "verb", "regular -ir; participle escrito", "Escribe tu nombre.", "Write your name."],
    ["hablar", "to speak / talk", "verb", "regular -ar", "Hablamos español.", "We speak Spanish."],
    ["escuchar", "to listen", "verb", "regular -ar", "Escucha la música.", "Listen to the music."],
    ["entender", "to understand", "verb", "entiendo, entiendes… (e→ie)", "No entiendo.", "I don't understand."],
    ["comprar", "to buy", "verb", "regular -ar", "Compro pan.", "I'm buying bread."],
    ["necesitar", "to need", "verb", "regular -ar", "Necesito ayuda.", "I need help."],
    ["gustar", "to be pleasing (to like)", "verb", "me gusta, te gusta, le gusta; me gustan (plural)", "Me gusta el hockey.", "I like hockey."],
    ["ayudar", "to help", "verb", "regular -ar", "¿Me ayudas?", "Will you help me?"],
    ["esperar", "to wait / hope", "verb", "regular -ar", "Espera un momento.", "Wait a moment."],
    ["empezar", "to begin", "verb", "empiezo, empiezas… (e→ie)", "El partido empieza ahora.", "The game starts now."],
    ["terminar", "to finish", "verb", "regular -ar", "¿Cuándo terminas?", "When do you finish?"],
    ["jugar", "to play (a game)", "verb", "juego, juegas, juega, jugamos, jugáis, juegan", "Juego al hockey.", "I play hockey."]
  ],
  es_v3: [
    ["cero", "zero", "num", "", "Cero a cero.", "Nil nil."],
    ["uno", "one", "num", "un before a m. noun, una before f.", "Un café.", "One coffee."],
    ["dos", "two", "num", "", "Dos entradas.", "Two tickets."],
    ["tres", "three", "num", "", "Tres días.", "Three days."],
    ["cuatro", "four", "num", "", "Cuatro semanas.", "Four weeks."],
    ["cinco", "five", "num", "", "A las cinco.", "At five o'clock."],
    ["seis", "six", "num", "", "Seis meses.", "Six months."],
    ["siete", "seven", "num", "", "Siete días.", "Seven days."],
    ["ocho", "eight", "num", "", "Ocho horas.", "Eight hours."],
    ["nueve", "nine", "num", "", "Nueve jugadores.", "Nine players."],
    ["diez", "ten", "num", "", "Diez minutos.", "Ten minutes."],
    ["veinte", "twenty", "num", "veintiuno, veintidós…", "Veinte pesos.", "Twenty pesos."],
    ["cien", "hundred", "num", "ciento uno; doscientos", "Cien euros.", "A hundred euros."],
    ["mil", "thousand", "num", "dos mil", "Mil gracias.", "A thousand thanks."],
    ["hora", "hour; time", "n", "la hora; ¿qué hora es?", "¿Qué hora es?", "What time is it?"],
    ["minuto", "minute", "n", "el minuto", "Cinco minutos más.", "Five more minutes."],
    ["día", "day", "n", "el día (m., despite the -a)", "Buenos días.", "Good morning."],
    ["semana", "week", "n", "la semana", "La semana que viene.", "Next week."],
    ["mes", "month", "n", "el mes, los meses", "Cada mes.", "Every month."],
    ["año", "year", "n", "el año", "¡Feliz año nuevo!", "Happy new year!"],
    ["hoy", "today", "adv", "", "Hoy es lunes.", "Today is Monday."],
    ["mañana", "tomorrow; morning", "adv", "la mañana = the morning", "Hasta mañana.", "See you tomorrow."],
    ["ayer", "yesterday", "adv", "", "Ayer llovió.", "Yesterday it rained."],
    ["ahora", "now", "adv", "", "Ahora me voy.", "I'm leaving now."],
    ["tarde", "late; afternoon", "adv", "la tarde = the afternoon; buenas tardes", "Es tarde.", "It's late."],
    ["temprano", "early", "adv", "", "Me levanto temprano.", "I get up early."],
    ["lunes", "Monday", "n", "el lunes = on Monday; days are lowercase", "El lunes tengo hockey.", "On Monday I have hockey."],
    ["martes", "Tuesday", "n", "", "El martes por la noche.", "Tuesday night."],
    ["miércoles", "Wednesday", "n", "", "El miércoles.", "On Wednesday."],
    ["jueves", "Thursday", "n", "", "El jueves por la mañana.", "Thursday morning."],
    ["viernes", "Friday", "n", "", "¡Por fin viernes!", "Finally Friday!"],
    ["sábado", "Saturday", "n", "", "El sábado hay partido.", "On Saturday there's a game."],
    ["domingo", "Sunday", "n", "", "El domingo descanso.", "On Sunday I rest."],
    ["noche", "night", "n", "la noche; buenas noches", "Buenas noches.", "Good night."]
  ],
  es_v4: [
    ["hombre", "man", "n", "el hombre", "Un hombre mayor.", "An older man."],
    ["mujer", "woman; wife", "n", "la mujer", "Una mujer joven.", "A young woman."],
    ["niño", "child / boy", "n", "la niña = girl; los niños = children", "Dos niños.", "Two children."],
    ["chico", "boy / guy", "n", "la chica = girl", "El chico juega.", "The boy is playing."],
    ["amigo", "friend", "n", "la amiga (f.)", "Mi mejor amigo.", "My best friend."],
    ["familia", "family", "n", "la familia", "Mi familia vive en Canadá.", "My family lives in Canada."],
    ["madre", "mother", "n", "mamá (mum)", "Mi madre llama.", "My mother is calling."],
    ["padre", "father", "n", "papá (dad); los padres = parents", "Mi padre conduce.", "My father drives."],
    ["hermano", "brother", "n", "la hermana = sister; los hermanos = siblings", "Mi hermano es mayor.", "My brother is older."],
    ["casa", "house / home", "n", "la casa; en casa = at home", "Estoy en casa.", "I'm at home."],
    ["piso", "flat / apartment; floor", "n", "el piso; apartamento (Lat. Am.)", "Un piso pequeño.", "A small flat."],
    ["habitación", "room", "n", "la habitación; el cuarto", "Mi habitación es pequeña.", "My room is small."],
    ["cocina", "kitchen", "n", "la cocina; cocinar = to cook", "Comemos en la cocina.", "We eat in the kitchen."],
    ["puerta", "door", "n", "la puerta", "Cierra la puerta.", "Close the door."],
    ["ventana", "window", "n", "la ventana", "Abre la ventana.", "Open the window."],
    ["mesa", "table", "n", "la mesa", "El libro está en la mesa.", "The book is on the table."],
    ["silla", "chair", "n", "la silla", "Una silla más.", "One more chair."],
    ["cama", "bed", "n", "la cama", "Estoy en la cama.", "I'm in bed."],
    ["coche", "car", "n", "el coche; carro (Lat. Am.), auto", "Vamos en coche.", "We go by car."],
    ["ciudad", "city", "n", "la ciudad", "Una ciudad grande.", "A big city."],
    ["país", "country", "n", "el país, los países", "España es un país.", "Spain is a country."],
    ["escuela", "school", "n", "la escuela; el colegio", "Los niños van a la escuela.", "The children go to school."],
    ["trabajo", "work / job", "n", "el trabajo", "Voy al trabajo.", "I'm going to work."],
    ["teléfono", "telephone", "n", "el teléfono; el móvil / celular = mobile", "Mi teléfono no funciona.", "My phone doesn't work."],
    ["ordenador", "computer", "n", "el ordenador (Spain); la computadora (Lat. Am.)", "Un ordenador nuevo.", "A new computer."],
    ["libro", "book", "n", "el libro", "Un buen libro.", "A good book."],
    ["dinero", "money", "n", "el dinero", "No tengo dinero.", "I have no money."],
    ["nombre", "name", "n", "el nombre", "¿Cuál es tu nombre?", "What is your name?"],
    ["cosa", "thing", "n", "la cosa; algo = something; nada = nothing", "Una cosa más.", "One more thing."],
    ["tiempo", "time; weather", "n", "el tiempo", "No tengo tiempo.", "I don't have time."]
  ],
  es_v5: [
    ["comida", "food; meal; lunch", "n", "la comida", "La comida está rica.", "The food is delicious."],
    ["agua", "water", "n", "el agua (f., but el in the singular)", "Un vaso de agua, por favor.", "A glass of water, please."],
    ["café", "coffee", "n", "el café; café con leche", "¿Quieres café?", "Do you want coffee?"],
    ["té", "tea", "n", "el té", "Bebo té.", "I drink tea."],
    ["leche", "milk", "n", "la leche", "¿Leche en el café?", "Milk in the coffee?"],
    ["pan", "bread", "n", "el pan", "Pan fresco.", "Fresh bread."],
    ["mantequilla", "butter", "n", "la mantequilla", "Pan con mantequilla.", "Bread with butter."],
    ["queso", "cheese", "n", "el queso", "Queso manchego.", "Manchego cheese."],
    ["huevo", "egg", "n", "el huevo", "Dos huevos.", "Two eggs."],
    ["carne", "meat", "n", "la carne", "No como carne.", "I don't eat meat."],
    ["pescado", "fish (as food)", "n", "el pescado; el pez = the live fish", "Pescado los viernes.", "Fish on Fridays."],
    ["pollo", "chicken", "n", "el pollo", "Pollo con arroz.", "Chicken with rice."],
    ["verduras", "vegetables", "n", "las verduras", "Come tus verduras.", "Eat your vegetables."],
    ["fruta", "fruit", "n", "la fruta", "Fruta fresca.", "Fresh fruit."],
    ["manzana", "apple", "n", "la manzana", "Una manzana roja.", "A red apple."],
    ["patata", "potato", "n", "la patata (Spain); la papa (Lat. Am.)", "Patatas fritas.", "French fries."],
    ["arroz", "rice", "n", "el arroz", "Arroz blanco.", "White rice."],
    ["sopa", "soup", "n", "la sopa", "Sopa caliente.", "Hot soup."],
    ["azúcar", "sugar", "n", "el azúcar", "Sin azúcar, gracias.", "No sugar, thanks."],
    ["sal", "salt", "n", "la sal", "Un poco de sal.", "A little salt."],
    ["desayuno", "breakfast", "n", "el desayuno; desayunar", "Desayuno a las siete.", "I have breakfast at seven."],
    ["almuerzo", "lunch", "n", "el almuerzo; la comida (Spain)", "Almorzamos juntos.", "We have lunch together."],
    ["cena", "dinner", "n", "la cena; cenar", "La cena está lista.", "Dinner is ready."],
    ["restaurante", "restaurant", "n", "el restaurante", "Un buen restaurante.", "A good restaurant."],
    ["carta", "menu; letter", "n", "la carta; el menú (set menu)", "¿Me trae la carta?", "Can you bring me the menu?"],
    ["cuenta", "the bill", "n", "la cuenta", "La cuenta, por favor.", "The bill, please."],
    ["pedir", "to order / ask for", "verb", "pido, pides, pide… (e→i)", "Quiero pedir.", "I'd like to order."],
    ["hambre", "hunger", "n", "tener hambre = to be hungry", "Tengo hambre.", "I'm hungry."],
    ["sed", "thirst", "n", "tener sed = to be thirsty", "¿Tienes sed?", "Are you thirsty?"],
    ["rico", "tasty; rich", "adj", "rica, ricos, ricas", "¡Qué rico!", "How tasty!"]
  ],
  es_v6: [
    ["despertarse", "to wake up", "verb", "me despierto, te despiertas… (e→ie)", "Me despierto a las seis.", "I wake up at six."],
    ["levantarse", "to get up", "verb", "me levanto", "Me levanto temprano.", "I get up early."],
    ["ducharse", "to shower", "verb", "me ducho", "Me ducho después del entrenamiento.", "I shower after practice."],
    ["vestirse", "to get dressed", "verb", "me visto, te vistes… (e→i)", "¡Vístete!", "Get dressed!"],
    ["cocinar", "to cook", "verb", "regular -ar", "¿Quién cocina esta noche?", "Who's cooking tonight?"],
    ["limpiar", "to clean", "verb", "regular -ar", "Limpio los sábados.", "I clean on Saturdays."],
    ["lavar", "to wash", "verb", "lavarse las manos", "Lávate las manos.", "Wash your hands."],
    ["entrenar", "to train", "verb", "el entrenamiento = practice", "Entreno tres veces por semana.", "I train three times a week."],
    ["descansar", "to rest", "verb", "regular -ar", "Descansa un poco.", "Rest a little."],
    ["sentarse", "to sit down", "verb", "me siento, te sientas… (e→ie)", "Siéntate.", "Sit down."],
    ["abrir", "to open", "verb", "participle abierto", "Abre la puerta.", "Open the door."],
    ["cerrar", "to close", "verb", "cierro, cierras… (e→ie)", "La tienda cierra a las ocho.", "The shop closes at eight."],
    ["ropa", "clothes", "n", "la ropa (singular)", "Ropa nueva.", "New clothes."],
    ["zapato", "shoe", "n", "los zapatos", "Quítate los zapatos.", "Take off your shoes."],
    ["chaqueta", "jacket", "n", "la chaqueta; el abrigo = coat", "Una chaqueta caliente.", "A warm jacket."],
    ["camiseta", "T-shirt / jersey", "n", "la camiseta", "Mi camiseta de hockey.", "My hockey jersey."],
    ["pantalones", "trousers", "n", "los pantalones", "Pantalones azules.", "Blue trousers."],
    ["bolso", "bag", "n", "el bolso; la mochila = backpack", "¿Dónde está mi bolso?", "Where is my bag?"],
    ["llave", "key", "n", "la llave", "Perdí la llave.", "I lost the key."],
    ["reloj", "clock / watch", "n", "el reloj", "Un reloj nuevo.", "A new watch."],
    ["música", "music", "n", "la música", "Me gusta la música.", "I like music."],
    ["película", "film / movie", "n", "la película", "¿Vemos una película?", "Shall we watch a movie?"],
    ["partido", "game / match", "n", "el partido", "¡Ganamos el partido!", "We won the game!"],
    ["equipo", "team; equipment", "n", "el equipo", "Nuestro equipo es bueno.", "Our team is good."],
    ["hockey", "hockey", "n", "el hockey (sobre hielo)", "Juego al hockey.", "I play hockey."],
    ["jugador", "player", "n", "el jugador, la jugadora", "Un buen jugador.", "A good player."],
    ["ganar", "to win; to earn", "verb", "regular -ar", "Queremos ganar.", "We want to win."],
    ["perder", "to lose", "verb", "pierdo, pierdes… (e→ie)", "No quiero perder.", "I don't want to lose."],
    ["gol", "goal (scored)", "n", "el gol; marcar un gol", "¡Gol!", "Goal!"],
    ["entrenamiento", "practice / training", "n", "el entrenamiento", "Hay entrenamiento esta noche.", "There's practice tonight."]
  ],
  es_v7: [
    ["calle", "street", "n", "la calle", "¿Qué calle?", "Which street?"],
    ["camino", "road / way", "n", "el camino", "El camino a la ciudad.", "The way to the city."],
    ["plaza", "square", "n", "la plaza", "Nos vemos en la plaza.", "See you at the square."],
    ["tienda", "shop", "n", "la tienda", "La tienda está abierta.", "The shop is open."],
    ["banco", "bank; bench", "n", "el banco", "El banco está allí.", "The bank is there."],
    ["hospital", "hospital", "n", "el hospital", "¡Al hospital!", "To the hospital!"],
    ["farmacia", "pharmacy", "n", "la farmacia", "¿Hay una farmacia aquí?", "Is there a pharmacy here?"],
    ["estación", "station", "n", "la estación", "La estación central.", "The central station."],
    ["tren", "train", "n", "el tren", "El tren llega tarde.", "The train is late."],
    ["autobús", "bus", "n", "el autobús; el camión (Mexico), el colectivo (Argentina)", "El autobús viene ya.", "The bus is coming now."],
    ["avión", "plane", "n", "el avión; el vuelo = flight", "Mi vuelo sale a las diez.", "My flight leaves at ten."],
    ["billete", "ticket", "n", "el billete (Spain); el boleto (Lat. Am.)", "Un billete a Sevilla.", "A ticket to Seville."],
    ["derecha", "right", "n", "a la derecha", "Gira a la derecha.", "Turn right."],
    ["izquierda", "left", "n", "a la izquierda", "Está a la izquierda.", "It's on the left."],
    ["recto", "straight ahead", "adv", "todo recto; derecho (Lat. Am.)", "Sigue todo recto.", "Go straight ahead."],
    ["cerca", "near", "adv", "cerca de", "Está cerca.", "It's close."],
    ["lejos", "far", "adv", "lejos de", "¿Está lejos?", "Is it far?"],
    ["aquí", "here", "adv", "acá (Lat. Am.)", "Ven aquí.", "Come here."],
    ["allí", "there", "adv", "allá, ahí", "Ve allí.", "Go there."],
    ["mapa", "map", "n", "el mapa (m.)", "¿Tienes un mapa?", "Do you have a map?"],
    ["hotel", "hotel", "n", "el hotel", "Estamos en un hotel.", "We're at a hotel."],
    ["viaje", "trip", "n", "el viaje; viajar = to travel", "¡Buen viaje!", "Have a good trip!"],
    ["viajar", "to travel", "verb", "regular -ar", "Viajamos en tren.", "We travel by train."],
    ["bicicleta", "bicycle", "n", "la bicicleta, la bici", "Voy en bici.", "I go by bike."],
    ["aparcar", "to park", "verb", "estacionar (Lat. Am.)", "¿Dónde puedo aparcar?", "Where can I park?"],
    ["parar", "to stop", "verb", "regular -ar", "Para aquí.", "Stop here."],
    ["preguntar", "to ask (a question)", "verb", "la pregunta = question", "¿Puedo preguntar algo?", "May I ask something?"],
    ["contestar", "to answer", "verb", "la respuesta = answer; responder", "Contesta la pregunta.", "Answer the question."],
    ["encontrar", "to find", "verb", "encuentro, encuentras… (o→ue)", "No lo encuentro.", "I can't find it."],
    ["llevar", "to carry / take / wear", "verb", "regular -ar; traer = to bring", "Lleva una chaqueta.", "Take a jacket."]
  ],
  es_v8: [
    ["profesor", "teacher", "n", "el profesor, la profesora; el maestro (primary)", "El profesor explica.", "The teacher explains."],
    ["alumno", "pupil", "n", "el alumno, la alumna", "Veinte alumnos.", "Twenty pupils."],
    ["estudiante", "student", "n", "el / la estudiante", "Soy estudiante.", "I'm a student."],
    ["universidad", "university", "n", "la universidad", "Estudio en la universidad.", "I study at university."],
    ["curso", "course; school year", "n", "el curso", "Un curso de español.", "A course in Spanish."],
    ["examen", "exam", "n", "el examen, los exámenes", "Tengo examen el viernes.", "I have an exam on Friday."],
    ["deberes", "homework", "n", "los deberes; la tarea (Lat. Am.)", "¿Hiciste los deberes?", "Did you do the homework?"],
    ["oficina", "office", "n", "la oficina", "Estoy en la oficina.", "I'm at the office."],
    ["jefe", "boss", "n", "el jefe, la jefa", "Mi jefe es amable.", "My boss is kind."],
    ["compañero", "colleague / classmate", "n", "el compañero de trabajo / de clase", "Un compañero de trabajo.", "A colleague from work."],
    ["reunión", "meeting", "n", "la reunión", "Tenemos reunión a las tres.", "We have a meeting at three."],
    ["sueldo", "salary", "n", "el sueldo; el salario", "El sueldo llega el día 25.", "The salary comes on the 25th."],
    ["empresa", "company", "n", "la empresa", "Una empresa española.", "A Spanish company."],
    ["cliente", "customer", "n", "el / la cliente", "El cliente siempre tiene razón.", "The customer is always right."],
    ["ingeniero", "engineer", "n", "el ingeniero, la ingeniera", "Ella es ingeniera.", "She is an engineer."],
    ["médico", "doctor", "n", "el médico, la médica; el doctor", "Necesito un médico.", "I need a doctor."],
    ["enfermero", "nurse", "n", "el enfermero, la enfermera", "La enfermera ayuda.", "The nurse helps."],
    ["policía", "police; police officer", "n", "la policía (the force); el / la policía (the officer)", "¡Llama a la policía!", "Call the police!"],
    ["cocinero", "cook / chef", "n", "el cocinero, la cocinera", "El cocinero prepara la comida.", "The cook prepares the food."],
    ["estudiar", "to study", "verb", "regular -ar", "Estudio para el examen.", "I'm studying for the exam."],
    ["aprender", "to learn", "verb", "regular -er", "Aprendo español.", "I'm learning Spanish."],
    ["practicar", "to practise", "verb", "regular -ar", "Practica cada día.", "Practise every day."],
    ["error", "mistake", "n", "el error", "Todos cometemos errores.", "Everyone makes mistakes."],
    ["correcto", "correct / right", "adj", "tener razón = to be right", "Es correcto.", "It's correct."],
    ["difícil", "difficult", "adj", "difíciles", "El español no es tan difícil.", "Spanish isn't that hard."],
    ["fácil", "easy", "adj", "fáciles", "Fue fácil.", "It was easy."],
    ["importante", "important", "adj", "", "Es importante.", "It's important."],
    ["listo", "ready (with estar); clever (with ser)", "adj", "estoy listo / es listo", "¿Estás listo?", "Are you ready?"],
    ["pregunta", "question", "n", "la pregunta", "Tengo una pregunta.", "I have a question."],
    ["respuesta", "answer", "n", "la respuesta", "La respuesta correcta.", "The correct answer."]
  ],
  es_v9: [
    ["cabeza", "head", "n", "la cabeza; dolor de cabeza", "Me duele la cabeza.", "My head hurts."],
    ["mano", "hand", "n", "la mano (f., despite the -o)", "Lávate las manos.", "Wash your hands."],
    ["pie", "foot", "n", "el pie, los pies; a pie = on foot", "Me duele el pie.", "My foot hurts."],
    ["pierna", "leg", "n", "la pierna", "Se rompió la pierna.", "He broke his leg."],
    ["rodilla", "knee", "n", "la rodilla", "Me lesioné la rodilla.", "I hurt my knee."],
    ["brazo", "arm", "n", "el brazo", "El brazo izquierdo.", "The left arm."],
    ["ojo", "eye", "n", "el ojo", "Ojos azules.", "Blue eyes."],
    ["oreja", "ear", "n", "la oreja (outer); el oído (inner)", "Me duele el oído.", "My ear hurts."],
    ["boca", "mouth", "n", "la boca", "Abre la boca.", "Open your mouth."],
    ["nariz", "nose", "n", "la nariz", "Una nariz roja.", "A red nose."],
    ["estómago", "stomach", "n", "el estómago", "Dolor de estómago.", "Stomach ache."],
    ["corazón", "heart", "n", "el corazón", "El corazón late.", "The heart beats."],
    ["espalda", "back", "n", "la espalda", "Dolor de espalda.", "Back pain."],
    ["pelo", "hair", "n", "el pelo; el cabello", "Pelo rubio.", "Blond hair."],
    ["doler", "to hurt", "verb", "me duele, me duelen (like gustar)", "Me duele la rodilla.", "My knee hurts."],
    ["enfermo", "ill / sick", "adj", "estar enfermo", "Estoy enfermo hoy.", "I'm sick today."],
    ["sano", "healthy", "adj", "la salud = health", "Está sano otra vez.", "He's healthy again."],
    ["cansado", "tired", "adj", "estar cansado", "Estoy muy cansado.", "I'm very tired."],
    ["medicina", "medicine", "n", "la medicina; el medicamento", "Toma la medicina.", "Take the medicine."],
    ["fiebre", "fever", "n", "la fiebre; tener fiebre", "Tiene fiebre.", "She has a fever."],
    ["resfriado", "a cold", "n", "estar resfriado = to have a cold", "Estoy resfriado.", "I have a cold."],
    ["lesión", "injury", "n", "la lesión", "Una lesión de hockey.", "A hockey injury."],
    ["fuerte", "strong", "adj", "", "Un equipo fuerte.", "A strong team."],
    ["débil", "weak", "adj", "", "Me siento débil.", "I feel weak."],
    ["alto", "tall / high", "adj", "alta", "Es alto.", "He is tall."],
    ["bajo", "short / low", "adj", "baja", "Una silla baja.", "A low chair."],
    ["joven", "young", "adj", "jóvenes", "Un equipo joven.", "A young team."],
    ["viejo", "old", "adj", "mayor = older/elderly (polite)", "Un hombre viejo.", "An old man."],
    ["cuerpo", "body", "n", "el cuerpo", "Un cuerpo fuerte.", "A strong body."],
    ["sentirse", "to feel", "verb", "me siento, te sientes… (e→ie)", "Me siento bien.", "I feel good."]
  ],
  es_v10: [
    ["feliz", "happy", "adj", "felices; contento = glad", "Estoy feliz hoy.", "I'm happy today."],
    ["triste", "sad", "adj", "", "No estés triste.", "Don't be sad."],
    ["enfadado", "angry", "adj", "enojado (Lat. Am.)", "Está enfadado.", "He's angry."],
    ["miedo", "fear", "n", "tener miedo = to be afraid", "No tengo miedo.", "I'm not afraid."],
    ["nervioso", "nervous", "adj", "nerviosa", "Nervioso antes del partido.", "Nervous before the game."],
    ["tranquilo", "calm", "adj", "¡Tranquilo! = take it easy", "Tranquilo, hay tiempo.", "Relax, there's time."],
    ["contento", "pleased / glad", "adj", "contenta", "Estoy contento.", "I'm pleased."],
    ["decepcionado", "disappointed", "adj", "decepcionada", "Decepcionado con el resultado.", "Disappointed with the result."],
    ["orgulloso", "proud", "adj", "orgulloso de", "Estoy orgulloso de ti.", "I'm proud of you."],
    ["aburrido", "boring (ser) / bored (estar)", "adj", "", "Una película aburrida.", "A boring film."],
    ["divertido", "fun / funny", "adj", "", "¡Qué divertido!", "How fun!"],
    ["interesante", "interesting", "adj", "", "Un libro interesante.", "An interesting book."],
    ["raro", "strange / weird", "adj", "", "Es raro.", "That's strange."],
    ["bonito", "pretty / nice", "adj", "lindo (Lat. Am.); hermoso = beautiful", "Un día bonito.", "A nice day."],
    ["amable", "kind / nice", "adj", "", "Es muy amable.", "He's very kind."],
    ["tonto", "silly / stupid", "adj", "", "Fue una tontería.", "That was silly."],
    ["odiar", "to hate", "verb", "regular -ar", "Odio perder.", "I hate losing."],
    ["esperar", "to hope", "verb", "espero que + subjunctive", "Espero que sí.", "I hope so."],
    ["creer", "to believe / think", "verb", "creo que…", "Creo que sí.", "I think so."],
    ["quizás", "maybe", "adv", "tal vez, a lo mejor", "Quizás mañana.", "Maybe tomorrow."],
    ["seguro", "sure / safe", "adj", "seguramente = probably", "Seguro que sí.", "Surely yes."],
    ["de verdad", "really", "adv", "¿de verdad? = really?", "¿De verdad?", "Really?"],
    ["en realidad", "actually", "adv", "", "En realidad es bueno.", "Actually it's good."],
    ["desafortunadamente", "unfortunately", "adv", "por desgracia", "Desafortunadamente no.", "Unfortunately not."],
    ["claro", "of course / clear", "adv", "¡Claro que sí!", "¡Claro!", "Of course!"],
    ["más o menos", "more or less / approximately", "adv", "", "Más o menos diez minutos.", "About ten minutes."],
    ["sobre todo", "especially / above all", "adv", "", "Sobre todo en invierno.", "Especially in winter."],
    ["querer decir", "to mean", "verb", "¿qué quieres decir?", "¿Qué quieres decir?", "What do you mean?"],
    ["opinión", "opinion", "n", "la opinión; en mi opinión", "¿Cuál es tu opinión?", "What's your opinion?"],
    ["parecer", "to seem", "verb", "me parece que… = it seems to me", "Me parece bien.", "That seems fine to me."]
  ],
  es_v11: [
    ["tiempo", "weather", "n", "¿qué tiempo hace? = what's the weather like?", "¡Qué tiempo!", "What weather!"],
    ["sol", "sun", "n", "hace sol = it's sunny", "Hace sol.", "It's sunny."],
    ["lluvia", "rain", "n", "llueve = it's raining; llover", "Llueve.", "It's raining."],
    ["nieve", "snow", "n", "nieva = it's snowing; nevar", "¡Nieva!", "It's snowing!"],
    ["viento", "wind", "n", "hace viento", "Hace mucho viento.", "It's very windy."],
    ["nube", "cloud", "n", "la nube; nublado = cloudy", "No hay nubes hoy.", "No clouds today."],
    ["frío", "cold", "adj", "hace frío; tengo frío = I'm cold", "Hace frío fuera.", "It's cold outside."],
    ["calor", "heat", "n", "hace calor; tengo calor", "Un verano de mucho calor.", "A very hot summer."],
    ["grado", "degree", "n", "el grado", "Diez grados bajo cero.", "Ten degrees below zero."],
    ["verano", "summer", "n", "el verano; en verano", "En verano nadamos.", "In summer we swim."],
    ["invierno", "winter", "n", "el invierno", "El invierno es largo.", "Winter is long."],
    ["otoño", "autumn", "n", "el otoño", "En otoño empieza la temporada.", "In autumn the season starts."],
    ["primavera", "spring", "n", "la primavera", "¡Por fin primavera!", "Spring at last!"],
    ["bosque", "forest", "n", "el bosque", "Un bosque grande.", "A big forest."],
    ["lago", "lake", "n", "el lago", "Nadamos en el lago.", "We swim in the lake."],
    ["mar", "sea", "n", "el mar", "El mar está frío.", "The sea is cold."],
    ["montaña", "mountain", "n", "la montaña", "Montañas altas.", "High mountains."],
    ["árbol", "tree", "n", "el árbol", "Un árbol viejo.", "An old tree."],
    ["flor", "flower", "n", "la flor", "Flores bonitas.", "Pretty flowers."],
    ["animal", "animal", "n", "el animal", "Animales salvajes.", "Wild animals."],
    ["perro", "dog", "n", "el perro, la perra", "El perro ladra.", "The dog is barking."],
    ["gato", "cat", "n", "el gato, la gata", "El gato duerme.", "The cat is sleeping."],
    ["caballo", "horse", "n", "el caballo", "Un caballo marrón.", "A brown horse."],
    ["pájaro", "bird", "n", "el pájaro", "Los pájaros cantan.", "The birds are singing."],
    ["toro", "bull", "n", "el toro", "Vimos un toro.", "We saw a bull."],
    ["hielo", "ice", "n", "el hielo; la pista de hielo = the rink", "El hielo está grueso.", "The ice is thick."],
    ["cielo", "sky; heaven", "n", "el cielo", "Un cielo azul.", "A blue sky."],
    ["estrella", "star", "n", "la estrella", "Muchas estrellas.", "Many stars."],
    ["luz", "light", "n", "la luz, las luces", "Enciende la luz.", "Turn on the light."],
    ["oscuro", "dark", "adj", "está oscuro", "Está oscuro.", "It's dark."]
  ],
  es_v12: [
    ["noticias", "news", "n", "las noticias", "¿Viste las noticias?", "Did you see the news?"],
    ["periódico", "newspaper", "n", "el periódico; el diario", "Leo el periódico.", "I read the paper."],
    ["gobierno", "government", "n", "el gobierno", "El gobierno decide.", "The government decides."],
    ["elecciones", "election", "n", "las elecciones", "Las elecciones son en noviembre.", "The elections are in November."],
    ["votar", "to vote", "verb", "regular -ar", "Voto el domingo.", "I vote on Sunday."],
    ["ley", "law", "n", "la ley, las leyes", "Es la ley.", "It's the law."],
    ["impuesto", "tax", "n", "el impuesto", "Impuestos altos.", "High taxes."],
    ["precio", "price", "n", "el precio", "El precio es alto.", "The price is high."],
    ["costar", "to cost", "verb", "cuesta, cuestan (o→ue)", "¿Cuánto cuesta?", "How much does it cost?"],
    ["sociedad", "society", "n", "la sociedad", "La sociedad española.", "Spanish society."],
    ["cultura", "culture", "n", "la cultura", "La cultura mexicana.", "Mexican culture."],
    ["historia", "history; story", "n", "la historia", "La historia de España.", "The history of Spain."],
    ["idioma", "language", "n", "el idioma (m.); la lengua", "El español es un idioma bonito.", "Spanish is a beautiful language."],
    ["mundo", "world", "n", "el mundo; todo el mundo = everyone", "Todo el mundo.", "Everyone / the whole world."],
    ["guerra", "war", "n", "la guerra", "No a la guerra.", "No to war."],
    ["paz", "peace", "n", "la paz", "Paz en el mundo.", "Peace in the world."],
    ["medio ambiente", "environment", "n", "el medio ambiente", "Bueno para el medio ambiente.", "Good for the environment."],
    ["clima", "climate", "n", "el clima (m.)", "El clima cambia.", "The climate is changing."],
    ["tecnología", "technology", "n", "la tecnología", "Nueva tecnología.", "New technology."],
    ["futuro", "future", "n", "el futuro; en el futuro", "En el futuro.", "In the future."],
    ["problema", "problem", "n", "el problema (m.)", "¡No hay problema!", "No problem!"],
    ["solución", "solution", "n", "la solución", "Una buena solución.", "A good solution."],
    ["discutir", "to discuss; to argue", "verb", "regular -ir", "Discutimos de política.", "We discuss politics."],
    ["contar", "to tell; to count", "verb", "cuento, cuentas… (o→ue)", "¡Cuéntame más!", "Tell me more!"],
    ["explicar", "to explain", "verb", "regular -ar", "¿Puedes explicar?", "Can you explain?"],
    ["desarrollo", "development", "n", "el desarrollo", "Un desarrollo rápido.", "A rapid development."],
    ["decidir", "to decide", "verb", "regular -ir", "Tú decides.", "You decide."],
    ["pasar", "to happen; to pass; to spend (time)", "verb", "¿qué pasó? = what happened?", "¿Qué pasó?", "What happened?"],
    ["significar", "to mean", "verb", "regular -ar", "¿Qué significa la palabra?", "What does the word mean?"],
    ["palabra", "word", "n", "la palabra", "Una palabra nueva.", "A new word."]
  ],
  es_v13: [
    ["porque", "because", "conj", "", "Me quedo en casa porque estoy enfermo.", "I'm staying home because I'm sick."],
    ["por eso", "therefore / that's why", "adv", "", "Llueve, por eso tomo el autobús.", "It's raining, so I take the bus."],
    ["aunque", "although", "conj", "+ indicative (fact) or subjunctive (hypothetical)", "Jugamos aunque nevaba.", "We played although it was snowing."],
    ["a pesar de", "despite", "prep", "a pesar de que + clause", "A pesar del frío, entrené.", "Despite the cold, I trained."],
    ["mientras", "while", "conj", "", "Leo mientras cocinas.", "I read while you cook."],
    ["antes de", "before", "prep", "antes de que + subjunctive", "Llama antes de venir.", "Call before coming."],
    ["después de", "after", "prep", "después de que + clause", "Después de comer, salimos.", "After eating, we went out."],
    ["si", "if", "conj", "no accent (sí = yes)", "Si llueve, nos quedamos en casa.", "If it rains, we stay home."],
    ["además", "besides / moreover", "adv", "", "Además, es barato.", "Besides, it's cheap."],
    ["en cambio", "on the other hand", "adv", "sin embargo = however", "A mí, en cambio, me gusta el invierno.", "I, on the other hand, like winter."],
    ["entonces", "so / then", "adv", "", "¿Entonces no vienes?", "So you're not coming?"],
    ["sin embargo", "however / nevertheless", "adv", "", "Hacía frío; sin embargo, fuimos.", "It was cold; however, we went."],
    ["todavía", "still / yet", "adv", "aún", "Todavía vivo aquí.", "I still live here."],
    ["ya", "already; now", "adv", "ya no = no longer", "¿Ya estás listo?", "Are you ready already?"],
    ["pronto", "soon", "adv", "hasta pronto", "Nos vemos pronto.", "See you soon."],
    ["a menudo", "often", "adv", "muchas veces", "Entreno a menudo.", "I train often."],
    ["rara vez", "rarely", "adv", "casi nunca", "Rara vez llega tarde.", "He rarely arrives late."],
    ["siempre", "always", "adv", "", "Siempre tengo hambre.", "I'm always hungry."],
    ["nunca", "never", "adv", "no … nunca (double negative is required)", "Nunca me rindo.", "I never give up."],
    ["a veces", "sometimes", "adv", "", "A veces llueve.", "Sometimes it rains."],
    ["solo", "only / just; alone", "adv", "solamente", "Solo una vez.", "Only once."],
    ["bastante", "quite / enough", "adv", "", "Es bastante bueno.", "It's quite good."],
    ["demasiado", "too (much)", "adv", "", "Es demasiado caro.", "It's too expensive."],
    ["casi", "almost", "adv", "", "Casi listo.", "Almost ready."],
    ["exactamente", "exactly", "adv", "", "¡Exactamente!", "Exactly!"],
    ["en serio", "seriously / really", "adv", "¿en serio?", "¿En serio?", "Seriously?"],
    ["probablemente", "probably", "adv", "", "Probablemente llegará tarde.", "He'll probably be late."],
    ["enseguida", "right away", "adv", "", "¡Ven enseguida!", "Come right away!"],
    ["el uno al otro", "each other", "pron", "nos ayudamos = we help each other (reflexive)", "Nos ayudamos el uno al otro.", "We help each other."],
    ["cada", "each / every", "adj", "cada día", "Cada día.", "Every day."]
  ],
  es_v14: [
    ["vale", "OK (Spain)", "phrase", "", "Vale, nos vemos a las seis.", "OK, see you at six."],
    ["venga", "come on / OK then (Spain)", "phrase", "", "¡Venga, vamos!", "Come on, let's go!"],
    ["¿qué tal?", "how's it going?", "phrase", "", "¿Qué tal el partido?", "How was the game?"],
    ["no pasa nada", "no worries / it's fine", "phrase", "", "No pasa nada.", "No worries."],
    ["¡qué pena!", "what a pity!", "phrase", "", "¡Qué pena que no vinieras!", "What a pity you didn't come!"],
    ["buena suerte", "good luck", "phrase", "¡suerte!", "¡Buena suerte en el examen!", "Good luck on the exam!"],
    ["salud", "cheers; health", "phrase", "also said after a sneeze", "¡Salud!", "Cheers!"],
    ["enhorabuena", "congratulations", "phrase", "felicidades", "¡Enhorabuena!", "Congratulations!"],
    ["tener ganas de", "to feel like (doing)", "phrase", "tengo ganas de…", "Tengo ganas de helado.", "I feel like ice cream."],
    ["dar tiempo", "to have enough time", "phrase", "no me da tiempo", "No me da tiempo.", "I don't have enough time."],
    ["arreglarse", "to work out / get sorted", "verb", "se arregla", "Ya se arreglará.", "It'll work out."],
    ["sentirse como en casa", "to feel at home", "phrase", "", "Me siento como en casa en España.", "I feel at home in Spain."],
    ["echar de menos", "to miss (someone)", "phrase", "extrañar (Lat. Am.)", "Echo de menos a mi familia.", "I miss my family."],
    ["estar de acuerdo", "to agree", "phrase", "estoy de acuerdo contigo", "Estoy de acuerdo contigo.", "I agree with you."],
    ["llevarse bien", "to get along", "phrase", "nos llevamos bien", "Nos llevamos bien.", "We get along."],
    ["poder permitirse", "to afford", "phrase", "", "No me lo puedo permitir.", "I can't afford it."],
    ["me da igual", "I don't care / it's all the same to me", "phrase", "", "Me da igual.", "I don't care."],
    ["rendirse", "to give up", "verb", "me rindo", "¡No te rindas!", "Don't give up!"],
    ["tener ilusión por", "to look forward to", "phrase", "", "Tengo muchas ganas de ver el partido.", "I'm really looking forward to the game."],
    ["averiguar", "to find out", "verb", "regular -ar", "Averigua cuándo sale el tren.", "Find out when the train leaves."],
    ["dar pena", "to feel sorry for", "phrase", "me da pena", "Me da pena él.", "I feel sorry for him."],
    ["visitar", "to visit", "verb", "regular -ar", "Visitamos a la abuela.", "We're visiting grandma."],
    ["no importa", "it doesn't matter", "phrase", "", "No importa quién gane.", "It doesn't matter who wins."],
    ["de todas formas", "anyway / in any case", "phrase", "de todos modos", "De todas formas, nos vemos mañana.", "Anyway, see you tomorrow."],
    ["¿qué te parece?", "what do you think (of)? / how about?", "phrase", "", "¿Qué te parece un café?", "How about a coffee?"],
    ["en vez de", "instead of", "prep", "en lugar de", "Té en vez de café.", "Tea instead of coffee."],
    ["por cierto", "by the way", "phrase", "", "Por cierto, ¿viste el partido?", "By the way, did you see the game?"],
    ["¡ojalá!", "I hope so / if only", "phrase", "ojalá que + subjunctive", "¡Ojalá ganemos!", "I hope we win!"],
    ["tener curiosidad", "to be curious", "phrase", "", "Tengo curiosidad por España.", "I'm curious about Spain."],
    ["ni idea", "no idea", "phrase", "", "Ni idea.", "No idea."]
  ]
};

/* ---- paradigm tables ---- */
var ES_GENDER = {
  name: "El or la", cols: ["noun", "article", "meaning"], ask: [1], given: 0, gloss: 2, choice: true, target: 5,
  q: "Is it <b>el</b> or <b>la</b> {w} ({g})?",
  rule: { 1: "-o is usually masculine, -a usually feminine. Famous exceptions: el día, el mapa, el problema, el idioma, el clima (Greek -ma words are masculine); la mano, la foto, la moto. Nouns in -ción, -sión, -dad, -tad, -tud are feminine; -or, -aje are masculine." },
  rows: [["libro", "el", "book"], ["casa", "la", "house"], ["día", "el", "day"], ["mano", "la", "hand"], ["problema", "el", "problem"], ["ciudad", "la", "city"], ["coche", "el", "car"], ["noche", "la", "night"],
    ["mapa", "el", "map"], ["foto", "la", "photo"], ["idioma", "el", "language"], ["universidad", "la", "university"], ["reloj", "el", "watch"], ["canción", "la", "song"], ["viaje", "el", "trip"], ["calle", "la", "street"],
    ["agua", "el (f.)", "water"], ["clima", "el", "climate"], ["flor", "la", "flower"], ["color", "el", "colour"], ["leche", "la", "milk"], ["pie", "el", "foot"], ["sal", "la", "salt"], ["pan", "el", "bread"],
    ["gente", "la", "people"], ["equipo", "el", "team"], ["clase", "la", "class"], ["lápiz", "el", "pencil"], ["moto", "la", "motorbike"], ["sistema", "el", "system"]]
};
var ES_PLURAL = {
  name: "Plurals", cols: ["singular", "plural", "meaning"], ask: [1], given: 0, gloss: 2, target: 7,
  q: "{w} ({g}): give the <b>plural</b>.",
  rule: { 1: "Vowel + -s; consonant + -es; -z → -ces; words ending in -s with an unstressed last syllable do not change (el lunes, los lunes). A written accent on the last syllable disappears in the plural (canción → canciones)." },
  rows: [["libro", "libros", "book"], ["ciudad", "ciudades", "city"], ["lápiz", "lápices", "pencil"], ["lunes", "lunes", "Monday"], ["canción", "canciones", "song"], ["examen", "exámenes", "exam"], ["mes", "meses", "month"], ["jugador", "jugadores", "player"],
    ["pez", "peces", "fish"], ["luz", "luces", "light"], ["joven", "jóvenes", "young person"], ["país", "países", "country"], ["autobús", "autobuses", "bus"], ["hotel", "hoteles", "hotel"], ["mujer", "mujeres", "woman"], ["crisis", "crisis", "crisis"]]
};
var ES_PRESENT = {
  name: "Present tense", cols: ["infinitive", "yo", "tú", "él / ella / usted", "nosotros", "ellos / ustedes", "meaning"], ask: [1, 2, 3, 4, 5], given: 0, gloss: 6, target: 9,
  q: "{w} ({g}): give the present for <b>{form}</b>.",
  rule: { 1: "Regular endings. -ar: -o -as -a -amos -áis -an. -er: -o -es -e -emos -éis -en. -ir: -o -es -e -imos -ís -en. Yo-irregulars: tengo, hago, digo, salgo, pongo, vengo, sé, conozco, doy, voy, soy, estoy.", 2: "", 3: "Stem changes in the boot (all but nosotros/vosotros): e→ie (pensar, querer, empezar), o→ue (poder, dormir, volver), e→i (pedir, servir).", 4: "Nosotros keeps the stem: pensamos, podemos, pedimos.", 5: "" },
  rows: [["hablar", "hablo", "hablas", "habla", "hablamos", "hablan", "speak"], ["comer", "como", "comes", "come", "comemos", "comen", "eat"], ["vivir", "vivo", "vives", "vive", "vivimos", "viven", "live"],
    ["ser", "soy", "eres", "es", "somos", "son", "be"], ["estar", "estoy", "estás", "está", "estamos", "están", "be (state)"], ["tener", "tengo", "tienes", "tiene", "tenemos", "tienen", "have"],
    ["ir", "voy", "vas", "va", "vamos", "van", "go"], ["hacer", "hago", "haces", "hace", "hacemos", "hacen", "do"], ["decir", "digo", "dices", "dice", "decimos", "dicen", "say"],
    ["poder", "puedo", "puedes", "puede", "podemos", "pueden", "can"], ["querer", "quiero", "quieres", "quiere", "queremos", "quieren", "want"], ["pensar", "pienso", "piensas", "piensa", "pensamos", "piensan", "think"],
    ["dormir", "duermo", "duermes", "duerme", "dormimos", "duermen", "sleep"], ["pedir", "pido", "pides", "pide", "pedimos", "piden", "ask for"], ["jugar", "juego", "juegas", "juega", "jugamos", "juegan", "play"],
    ["saber", "sé", "sabes", "sabe", "sabemos", "saben", "know"], ["conocer", "conozco", "conoces", "conoce", "conocemos", "conocen", "know (people)"], ["venir", "vengo", "vienes", "viene", "venimos", "vienen", "come"],
    ["salir", "salgo", "sales", "sale", "salimos", "salen", "go out"], ["ver", "veo", "ves", "ve", "vemos", "ven", "see"], ["dar", "doy", "das", "da", "damos", "dan", "give"],
    ["empezar", "empiezo", "empiezas", "empieza", "empezamos", "empiezan", "begin"], ["entender", "entiendo", "entiendes", "entiende", "entendemos", "entienden", "understand"], ["volver", "vuelvo", "vuelves", "vuelve", "volvemos", "vuelven", "return"]]
};
var ES_PRETERITE = {
  name: "Preterite", cols: ["infinitive", "yo", "tú", "él / ella", "nosotros", "ellos", "meaning"], ask: [1, 2, 3, 4, 5], given: 0, gloss: 6, target: 10,
  q: "{w} ({g}): give the preterite for <b>{form}</b>.",
  rule: { 1: "Regular preterite. -ar: -é -aste -ó -amos -asteis -aron. -er/-ir: -í -iste -ió -imos -isteis -ieron. The accents on yo and él forms are the tense.", 2: "", 3: "Irregular stems take unaccented endings -e -iste -o -imos -ieron: tuve, hice, dije (dijeron), puse, pude, vine, quise, supe, estuve. Ser and ir share fui, fuiste, fue, fuimos, fueron.", 4: "", 5: "" },
  rows: [["hablar", "hablé", "hablaste", "habló", "hablamos", "hablaron", "speak"], ["comer", "comí", "comiste", "comió", "comimos", "comieron", "eat"], ["vivir", "viví", "viviste", "vivió", "vivimos", "vivieron", "live"],
    ["ser / ir", "fui", "fuiste", "fue", "fuimos", "fueron", "be / go"], ["tener", "tuve", "tuviste", "tuvo", "tuvimos", "tuvieron", "have"], ["hacer", "hice", "hiciste", "hizo", "hicimos", "hicieron", "do"],
    ["decir", "dije", "dijiste", "dijo", "dijimos", "dijeron", "say"], ["estar", "estuve", "estuviste", "estuvo", "estuvimos", "estuvieron", "be"], ["poder", "pude", "pudiste", "pudo", "pudimos", "pudieron", "can"],
    ["poner", "puse", "pusiste", "puso", "pusimos", "pusieron", "put"], ["venir", "vine", "viniste", "vino", "vinimos", "vinieron", "come"], ["querer", "quise", "quisiste", "quiso", "quisimos", "quisieron", "want"],
    ["ver", "vi", "viste", "vio", "vimos", "vieron", "see"], ["dar", "di", "diste", "dio", "dimos", "dieron", "give"], ["jugar", "jugué", "jugaste", "jugó", "jugamos", "jugaron", "play"],
    ["leer", "leí", "leíste", "leyó", "leímos", "leyeron", "read"], ["dormir", "dormí", "dormiste", "durmió", "dormimos", "durmieron", "sleep"], ["pedir", "pedí", "pediste", "pidió", "pedimos", "pidieron", "ask for"]]
};
var ES_IMPERFECT = {
  name: "Imperfect", cols: ["infinitive", "yo", "tú", "él / ella", "nosotros", "ellos", "meaning"], ask: [1, 2, 3, 4, 5], given: 0, gloss: 6, target: 9,
  q: "{w} ({g}): give the imperfect for <b>{form}</b>.",
  rule: { 1: "The imperfect is almost entirely regular. -ar: -aba -abas -aba -ábamos -abais -aban. -er/-ir: -ía -ías -ía -íamos -íais -ían. Only three irregulars: ser (era), ir (iba), ver (veía).", 2: "", 3: "", 4: "", 5: "" },
  rows: [["hablar", "hablaba", "hablabas", "hablaba", "hablábamos", "hablaban", "speak"], ["comer", "comía", "comías", "comía", "comíamos", "comían", "eat"], ["vivir", "vivía", "vivías", "vivía", "vivíamos", "vivían", "live"],
    ["ser", "era", "eras", "era", "éramos", "eran", "be"], ["ir", "iba", "ibas", "iba", "íbamos", "iban", "go"], ["ver", "veía", "veías", "veía", "veíamos", "veían", "see"],
    ["tener", "tenía", "tenías", "tenía", "teníamos", "tenían", "have"], ["estar", "estaba", "estabas", "estaba", "estábamos", "estaban", "be"], ["jugar", "jugaba", "jugabas", "jugaba", "jugábamos", "jugaban", "play"],
    ["hacer", "hacía", "hacías", "hacía", "hacíamos", "hacían", "do"], ["querer", "quería", "querías", "quería", "queríamos", "querían", "want"], ["poder", "podía", "podías", "podía", "podíamos", "podían", "can"]]
};
var ES_FUTURE = {
  name: "Future and conditional", cols: ["infinitive", "future (yo)", "future (él)", "conditional (yo)", "meaning"], ask: [1, 2, 3], given: 0, gloss: 4, target: 9,
  q: "{w} ({g}): give the <b>{form}</b>.",
  rule: { 1: "Future: infinitive + -é -ás -á -emos -éis -án. Irregular stems: tendr-, har-, dir-, podr-, pondr-, saldr-, vendr-, querr-, sabr-, habr-.", 2: "", 3: "Conditional: the same stems + -ía -ías -ía -íamos -íais -ían. Used for 'would' and for polite requests: ¿Podría…?" },
  rows: [["hablar", "hablaré", "hablará", "hablaría", "speak"], ["comer", "comeré", "comerá", "comería", "eat"], ["vivir", "viviré", "vivirá", "viviría", "live"], ["tener", "tendré", "tendrá", "tendría", "have"],
    ["hacer", "haré", "hará", "haría", "do"], ["decir", "diré", "dirá", "diría", "say"], ["poder", "podré", "podrá", "podría", "can"], ["poner", "pondré", "pondrá", "pondría", "put"],
    ["salir", "saldré", "saldrá", "saldría", "go out"], ["venir", "vendré", "vendrá", "vendría", "come"], ["querer", "querré", "querrá", "querría", "want"], ["saber", "sabré", "sabrá", "sabría", "know"],
    ["ser", "seré", "será", "sería", "be"], ["ir", "iré", "irá", "iría", "go"], ["haber", "habré", "habrá", "habría", "have (aux.)"], ["jugar", "jugaré", "jugará", "jugaría", "play"]]
};
var ES_SUBJ = {
  name: "Present subjunctive", cols: ["infinitive", "yo", "tú", "él / ella", "nosotros", "ellos", "meaning"], ask: [1, 2, 3, 4, 5], given: 0, gloss: 6, target: 10,
  q: "{w} ({g}): give the present subjunctive for <b>{form}</b>.",
  rule: { 1: "Take the yo form of the present, drop the -o, add the opposite endings: -ar → -e -es -e -emos -éis -en; -er/-ir → -a -as -a -amos -áis -an. So tengo → tenga, conozco → conozca, digo → diga.", 2: "", 3: "Six irregulars: sea, esté, vaya, haya, sepa, dé.", 4: "", 5: "" },
  rows: [["hablar", "hable", "hables", "hable", "hablemos", "hablen", "speak"], ["comer", "coma", "comas", "coma", "comamos", "coman", "eat"], ["vivir", "viva", "vivas", "viva", "vivamos", "vivan", "live"],
    ["tener", "tenga", "tengas", "tenga", "tengamos", "tengan", "have"], ["hacer", "haga", "hagas", "haga", "hagamos", "hagan", "do"], ["ser", "sea", "seas", "sea", "seamos", "sean", "be"],
    ["estar", "esté", "estés", "esté", "estemos", "estén", "be"], ["ir", "vaya", "vayas", "vaya", "vayamos", "vayan", "go"], ["saber", "sepa", "sepas", "sepa", "sepamos", "sepan", "know"],
    ["poder", "pueda", "puedas", "pueda", "podamos", "puedan", "can"], ["querer", "quiera", "quieras", "quiera", "queramos", "quieran", "want"], ["decir", "diga", "digas", "diga", "digamos", "digan", "say"],
    ["venir", "venga", "vengas", "venga", "vengamos", "vengan", "come"], ["dar", "dé", "des", "dé", "demos", "den", "give"], ["haber", "haya", "hayas", "haya", "hayamos", "hayan", "have (aux.)"]]
};
var ES_SERESTAR = {
  name: "Ser or estar", cols: ["sentence", "verb", "meaning"], ask: [1], given: 0, gloss: 2, choice: true, target: 6,
  q: "{w} ({g}): ser or estar?",
  rule: { 1: "Ser: identity, origin, profession, time, what something is like by nature. Estar: location, temporary state, result of a change, the -ando/-iendo progressive. Some adjectives change meaning: ser aburrido (boring) / estar aburrido (bored); ser listo (clever) / estar listo (ready)." },
  rows: [["Yo ___ canadiense.", "ser (soy)", "I am Canadian."], ["Yo ___ cansado.", "estar (estoy)", "I am tired."], ["El libro ___ en la mesa.", "estar (está)", "The book is on the table."], ["Mi madre ___ médica.", "ser (es)", "My mother is a doctor."],
    ["___ las tres.", "ser (son)", "It is three o'clock."], ["Nosotros ___ en Madrid.", "estar (estamos)", "We are in Madrid."], ["La sopa ___ caliente.", "estar (está)", "The soup is hot (right now)."], ["El hielo ___ frío.", "ser (es)", "Ice is cold (by nature)."],
    ["¿Dónde ___ el baño?", "estar (está)", "Where is the bathroom?"], ["Hoy ___ lunes.", "ser (es)", "Today is Monday."], ["Ella ___ muy lista.", "ser (es)", "She is very clever."], ["¿___ listo?", "estar (estás)", "Are you ready?"],
    ["Ellos ___ jugando.", "estar (están)", "They are playing."], ["La película ___ aburrida.", "ser (es)", "The film is boring."], ["___ enfermo hoy.", "estar (estoy)", "I'm ill today."], ["Esto ___ importante.", "ser (es)", "This is important."]]
};
var ES_ADJ = {
  name: "Adjective agreement", cols: ["m. sg.", "f. sg.", "m. pl.", "f. pl.", "meaning"], ask: [1, 2, 3], given: 0, gloss: 4, target: 7,
  q: "{w} ({g}): give the <b>{form}</b> form.",
  rule: { 1: "-o → -a for the feminine; adjectives ending in -e or a consonant have one singular form for both genders (grande, fácil), except nationality adjectives (español, española) and -or (trabajador, trabajadora).", 2: "Plural: vowel + -s, consonant + -es.", 3: "Adjectives follow the noun: un coche rojo. A few shorten before a masculine singular noun: bueno → buen, malo → mal, grande → gran (before any singular noun, meaning 'great')." },
  rows: [["alto", "alta", "altos", "altas", "tall"], ["bueno", "buena", "buenos", "buenas", "good"], ["grande", "grande", "grandes", "grandes", "big"], ["fácil", "fácil", "fáciles", "fáciles", "easy"],
    ["español", "española", "españoles", "españolas", "Spanish"], ["trabajador", "trabajadora", "trabajadores", "trabajadoras", "hard-working"], ["feliz", "feliz", "felices", "felices", "happy"], ["joven", "joven", "jóvenes", "jóvenes", "young"],
    ["rojo", "roja", "rojos", "rojas", "red"], ["azul", "azul", "azules", "azules", "blue"], ["pequeño", "pequeña", "pequeños", "pequeñas", "small"], ["nuevo", "nueva", "nuevos", "nuevas", "new"],
    ["inteligente", "inteligente", "inteligentes", "inteligentes", "intelligent"], ["difícil", "difícil", "difíciles", "difíciles", "difficult"], ["cansado", "cansada", "cansados", "cansadas", "tired"], ["frío", "fría", "fríos", "frías", "cold"]]
};
var ES_PRON = {
  name: "Object pronouns", cols: ["subject", "direct object", "indirect object", "after a preposition", "possessive", "meaning"], ask: [1, 2, 3, 4], given: 0, gloss: 5, target: 6,
  q: "{w} ({g}): give the <b>{form}</b> form.",
  rule: { 1: "Direct: me, te, lo/la, nos, os, los/las. They go before a conjugated verb (lo veo) or attach to an infinitive or gerund (quiero verlo).", 2: "Indirect: me, te, le, nos, os, les. With a direct object pronoun, le/les becomes se: se lo doy.", 3: "After prepositions: mí, ti, él/ella/usted, nosotros, vosotros, ellos; conmigo, contigo.", 4: "Possessives: mi(s), tu(s), su(s), nuestro/a(s), vuestro/a(s), su(s); they agree with the thing owned." },
  rows: [["yo", "me", "me", "mí", "mi / mis", "I"], ["tú", "te", "te", "ti", "tu / tus", "you"], ["él", "lo", "le", "él", "su / sus", "he"], ["ella", "la", "le", "ella", "su / sus", "she"],
    ["usted", "lo / la", "le", "usted", "su / sus", "you (formal)"], ["nosotros", "nos", "nos", "nosotros", "nuestro / nuestra / nuestros / nuestras", "we"], ["ellos", "los", "les", "ellos", "su / sus", "they"], ["ellas", "las", "les", "ellas", "su / sus", "they (f.)"]]
};
/* gustar-type sentences: [English, Spanish, gloss note] */
var ES_GUSTAR = [
  ["I like coffee.", "Me gusta el café.", "singular thing → gusta"], ["I like apples.", "Me gustan las manzanas.", "plural thing → gustan"], ["Do you like hockey?", "¿Te gusta el hockey?", ""], ["She likes to read.", "Le gusta leer.", "an infinitive → gusta"],
  ["We like the city.", "Nos gusta la ciudad.", ""], ["They like the games.", "Les gustan los partidos.", ""], ["I don't like winter.", "No me gusta el invierno.", ""], ["My knee hurts.", "Me duele la rodilla.", "doler works the same way"],
  ["My feet hurt.", "Me duelen los pies.", ""], ["He is interested in history.", "Le interesa la historia.", "interesar too"], ["I love tacos.", "Me encantan los tacos.", "encantar = love"], ["It seems good to me.", "Me parece bien.", "parecer"]
];
/* tense choice: preterite vs imperfect: [sentence with blank, answer, gloss] */
var ES_PASTCHOICE = {
  name: "Preterite or imperfect", cols: ["sentence", "form", "meaning"], ask: [1], given: 0, gloss: 2, choice: true, target: 8,
  q: "{w} ({g}): which form?",
  rule: { 1: "Preterite: a completed action, a specific time, a sequence of events (ayer, una vez, de repente). Imperfect: background, habit, description, age, time, ongoing action interrupted (siempre, mientras, todos los días, de niño)." },
  rows: [["Ayer ___ (jugar, nosotros) un partido.", "jugamos (preterite)", "Yesterday we played a game."], ["De niño ___ (jugar, yo) al hockey todos los días.", "jugaba (imperfect)", "As a child I played hockey every day."], ["___ (ser) las tres cuando llegó.", "Eran (imperfect)", "It was three o'clock when he arrived."],
    ["De repente ___ (empezar) a nevar.", "empezó (preterite)", "Suddenly it started to snow."], ["Mientras ___ (comer, yo), sonó el teléfono.", "comía (imperfect)", "While I was eating, the phone rang."], ["El año pasado ___ (ir, ellos) a México.", "fueron (preterite)", "Last year they went to Mexico."],
    ["Mi abuela siempre ___ (cocinar) los domingos.", "cocinaba (imperfect)", "My grandmother always cooked on Sundays."], ["___ (tener, yo) diez años cuando nos mudamos.", "Tenía (imperfect)", "I was ten when we moved."], ["Anoche ___ (ver, nosotros) una película.", "vimos (preterite)", "Last night we watched a film."],
    ["Hacía frío y ___ (llover).", "llovía (imperfect)", "It was cold and raining."], ["El partido ___ (terminar) a las diez.", "terminó (preterite)", "The game ended at ten."], ["Cuando era joven ___ (vivir, él) en Madrid.", "vivía (imperfect)", "When he was young he lived in Madrid."]]
};
/* pronunciation: [word, rule, meaning] */
var ES_SOUND_RULES = ["hard c / g (k, g)", "soft c (s / th)", "soft g (like Spanish j)", "silent h", "ll / y (y sound)", "ñ (ny)", "rr (rolled)", "j (throaty h)", "qu / gu (silent u)"];
var ES_SOUNDS = [
  ["casa", "hard c / g (k, g)", "house"], ["cine", "soft c (s / th)", "cinema"], ["gente", "soft g (like Spanish j)", "people"], ["gato", "hard c / g (k, g)", "cat"], ["hola", "silent h", "hello"], ["llave", "ll / y (y sound)", "key"],
  ["año", "ñ (ny)", "year"], ["perro", "rr (rolled)", "dog"], ["jugar", "j (throaty h)", "to play"], ["queso", "qu / gu (silent u)", "cheese"], ["guitarra", "qu / gu (silent u)", "guitar"], ["ciudad", "soft c (s / th)", "city"],
  ["gimnasio", "soft g (like Spanish j)", "gym"], ["hielo", "silent h", "ice"], ["calle", "ll / y (y sound)", "street"], ["niño", "ñ (ny)", "child"], ["carro", "rr (rolled)", "car"], ["hijo", "j (throaty h)", "son"],
  ["cuánto", "hard c / g (k, g)", "how much"], ["gracias", "soft c (s / th)", "thanks"], ["general", "soft g (like Spanish j)", "general"], ["hora", "silent h", "hour"], ["ella", "ll / y (y sound)", "she"], ["mañana", "ñ (ny)", "tomorrow"]
];
/* stress: [word, stressed syllable number (1-based), syllables, rule] */
var ES_STRESS = [
  ["hablar", 2, "ha-BLAR", "ends in a consonant other than n/s: last syllable"], ["casa", 1, "CA-sa", "ends in a vowel: second-to-last"], ["cantan", 1, "CAN-tan", "ends in n or s: second-to-last"], ["canción", 2, "can-CIÓN", "the accent mark overrides the rule"],
  ["médico", 1, "MÉ-di-co", "accent mark: third-to-last"], ["ciudad", 2, "ciu-DAD", "ends in a consonant: last"], ["lápiz", 1, "LÁ-piz", "accent mark"], ["jóvenes", 1, "JÓ-ve-nes", "accent mark"],
  ["universidad", 5, "u-ni-ver-si-DAD", "ends in a consonant: last"], ["teléfono", 2, "te-LÉ-fo-no", "accent mark"], ["mañana", 2, "ma-ÑA-na", "ends in a vowel: second-to-last"], ["examen", 2, "e-XA-men", "ends in n: second-to-last"]
];
/* minimal pairs by accent: [a, b, meanings] */
var ES_PAIRS = [["hablo", "habló", "I speak / he spoke"], ["papa", "papá", "potato / dad"], ["esta", "está", "this / is"], ["si", "sí", "if / yes"], ["el", "él", "the / he"], ["tu", "tú", "your / you"], ["como", "comió", "I eat / he ate"], ["pero", "perro", "but / dog"], ["caro", "carro", "expensive / car"], ["pera", "perra", "pear / female dog"]];

/* ---- dialogues ---- */
var ES_DIALOGUES = [
  { id: "es_d1", title: "Hello, who are you?", setting: "A new teammate at the rink. Introduce yourself.", level: "A1",
    turns: [
      { bot: "¡Hola! Me llamo Lucía. ¿Cómo te llamas?", botg: "Hi! My name is Lucía. What's your name?", expect: ["me llamo", "mi nombre", "^soy "], model: "¡Hola! Me llamo Erik.", modelg: "Hi! My name is Erik.", hint: "Me llamo ... (My name is ...)" },
      { bot: "¡Mucho gusto! ¿De dónde eres?", botg: "Nice to meet you! Where are you from?", expect: ["soy de", "de canad", "vengo de"], model: "Soy de Canadá.", modelg: "I'm from Canada.", hint: "Soy de ... " },
      { bot: "¡Qué bien! ¿Vives aquí ahora?", botg: "Great! Do you live here now?", expect: ["^s[ií]", "^no", "vivo"], model: "Sí, vivo aquí ahora.", modelg: "Yes, I live here now.", hint: "Sí / No, vivo ..." },
      { bot: "¿Juegas al hockey?", botg: "Do you play hockey?", expect: ["s[ií]", "juego"], model: "Sí, juego al hockey.", modelg: "Yes, I play hockey.", hint: "Sí, juego al ..." },
      { bot: "¡Perfecto! Nos vemos en el entrenamiento. ¡Adiós!", botg: "Perfect! See you at practice. Bye!", expect: ["adi[oó]s", "hasta", "nos vemos", "chao"], model: "¡Adiós, hasta luego!", modelg: "Bye, see you later!", hint: "Adiós / Hasta luego / Nos vemos" }
    ] },
  { id: "es_d2", title: "At the café", setting: "Order a coffee and something to eat, then pay.", level: "A1",
    turns: [
      { bot: "¡Hola! ¿Qué desea?", botg: "Hi! What would you like?", expect: ["caf[eé]", "t[eé]", "quiero", "por favor", "me pone"], model: "Un café con leche, por favor.", modelg: "A coffee with milk, please.", hint: "Un café, por favor / Quiero ..." },
      { bot: "¿Quiere algo de comer también?", botg: "Would you like something to eat too?", expect: ["s[ií]", "no", "tostada", "croissant", "bocadillo", "gracias"], model: "Sí, una tostada, por favor.", modelg: "Yes, a piece of toast, please.", hint: "Sí, un/una ... por favor / No, gracias" },
      { bot: "Son cuatro euros con cincuenta. ¿Con tarjeta o en efectivo?", botg: "That's four fifty. Card or cash?", expect: ["tarjeta", "efectivo"], model: "Con tarjeta, por favor.", modelg: "By card, please.", hint: "Con tarjeta / En efectivo" },
      { bot: "Aquí tiene. ¿Quiere el recibo?", botg: "Here you go. Do you want the receipt?", expect: ["s[ií]", "no", "gracias"], model: "No, gracias.", modelg: "No, thanks.", hint: "No, gracias / Sí, por favor" }
    ] },
  { id: "es_d3", title: "Asking the way", setting: "You are lost in Barcelona and need the train station.", level: "A2",
    turns: [
      { bot: "Hola, ¿puedo ayudarle?", botg: "Hello, can I help you?", expect: ["d[oó]nde est[aá]", "estaci[oó]n", "busco", "c[oó]mo (llego|voy)"], model: "Sí, ¿dónde está la estación de tren?", modelg: "Yes, where is the train station?", hint: "¿Dónde está ...? / ¿Cómo llego a ...?" },
      { bot: "Siga todo recto y gire a la izquierda en el banco. ¿Entendido?", botg: "Go straight ahead and turn left at the bank. Got it? (say it back)", expect: ["recto", "izquierda", "banco"], model: "Todo recto y a la izquierda en el banco.", modelg: "Straight ahead and left at the bank.", hint: "Repeat: todo recto ... izquierda ..." },
      { bot: "Exacto. Son unos diez minutos. ¿Va a Madrid?", botg: "Exactly. About ten minutes. Are you going to Madrid?", expect: ["s[ií]", "no", "voy a", "madrid", "sevilla"], model: "Sí, voy a Madrid.", modelg: "Yes, I'm going to Madrid.", hint: "Sí, voy a ..." },
      { bot: "¡Buen viaje! Adiós.", botg: "Have a good trip! Bye.", expect: ["gracias", "adi[oó]s"], model: "¡Muchas gracias! Adiós.", modelg: "Thanks a lot! Bye.", hint: "Gracias ... adiós" }
    ] },
  { id: "es_d4", title: "At the doctor", setting: "You hurt your knee at hockey. Say what happened in the past tense.", level: "A2",
    turns: [
      { bot: "Buenos días, ¿qué le pasa?", botg: "Good morning, what's wrong?", expect: ["me duele", "rodilla", "me lesion", "me ca[ií]"], model: "Me duele la rodilla.", modelg: "My knee hurts.", hint: "Me duele ... / Me lesioné ..." },
      { bot: "Entiendo. ¿Cuándo pasó?", botg: "I see. When did it happen?", expect: ["ayer", "anoche", "hace", "en el entrenamiento", "el (lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bado|domingo)"], model: "Ayer, en el entrenamiento de hockey.", modelg: "Yesterday, at hockey practice.", hint: "Ayer / Hace ... / En el entrenamiento" },
      { bot: "¿Puede caminar?", botg: "Can you walk?", expect: ["s[ií]", "no", "un poco", "puedo"], model: "Sí, pero me cuesta.", modelg: "Yes, but it's hard.", hint: "Sí / No / Un poco" },
      { bot: "Tome este medicamento dos veces al día y descanse una semana. ¿De acuerdo?", botg: "Take this medicine twice a day and rest a week. OK?", expect: ["de acuerdo", "vale", "gracias", "s[ií]"], model: "De acuerdo, muchas gracias.", modelg: "OK, thanks a lot.", hint: "De acuerdo / Vale, gracias" }
    ] },
  { id: "es_d5", title: "Talking about the game", setting: "A friend asks about last night's game. Preterite and opinions.", level: "B1",
    turns: [
      { bot: "¿Qué tal el partido de ayer?", botg: "How was the game yesterday?", expect: ["ganamos", "perdimos", "fue", "empatamos"], model: "¡Ganamos tres a dos!", modelg: "We won 3–2!", hint: "Ganamos / Perdimos / Fue ..." },
      { bot: "¡Enhorabuena! ¿Marcaste algún gol?", botg: "Congratulations! Did you score a goal?", expect: ["s[ií]", "no", "gol", "marqu[eé]", "asistencia"], model: "Marqué un gol y di una asistencia.", modelg: "I scored a goal and gave an assist.", hint: "Marqué ... / No, pero ..." },
      { bot: "¿Qué fue lo más difícil?", botg: "What was the hardest part?", expect: ["lo m[aá]s dif[ií]cil", "fue", "tercer", "cansados", "r[aá]pidos"], model: "Lo más difícil fue el tercer período; estábamos cansados.", modelg: "The hardest was the third period; we were tired.", hint: "Lo más difícil fue ..." },
      { bot: "¿Cuándo es el próximo partido?", botg: "When's the next game?", expect: ["el (lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bado|domingo)", "pr[oó]xim", "ma[nñ]ana", "semana"], model: "El sábado, fuera de casa.", modelg: "On Saturday, away.", hint: "El ... / La semana que viene" },
      { bot: "Iré a verlo. ¡Suerte!", botg: "I'll come and watch. Good luck!", expect: ["gracias", "genial", "qu[eé] bien"], model: "¡Gracias, qué bien!", modelg: "Thanks, great!", hint: "Gracias ..." }
    ] },
  { id: "es_d6", title: "A polite disagreement", setting: "A classmate wants to study late; you prefer mornings. Use the subjunctive and connectors.", level: "B2",
    turns: [
      { bot: "¿Estudiamos esta noche a las diez? Yo rindo mejor tarde.", botg: "Shall we study tonight at ten? I work better late.", expect: ["prefiero", "no estoy de acuerdo", "porque", "por la ma[nñ]ana", "temprano", "mejor"], model: "Prefiero por la mañana porque tengo hockey por las noches.", modelg: "I prefer the morning because I have hockey in the evenings.", hint: "Prefiero ... porque ..." },
      { bot: "Pero por la mañana no me funciona el cerebro. ¿No podemos llegar a un acuerdo?", botg: "But in the morning my brain doesn't work. Can't we reach a compromise?", expect: ["qu[eé] te parece", "podr[ií]amos", "en vez de", "a las", "tarde"], model: "¿Qué te parece a las cuatro de la tarde, en vez de la noche?", modelg: "How about four in the afternoon, instead of the evening?", hint: "¿Qué te parece ... en vez de ...?" },
      { bot: "Vale, me parece bien. ¿Por qué capítulo empezamos?", botg: "OK, that seems fine. Which chapter do we start with?", expect: ["cap[ií]tulo", "empecemos", "creo que", "lo m[aá]s dif[ií]cil", "primero"], model: "Creo que es mejor que empecemos por el capítulo más difícil.", modelg: "I think it's better that we start with the hardest chapter.", hint: "Creo que es mejor que empecemos por ..." },
      { bot: "De acuerdo. Yo llevo el café. ¡Hasta luego!", botg: "Agreed. I'll bring the coffee. See you!", expect: ["hasta", "gracias", "perfecto", "genial"], model: "¡Perfecto, hasta luego!", modelg: "Perfect, see you!", hint: "Perfecto / Hasta luego" }
    ] }
];

/* ---- graded readers ---- */
var ES_READINGS = [
  { id: "es_r1", title: "Mi familia", level: "A1", text: [
      "Me llamo Sara y tengo veinte años. Vivo en Valencia con mi familia. Somos cinco personas: mi madre, mi padre, mi hermano, mi hermana y yo.",
      "Mi hermano se llama Jorge. Tiene veintitrés años y juega al hockey. Mi hermana se llama Lina. Tiene quince años y va al instituto. Mi madre trabaja en un hospital y mi padre es profesor.",
      "También tenemos un perro. Se llama Max y es viejo pero alegre. Los domingos comemos todos juntos."
    ], gloss: [["instituto", "secondary school"], ["juntos", "together"], ["alegre", "cheerful"]],
    qs: [{ q: "¿Cuántas personas hay en la familia?", options: ["Tres", "Cuatro", "Cinco", "Seis"], answer: "Cinco" }, { q: "¿Qué hace el padre?", options: ["Es profesor", "Juega al hockey", "Trabaja en un hospital", "Va al instituto"], answer: "Es profesor" }, { q: "¿Cómo se llama el perro?", options: ["Jorge", "Max", "Lina", "Sara"], answer: "Max" }] },
  { id: "es_r2", title: "Un día en Madrid", level: "A2", text: [
      "Ayer fui a Madrid en tren. El viaje duró unos cuarenta minutos. Llegué a las diez y fui directamente al centro, a la Puerta del Sol.",
      "En el centro hay muchas calles pequeñas y edificios antiguos. Tomé un café en un bar y comí unos churros con chocolate. Después caminé hasta el Palacio Real. Había mucha gente.",
      "Por la tarde visité el Museo del Prado y vi Las Meninas de Velázquez. Fue impresionante. Por la noche volví a casa, cansado pero contento."
    ], gloss: [["duró", "lasted"], ["edificios", "buildings"], ["había", "there was/were"], ["impresionante", "impressive"], ["volví", "I returned"]],
    qs: [{ q: "¿Cómo fue a Madrid?", options: ["En coche", "En tren", "En autobús", "En avión"], answer: "En tren" }, { q: "¿Qué hizo por la tarde?", options: ["Tomó un café", "Fue al Palacio Real", "Visitó el Prado", "Volvió a casa"], answer: "Visitó el Prado" }, { q: "¿Qué comió?", options: ["Paella", "Churros con chocolate", "Tortilla", "Tapas"], answer: "Churros con chocolate" }] },
  { id: "es_r3", title: "La sobremesa", level: "A2", text: [
      "En España y en muchos países de Latinoamérica, la comida no termina cuando termina la comida. Después del último plato, la gente se queda en la mesa hablando, a veces durante una hora o más. Eso se llama la sobremesa.",
      "Durante la sobremesa se toma café, se cuentan historias y se discute de todo: de política, de fútbol, de la familia. Nadie tiene prisa. Para muchos españoles, la sobremesa es la parte más importante de la comida.",
      "Los extranjeros a veces no lo entienden y se levantan de la mesa demasiado pronto. Si quieres parecer español, quédate sentado, pide otro café y sigue hablando."
    ], gloss: [["se queda", "stays"], ["prisa", "hurry"], ["extranjeros", "foreigners"], ["demasiado pronto", "too soon"], ["quédate sentado", "stay seated"]],
    qs: [{ q: "¿Qué es la sobremesa?", options: ["El postre", "El tiempo de conversación después de comer", "Un tipo de café", "La hora de la siesta"], answer: "El tiempo de conversación después de comer" }, { q: "¿Cuánto puede durar?", options: ["Cinco minutos", "Una hora o más", "Toda la noche", "No se sabe"], answer: "Una hora o más" }, { q: "¿Qué error cometen algunos extranjeros?", options: ["Hablan de política", "Piden café", "Se levantan demasiado pronto", "Comen demasiado"], answer: "Se levantan demasiado pronto" }] },
  { id: "es_r4", title: "El español en el mundo", level: "B1", text: [
      "El español es la lengua materna de casi quinientos millones de personas y la segunda lengua más hablada del mundo por número de hablantes nativos, después del chino mandarín. Es lengua oficial en veintiún países, desde México hasta Argentina, pasando por España y Guinea Ecuatorial.",
      "Aunque se entiende en todas partes, el español cambia de un país a otro. En España se dice vosotros; en Argentina, vos; en casi toda Latinoamérica, ustedes. En México un autobús es un camión, en Argentina un colectivo y en Cuba una guagua. La pronunciación también varía: en gran parte de España la c de cine suena como la th inglesa; en América, como una s.",
      "A pesar de estas diferencias, un mexicano, un español y un argentino se entienden sin problemas, igual que un canadiense entiende a un australiano. La Real Academia Española y las academias de cada país trabajan juntas para mantener la unidad de la lengua."
    ], gloss: [["lengua materna", "mother tongue"], ["hablantes", "speakers"], ["pasando por", "via"], ["varía", "varies"], ["a pesar de", "despite"], ["mantener", "to maintain"]],
    qs: [{ q: "¿Cuántos países tienen el español como lengua oficial?", options: ["Once", "Veintiuno", "Treinta", "Cinco"], answer: "Veintiuno" }, { q: "¿Cómo se dice autobús en Argentina?", options: ["Camión", "Guagua", "Colectivo", "Micro"], answer: "Colectivo" }, { q: "¿Se entienden un mexicano y un español?", options: ["No, son lenguas distintas", "Sí, sin problemas", "Solo por escrito", "Solo con traductor"], answer: "Sí, sin problemas" }] },
  { id: "es_r5", title: "El hockey sobre hielo en España", level: "B1", text: [
      "El hockey sobre hielo no es un deporte popular en España: hay apenas unas pocas pistas y menos de dos mil jugadores federados. Sin embargo, existe una liga nacional desde 1972 y la selección española compite en los campeonatos mundiales de la división inferior.",
      "Los equipos más conocidos son el CH Jaca, en los Pirineos, el Txuri Urdin de San Sebastián y el Majadahonda de Madrid. Muchos jugadores son extranjeros que vienen de Canadá, Finlandia o Suecia a jugar una temporada, y aportan experiencia a los jóvenes españoles.",
      "El mayor problema es la falta de hielo: las pistas son caras de mantener en un país con veranos tan calurosos. Aun así, cada año más niños empiezan a patinar, y las escuelas de hockey de Barcelona y Madrid crecen poco a poco."
    ], gloss: [["apenas", "barely"], ["federados", "registered"], ["selección", "national team"], ["aportan", "contribute"], ["falta", "lack"], ["calurosos", "hot"], ["aun así", "even so"], ["crecen", "grow"]],
    qs: [{ q: "¿Desde cuándo existe la liga española?", options: ["1972", "1992", "2002", "1952"], answer: "1972" }, { q: "¿De dónde vienen muchos jugadores extranjeros?", options: ["De Francia e Italia", "De Canadá, Finlandia o Suecia", "De Rusia", "De Argentina"], answer: "De Canadá, Finlandia o Suecia" }, { q: "¿Cuál es el mayor problema?", options: ["La falta de jugadores", "La falta de hielo", "El precio de las entradas", "La televisión"], answer: "La falta de hielo" }] },
  { id: "es_r6", title: "La siesta: mito y realidad", level: "B2", text: [
      "Pocas costumbres españolas son tan conocidas, ni tan mal entendidas, como la siesta. La imagen del país entero durmiendo después de comer es, hoy, casi un mito: según las encuestas, menos de un veinte por ciento de los españoles duerme la siesta con regularidad, y la mayoría de los trabajadores urbanos no tiene tiempo para hacerlo.",
      "Lo que sí persiste es el horario que la hizo posible. La jornada partida, con una pausa larga a mediodía, sigue siendo habitual en muchos comercios y oficinas, de modo que la gente come tarde, cena más tarde aún y se acuesta después de medianoche. Varios gobiernos han propuesto adaptar los horarios a los del resto de Europa, con el argumento de que el modelo actual perjudica la conciliación familiar y la productividad.",
      "Curiosamente, mientras España debate si abandonar la siesta, la ciencia del sueño la recomienda: una siesta de veinte minutos mejora la atención y la memoria, siempre que no sea demasiado larga ni demasiado tarde. Quizá la costumbre tenga más futuro fuera de España que dentro."
    ], gloss: [["costumbres", "customs"], ["encuestas", "surveys"], ["persiste", "persists"], ["jornada partida", "split working day"], ["de modo que", "so that"], ["se acuesta", "goes to bed"], ["perjudica", "harms"], ["conciliación", "work-life balance"], ["siempre que", "provided that"]],
    qs: [{ q: "¿Qué porcentaje de españoles duerme la siesta con regularidad, según el texto?", options: ["Más del cincuenta", "Menos del veinte", "Casi todos", "Nadie"], answer: "Menos del veinte" }, { q: "¿Qué es la jornada partida?", options: ["Un día festivo", "Un horario con una pausa larga a mediodía", "Un turno de noche", "Media jornada"], answer: "Un horario con una pausa larga a mediodía" }, { q: "¿Qué dice la ciencia del sueño sobre la siesta?", options: ["Que es perjudicial", "Que una siesta corta mejora la atención", "Que debe durar dos horas", "Que solo sirve a los niños"], answer: "Que una siesta corta mejora la atención" }] }
];

var ES_DICTATION = [
  ["Me llamo Ana y vivo en Sevilla.", "A1"], ["¿Cuánto cuesta?", "A1"], ["Nos vemos mañana a las diez.", "A1"], ["No entiendo. ¿Puede repetir, por favor?", "A1"],
  ["Mi hermano juega al hockey los sábados.", "A2"], ["Ayer llovió todo el día.", "A2"], ["¿Me trae la cuenta, por favor?", "A2"], ["El tren a Barcelona sale del andén cuatro.", "A2"],
  ["Hace dos años que vivo en España.", "B1"], ["Si nieva mañana, cancelarán el partido.", "B1"], ["Dijo que no tenía tiempo.", "B1"], ["Tenemos que decidirlo antes del viernes.", "B1"],
  ["Aunque el equipo jugó bien, perdió por un gol.", "B2"], ["Lo más importante es parar y hablar con la gente.", "B2"], ["El gobierno propone bajar los impuestos el año que viene.", "B2"], ["Nunca pensé que el invierno fuera tan largo.", "B2"]
];
var ES_WRITING = [
  ["I am tired.", ["Estoy cansado.", "Estoy cansada."], "A1"], ["Where do you live?", ["¿Dónde vives?", "Dónde vives"], "A1"], ["I don't understand.", ["No entiendo.", "No comprendo."], "A1"], ["We have a dog.", ["Tenemos un perro."], "A1"],
  ["Today I'm playing hockey.", ["Hoy juego al hockey.", "Hoy juego hockey.", "Juego al hockey hoy."], "A2"], ["The book is on the table.", ["El libro está en la mesa.", "El libro está sobre la mesa."], "A2"], ["Can you help me?", ["¿Puedes ayudarme?", "¿Me puedes ayudar?", "Puedes ayudarme"], "A2"], ["She bought a new car.", ["Compró un coche nuevo.", "Ella compró un coche nuevo.", "Compró un carro nuevo."], "A2"],
  ["I know that he isn't coming.", ["Sé que no viene.", "Sé que él no viene.", "Sé que no va a venir."], "B1"], ["We have lived here for three years.", ["Vivimos aquí desde hace tres años.", "Hace tres años que vivimos aquí.", "Llevamos tres años viviendo aquí."], "B1"], ["If it rains, we'll stay at home.", ["Si llueve, nos quedamos en casa.", "Si llueve nos quedamos en casa.", "Si llueve, nos quedaremos en casa."], "B1"], ["Yesterday I was at the rink all day.", ["Ayer estuve en la pista todo el día.", "Ayer estuve en la pista de hielo todo el día."], "B1"],
  ["Spanish is spoken in Spain.", ["En España se habla español.", "Se habla español en España."], "B2"], ["Although we lost, I was proud of the team.", ["Aunque perdimos, estaba orgulloso del equipo.", "Aunque perdimos, estuve orgulloso del equipo.", "Aunque perdimos, estaba orgullosa del equipo."], "B2"], ["I would rather train in the morning.", ["Preferiría entrenar por la mañana.", "Prefiero entrenar por la mañana."], "B2"], ["The game was cancelled because of the weather.", ["El partido se canceló por el tiempo.", "Cancelaron el partido por el tiempo.", "El partido fue cancelado por el mal tiempo."], "B2"]
];

if (typeof module !== "undefined") module.exports = {
  ES_VOCAB: ES_VOCAB, ES_GENDER: ES_GENDER, ES_PLURAL: ES_PLURAL, ES_PRESENT: ES_PRESENT, ES_PRETERITE: ES_PRETERITE, ES_IMPERFECT: ES_IMPERFECT, ES_FUTURE: ES_FUTURE, ES_SUBJ: ES_SUBJ, ES_SERESTAR: ES_SERESTAR, ES_ADJ: ES_ADJ, ES_PRON: ES_PRON,
  ES_GUSTAR: ES_GUSTAR, ES_PASTCHOICE: ES_PASTCHOICE, ES_SOUND_RULES: ES_SOUND_RULES, ES_SOUNDS: ES_SOUNDS, ES_STRESS: ES_STRESS, ES_PAIRS: ES_PAIRS, ES_DIALOGUES: ES_DIALOGUES, ES_READINGS: ES_READINGS, ES_DICTATION: ES_DICTATION, ES_WRITING: ES_WRITING
};
