/* ============================================================
   HEBREW: the vocabulary (modern)
   Row: [word with vowel points, transliteration, gloss, part of speech, forms, example, example gloss]
   Typing without the points is always accepted. Pronunciation is
   standard Israeli; stress is on the last syllable unless marked.
   ============================================================ */

var HE_VOCAB = {
  he_v1: [
    ["שָׁלוֹם", "shalom", "hello / goodbye / peace", "phrase", "", "שָׁלוֹם, מָה שְׁלוֹמְךָ?", "Hello, how are you?"],
    ["אֲנִי", "ani", "I", "pron", "", "אֲנִי סְטוּדֶנְט.", "I am a student."],
    ["אַתָּה", "ata", "you (m.)", "pron", "אַתְּ (at) = you (f.)", "אַתָּה מִקָּנָדָה?", "Are you from Canada?"],
    ["אַתְּ", "at", "you (f.)", "pron", "", "אַתְּ מְדַבֶּרֶת עִבְרִית?", "Do you (f.) speak Hebrew?"],
    ["הוּא", "hu", "he", "pron", "", "הוּא מוֹרֶה.", "He is a teacher."],
    ["הִיא", "hi", "she", "pron", "", "הִיא רוֹפְאָה.", "She is a doctor."],
    ["אֲנַחְנוּ", "anachnu", "we", "pron", "", "אֲנַחְנוּ לוֹמְדִים עִבְרִית.", "We are learning Hebrew."],
    ["אַתֶּם", "atem", "you (m. pl.)", "pron", "אַתֶּן (aten) = you (f. pl.)", "אַתֶּם מֵאֵיפֹה?", "Where are you (pl.) from?"],
    ["הֵם", "hem", "they (m.)", "pron", "הֵן (hen) = they (f.)", "הֵם מְשַׂחֲקִים הוֹקִי.", "They play hockey."],
    ["כֵּן", "ken", "yes", "adv", "", "כֵּן, בְּסֵדֶר.", "Yes, OK."],
    ["לֹא", "lo", "no / not", "adv", "", "לֹא, תּוֹדָה.", "No, thank you."],
    ["תּוֹדָה", "toda", "thank you", "phrase", "תּוֹדָה רַבָּה = thanks a lot", "תּוֹדָה רַבָּה!", "Thanks a lot!"],
    ["בְּבַקָּשָׁה", "bevakasha", "please / you're welcome", "phrase", "", "קָפֶה, בְּבַקָּשָׁה.", "Coffee, please."],
    ["סְלִיחָה", "slicha", "sorry / excuse me", "phrase", "", "סְלִיחָה, אֵיפֹה הַתַּחֲנָה?", "Excuse me, where is the station?"],
    ["מָה", "ma", "what", "pron", "", "מָה זֶה?", "What is this?"],
    ["מִי", "mi", "who", "pron", "", "מִי זֶה?", "Who is this?"],
    ["אֵיפֹה", "eifo", "where", "adv", "לְאָן = where to", "אֵיפֹה אַתָּה גָּר?", "Where do you live?"],
    ["אֵיךְ", "eich", "how", "adv", "", "אֵיךְ קוֹרְאִים לְךָ?", "What's your name? (how do they call you)"],
    ["לָמָּה", "lama", "why", "adv", "כִּי = because", "לָמָּה לֹא?", "Why not?"],
    ["מָתַי", "matai", "when", "adv", "", "מָתַי הַמִּשְׂחָק?", "When is the game?"],
    ["זֶה", "ze", "this / it (m.)", "pron", "זֹאת (zot) = this (f.)", "זֶה טוֹב.", "This is good."],
    ["טוֹב", "tov", "good", "adj", "טוֹבָה, טוֹבִים, טוֹבוֹת", "בֹּקֶר טוֹב!", "Good morning!"],
    ["בְּסֵדֶר", "beseder", "OK / fine", "phrase", "", "הַכֹּל בְּסֵדֶר.", "Everything is fine."],
    ["יֵשׁ", "yesh", "there is / have", "verb", "יֵשׁ לִי = I have", "יֵשׁ לִי שְׁאֵלָה.", "I have a question."],
    ["אֵין", "ein", "there is no / don't have", "verb", "אֵין לִי = I don't have", "אֵין לִי זְמַן.", "I don't have time."],
    ["גַּם", "gam", "also", "adv", "", "גַּם אֲנִי.", "Me too."],
    ["מְאוֹד", "me'od", "very", "adv", "", "טוֹב מְאוֹד.", "Very good."],
    ["קְצָת", "ktsat", "a little", "adv", "", "אֲנִי מְדַבֵּר קְצָת עִבְרִית.", "I speak a little Hebrew."],
    ["לְהִתְרָאוֹת", "lehitra'ot", "see you / goodbye", "phrase", "", "לְהִתְרָאוֹת מָחָר!", "See you tomorrow!"],
    ["נָעִים מְאוֹד", "na'im me'od", "nice to meet you", "phrase", "", "נָעִים מְאוֹד, אֲנִי דָּן.", "Nice to meet you, I'm Dan."]
  ],
  he_v2: [
    ["לִלְמֹד", "lilmod", "to learn / study", "verb", "לוֹמֵד, לוֹמֶדֶת, לוֹמְדִים, לוֹמְדוֹת", "אֲנִי לוֹמֵד עִבְרִית.", "I learn Hebrew."],
    ["לְדַבֵּר", "ledaber", "to speak", "verb", "מְדַבֵּר, מְדַבֶּרֶת, מְדַבְּרִים, מְדַבְּרוֹת", "הוּא מְדַבֵּר אַנְגְּלִית.", "He speaks English."],
    ["לָלֶכֶת", "lalechet", "to go / walk", "verb", "הוֹלֵךְ, הוֹלֶכֶת, הוֹלְכִים, הוֹלְכוֹת", "אֲנִי הוֹלֵךְ הַבַּיְתָה.", "I'm going home."],
    ["לָבוֹא", "lavo", "to come", "verb", "בָּא, בָּאָה, בָּאִים, בָּאוֹת", "הִיא בָּאָה מָחָר.", "She comes tomorrow."],
    ["לִרְאוֹת", "lir'ot", "to see", "verb", "רוֹאֶה, רוֹאָה, רוֹאִים, רוֹאוֹת", "אֲנִי רוֹאֶה אוֹתְךָ.", "I see you."],
    ["לֶאֱכֹל", "le'echol", "to eat", "verb", "אוֹכֵל, אוֹכֶלֶת, אוֹכְלִים, אוֹכְלוֹת", "אֲנַחְנוּ אוֹכְלִים בְּשֵׁשׁ.", "We eat at six."],
    ["לִשְׁתּוֹת", "lishtot", "to drink", "verb", "שׁוֹתֶה, שׁוֹתָה, שׁוֹתִים, שׁוֹתוֹת", "הוּא שׁוֹתֶה קָפֶה.", "He drinks coffee."],
    ["לִישֹׁן", "lishon", "to sleep", "verb", "יָשֵׁן, יְשֵׁנָה, יְשֵׁנִים, יְשֵׁנוֹת", "הַיֶּלֶד יָשֵׁן.", "The child is sleeping."],
    ["לִקְרֹא", "likro", "to read; to call", "verb", "קוֹרֵא, קוֹרֵאת, קוֹרְאִים, קוֹרְאוֹת", "אֲנִי קוֹרֵא סֵפֶר.", "I'm reading a book."],
    ["לִכְתֹּב", "lichtov", "to write", "verb", "כּוֹתֵב, כּוֹתֶבֶת, כּוֹתְבִים, כּוֹתְבוֹת", "הִיא כּוֹתֶבֶת מִכְתָּב.", "She writes a letter."],
    ["לָדַעַת", "lada'at", "to know (a fact)", "verb", "יוֹדֵעַ, יוֹדַעַת, יוֹדְעִים, יוֹדְעוֹת", "אֲנִי לֹא יוֹדֵעַ.", "I don't know."],
    ["לִרְצוֹת", "lirtsot", "to want", "verb", "רוֹצֶה, רוֹצָה, רוֹצִים, רוֹצוֹת", "אֲנִי רוֹצֶה מַיִם.", "I want water."],
    ["לֶאֱהֹב", "le'ehov", "to love / like", "verb", "אוֹהֵב, אוֹהֶבֶת, אוֹהֲבִים, אוֹהֲבוֹת", "אֲנִי אוֹהֵב הוֹקִי.", "I love hockey."],
    ["לַעֲבֹד", "la'avod", "to work", "verb", "עוֹבֵד, עוֹבֶדֶת, עוֹבְדִים, עוֹבְדוֹת", "הוּא עוֹבֵד בְּבַנְק.", "He works at a bank."],
    ["לָגוּר", "lagur", "to live (reside)", "verb", "גָּר, גָּרָה, גָּרִים, גָּרוֹת", "אֲנִי גָּר בְּתֵל אָבִיב.", "I live in Tel Aviv."],
    ["לָתֵת", "latet", "to give", "verb", "נוֹתֵן, נוֹתֶנֶת, נוֹתְנִים, נוֹתְנוֹת", "תֵּן לִי אֶת הַסֵּפֶר.", "Give me the book."],
    ["לָקַחַת", "lakachat", "to take", "verb", "לוֹקֵחַ, לוֹקַחַת, לוֹקְחִים, לוֹקְחוֹת", "אֲנִי לוֹקֵחַ אוֹטוֹבּוּס.", "I take a bus."],
    ["לַעֲשׂוֹת", "la'asot", "to do / make", "verb", "עוֹשֶׂה, עוֹשָׂה, עוֹשִׂים, עוֹשׂוֹת", "מָה אַתָּה עוֹשֶׂה?", "What are you doing?"],
    ["לְהָבִין", "lehavin", "to understand", "verb", "מֵבִין, מְבִינָה, מְבִינִים, מְבִינוֹת", "אֲנִי לֹא מֵבִין.", "I don't understand."],
    ["לִשְׁמֹעַ", "lishmo'a", "to hear / listen", "verb", "שׁוֹמֵעַ, שׁוֹמַעַת, שׁוֹמְעִים, שׁוֹמְעוֹת", "אַתָּה שׁוֹמֵעַ?", "Do you hear?"],
    ["לַחְשֹׁב", "lachshov", "to think", "verb", "חוֹשֵׁב, חוֹשֶׁבֶת, חוֹשְׁבִים, חוֹשְׁבוֹת", "אֲנִי חוֹשֵׁב שֶׁכֵּן.", "I think so."],
    ["לִקְנוֹת", "liknot", "to buy", "verb", "קוֹנֶה, קוֹנָה, קוֹנִים, קוֹנוֹת", "אֲנִי קוֹנֶה לֶחֶם.", "I'm buying bread."],
    ["לְשַׂחֵק", "lesachek", "to play", "verb", "מְשַׂחֵק, מְשַׂחֶקֶת, מְשַׂחֲקִים, מְשַׂחֲקוֹת", "אֲנַחְנוּ מְשַׂחֲקִים הוֹקִי.", "We play hockey."],
    ["לַעֲזֹר", "la'azor", "to help", "verb", "עוֹזֵר, עוֹזֶרֶת; עוֹזֵר לְ = helps (someone)", "אַתָּה יָכוֹל לַעֲזֹר לִי?", "Can you help me?"],
    ["יָכוֹל", "yachol", "can / able", "verb", "יְכוֹלָה, יְכוֹלִים, יְכוֹלוֹת", "אֲנִי יָכוֹל לָבוֹא.", "I can come."],
    ["צָרִיךְ", "tsarich", "need / must", "verb", "צְרִיכָה, צְרִיכִים, צְרִיכוֹת", "אֲנִי צָרִיךְ לָלֶכֶת.", "I need to go."],
    ["לְחַכּוֹת", "lechakot", "to wait", "verb", "מְחַכֶּה, מְחַכָּה; מְחַכֶּה לְ", "חַכֵּה רֶגַע!", "Wait a moment!"],
    ["לְהַתְחִיל", "lehatchil", "to begin", "verb", "מַתְחִיל, מַתְחִילָה", "הַמִּשְׂחָק מַתְחִיל.", "The game is starting."],
    ["לִגְמֹר", "ligmor", "to finish", "verb", "גּוֹמֵר, גּוֹמֶרֶת; לְסַיֵּם", "מָתַי אַתָּה גּוֹמֵר?", "When do you finish?"],
    ["לִפְגֹּשׁ", "lifgosh", "to meet", "verb", "פּוֹגֵשׁ, פּוֹגֶשֶׁת", "נִפְגָּשִׁים מָחָר?", "Shall we meet tomorrow?"]
  ],
  he_v3: [
    ["אֶפֶס", "efes", "zero", "num", "", "אֶפֶס אֶפֶס.", "Nil nil."],
    ["אַחַת", "achat", "one (f.)", "num", "אֶחָד (echad) = one (m.)", "שְׁאֵלָה אַחַת.", "One question."],
    ["שְׁתַּיִם", "shtayim", "two (f.)", "num", "שְׁנַיִם (shnayim) = two (m.); שְׁתֵּי / שְׁנֵי before a noun", "שְׁתֵּי דַּקּוֹת.", "Two minutes."],
    ["שָׁלוֹשׁ", "shalosh", "three (f.)", "num", "שְׁלוֹשָׁה (m.)", "שָׁלוֹשׁ שָׁנִים.", "Three years."],
    ["אַרְבַּע", "arba", "four (f.)", "num", "אַרְבָּעָה (m.)", "אַרְבַּע שָׁעוֹת.", "Four hours."],
    ["חָמֵשׁ", "chamesh", "five (f.)", "num", "חֲמִשָּׁה (m.)", "בְּשָׁעָה חָמֵשׁ.", "At five o'clock."],
    ["שֵׁשׁ", "shesh", "six (f.)", "num", "שִׁשָּׁה (m.)", "שֵׁשׁ שְׁאֵלוֹת.", "Six questions."],
    ["שֶׁבַע", "sheva", "seven (f.)", "num", "שִׁבְעָה (m.)", "שֶׁבַע בַּבֹּקֶר.", "Seven in the morning."],
    ["שְׁמוֹנֶה", "shmone", "eight (f.)", "num", "שְׁמוֹנָה (m.)", "שְׁמוֹנֶה שָׁעוֹת שֵׁנָה.", "Eight hours of sleep."],
    ["תֵּשַׁע", "tesha", "nine (f.)", "num", "תִּשְׁעָה (m.)", "תֵּשַׁע בָּעֶרֶב.", "Nine in the evening."],
    ["עֶשֶׂר", "eser", "ten (f.)", "num", "עֲשָׂרָה (m.)", "עֶשֶׂר דַּקּוֹת.", "Ten minutes."],
    ["עֶשְׂרִים", "esrim", "twenty", "num", "", "עֶשְׂרִים שֶׁקֶל.", "Twenty shekels."],
    ["מֵאָה", "me'a", "hundred", "num", "מָאתַיִם = two hundred", "מֵאָה אָחוּז.", "A hundred percent."],
    ["אֶלֶף", "elef", "thousand", "num", "אַלְפַּיִם = two thousand", "אֶלֶף תּוֹדוֹת.", "A thousand thanks."],
    ["שָׁעָה", "sha'a", "hour; o'clock", "n", "שָׁעוֹת (f.); מָה הַשָּׁעָה? = what time is it?", "מָה הַשָּׁעָה?", "What time is it?"],
    ["דַּקָּה", "daka", "minute", "n", "דַּקּוֹת (f.)", "עוֹד חָמֵשׁ דַּקּוֹת.", "Five more minutes."],
    ["יוֹם", "yom", "day", "n", "יָמִים (m.)", "יוֹם טוֹב!", "Have a good day!"],
    ["שָׁבוּעַ", "shavu'a", "week", "n", "שָׁבוּעוֹת (m.)", "שָׁבוּעַ טוֹב!", "Have a good week!"],
    ["חֹדֶשׁ", "chodesh", "month", "n", "חֳדָשִׁים (m.)", "כָּל חֹדֶשׁ.", "Every month."],
    ["שָׁנָה", "shana", "year", "n", "שָׁנִים (f.)", "שָׁנָה טוֹבָה!", "Happy new year!"],
    ["הַיּוֹם", "hayom", "today", "adv", "", "הַיּוֹם יוֹם שֵׁנִי.", "Today is Monday."],
    ["מָחָר", "machar", "tomorrow", "adv", "", "נִתְרָאֶה מָחָר.", "See you tomorrow."],
    ["אֶתְמוֹל", "etmol", "yesterday", "adv", "", "אֶתְמוֹל יָרַד גֶּשֶׁם.", "Yesterday it rained."],
    ["עַכְשָׁו", "achshav", "now", "adv", "", "עַכְשָׁו אֲנִי הוֹלֵךְ.", "Now I'm going."],
    ["יוֹם רִאשׁוֹן", "yom rishon", "Sunday (the first day)", "n", "the week starts on Sunday", "בְּיוֹם רִאשׁוֹן יֵשׁ לִי שִׁעוּר.", "On Sunday I have a class."],
    ["יוֹם שֵׁנִי", "yom sheni", "Monday", "n", "", "בְּיוֹם שֵׁנִי יֵשׁ הוֹקִי.", "On Monday there's hockey."],
    ["יוֹם שְׁלִישִׁי", "yom shlishi", "Tuesday", "n", "", "יוֹם שְׁלִישִׁי בָּעֶרֶב.", "Tuesday evening."],
    ["יוֹם רְבִיעִי", "yom revi'i", "Wednesday", "n", "", "בְּיוֹם רְבִיעִי.", "On Wednesday."],
    ["יוֹם חֲמִישִׁי", "yom chamishi", "Thursday", "n", "", "יוֹם חֲמִישִׁי בַּבֹּקֶר.", "Thursday morning."],
    ["יוֹם שִׁשִּׁי", "yom shishi", "Friday", "n", "", "בְּיוֹם שִׁשִּׁי יֵשׁ מִשְׂחָק.", "On Friday there's a game."],
    ["שַׁבָּת", "shabat", "Saturday / Sabbath", "n", "שַׁבָּת שָׁלוֹם = Sabbath greeting", "שַׁבָּת שָׁלוֹם!", "Shabbat shalom!"],
    ["בֹּקֶר", "boker", "morning", "n", "בֹּקֶר טוֹב", "בֹּקֶר טוֹב!", "Good morning!"],
    ["עֶרֶב", "erev", "evening", "n", "עֶרֶב טוֹב", "הָעֶרֶב אֲנַחְנוּ מְשַׂחֲקִים.", "This evening we play."],
    ["לַיְלָה", "laila", "night", "n", "לַיְלָה טוֹב (m., despite the -a)", "לַיְלָה טוֹב!", "Good night!"]
  ],
  he_v4: [
    ["אִישׁ", "ish", "man", "n", "אֲנָשִׁים (people)", "אִישׁ זָקֵן.", "An old man."],
    ["אִשָּׁה", "isha", "woman; wife", "n", "נָשִׁים (f.)", "אִשָּׁה צְעִירָה.", "A young woman."],
    ["יֶלֶד", "yeled", "boy / child", "n", "יְלָדִים; יַלְדָּה = girl", "הַיֶּלֶד מְשַׂחֵק.", "The boy is playing."],
    ["יַלְדָּה", "yalda", "girl", "n", "יְלָדוֹת", "הַיַּלְדָּה קוֹרֵאת.", "The girl is reading."],
    ["חָבֵר", "chaver", "friend (m.); boyfriend", "n", "חֲבֵרָה (f.), חֲבֵרִים", "הַחָבֵר הֲכִי טוֹב שֶׁלִּי.", "My best friend."],
    ["מִשְׁפָּחָה", "mishpacha", "family", "n", "מִשְׁפָּחוֹת", "הַמִּשְׁפָּחָה שֶׁלִּי גָּרָה בְּקָנָדָה.", "My family lives in Canada."],
    ["אִמָּא", "ima", "mum", "n", "אֵם = mother", "אִמָּא מִתְקַשֶּׁרֶת.", "Mum is calling."],
    ["אַבָּא", "aba", "dad", "n", "אָב = father", "אַבָּא נוֹהֵג.", "Dad drives."],
    ["אָח", "ach", "brother", "n", "אַחִים", "הָאָח שֶׁלִּי גָּדוֹל מִמֶּנִּי.", "My brother is older than me."],
    ["אָחוֹת", "achot", "sister; nurse", "n", "אֲחָיוֹת", "אָחוֹת שֶׁלִּי לוֹמֶדֶת.", "My sister is studying."],
    ["בַּיִת", "bayit", "house / home", "n", "בָּתִּים; הַבַּיְתָה = homeward; בַּבַּיִת = at home", "אֲנִי בַּבַּיִת.", "I'm at home."],
    ["דִּירָה", "dira", "apartment", "n", "דִּירוֹת", "דִּירָה קְטַנָּה.", "A small apartment."],
    ["חֶדֶר", "cheder", "room", "n", "חֲדָרִים", "הַחֶדֶר שֶׁלִּי קָטָן.", "My room is small."],
    ["מִטְבָּח", "mitbach", "kitchen", "n", "מִטְבָּחִים", "אֲנַחְנוּ אוֹכְלִים בַּמִּטְבָּח.", "We eat in the kitchen."],
    ["דֶּלֶת", "delet", "door", "n", "דְּלָתוֹת (f.)", "סְגֹר אֶת הַדֶּלֶת!", "Close the door!"],
    ["חַלּוֹן", "chalon", "window", "n", "חַלּוֹנוֹת (m.)", "פְּתַח אֶת הַחַלּוֹן.", "Open the window."],
    ["שֻׁלְחָן", "shulchan", "table", "n", "שֻׁלְחָנוֹת (m.)", "הַסֵּפֶר עַל הַשֻּׁלְחָן.", "The book is on the table."],
    ["כִּסֵּא", "kise", "chair", "n", "כִּסְאוֹת (m.)", "עוֹד כִּסֵּא.", "One more chair."],
    ["מִטָּה", "mita", "bed", "n", "מִטּוֹת", "אֲנִי בַּמִּטָּה.", "I'm in bed."],
    ["מְכוֹנִית", "mechonit", "car", "n", "מְכוֹנִיּוֹת; אוֹטוֹ (colloquial)", "מְכוֹנִית חֲדָשָׁה.", "A new car."],
    ["עִיר", "ir", "city", "n", "עָרִים (f.)", "עִיר גְּדוֹלָה.", "A big city."],
    ["אֶרֶץ", "erets", "country / land", "n", "אֲרָצוֹת (f.); הָאָרֶץ = Israel (the Land)", "אֲנִי בָּאָרֶץ.", "I'm in Israel."],
    ["בֵּית סֵפֶר", "beit sefer", "school", "n", "בָּתֵּי סֵפֶר", "הַיְלָדִים בְּבֵית הַסֵּפֶר.", "The children are at school."],
    ["עֲבוֹדָה", "avoda", "work / job", "n", "עֲבוֹדוֹת", "אֲנִי הוֹלֵךְ לָעֲבוֹדָה.", "I'm going to work."],
    ["טֶלֶפוֹן", "telefon", "telephone", "n", "פֶּלֶאפוֹן / נַיָּד = mobile", "הַטֶּלֶפוֹן שֶׁלִּי מֵת.", "My phone is dead."],
    ["מַחְשֵׁב", "machshev", "computer", "n", "מַחְשְׁבִים", "מַחְשֵׁב חָדָשׁ.", "A new computer."],
    ["סֵפֶר", "sefer", "book", "n", "סְפָרִים", "סֵפֶר טוֹב.", "A good book."],
    ["כֶּסֶף", "kesef", "money; silver", "n", "", "אֵין לִי כֶּסֶף.", "I have no money."],
    ["שֵׁם", "shem", "name", "n", "שֵׁמוֹת (m.)", "מָה הַשֵּׁם שֶׁלְּךָ?", "What is your name?"],
    ["דָּבָר", "davar", "thing; word", "n", "דְּבָרִים", "מַשֶּׁהוּ = something; שׁוּם דָּבָר = nothing", "שׁוּם דָּבָר.", "Nothing."]
  ],
  he_v5: [
    ["אֹכֶל", "ochel", "food", "n", "", "הָאֹכֶל טָעִים.", "The food is tasty."],
    ["מַיִם", "mayim", "water", "n", "plural form, m.", "כּוֹס מַיִם, בְּבַקָּשָׁה.", "A glass of water, please."],
    ["קָפֶה", "kafe", "coffee", "n", "", "קָפֶה הָפוּךְ = latte", "אַתָּה רוֹצֶה קָפֶה?", "Do you want coffee?"],
    ["תֵּה", "te", "tea", "n", "", "תֵּה עִם נַעֲנַע.", "Tea with mint."],
    ["חָלָב", "chalav", "milk", "n", "", "חָלָב בַּקָּפֶה?", "Milk in the coffee?"],
    ["לֶחֶם", "lechem", "bread", "n", "", "לֶחֶם טָרִי.", "Fresh bread."],
    ["חֶמְאָה", "chem'a", "butter", "n", "", "חֶמְאָה עַל הַלֶּחֶם.", "Butter on the bread."],
    ["גְּבִינָה", "gvina", "cheese", "n", "גְּבִינוֹת", "גְּבִינָה לְבָנָה.", "White (soft) cheese."],
    ["בֵּיצָה", "beitsa", "egg", "n", "בֵּיצִים (f.)", "שְׁתֵּי בֵּיצִים.", "Two eggs."],
    ["בָּשָׂר", "basar", "meat", "n", "", "אֲנִי לֹא אוֹכֵל בָּשָׂר.", "I don't eat meat."],
    ["דָּג", "dag", "fish", "n", "דָּגִים", "דָּג בְּיוֹם שִׁשִּׁי.", "Fish on Friday."],
    ["עוֹף", "of", "chicken (meat); bird", "n", "", "עוֹף עִם אֹרֶז.", "Chicken with rice."],
    ["יְרָקוֹת", "yerakot", "vegetables", "n", "יֶרֶק (sg.)", "סָלָט יְרָקוֹת.", "Vegetable salad."],
    ["פֵּרוֹת", "perot", "fruit", "n", "פְּרִי (sg.)", "פֵּרוֹת טְרִיִּים.", "Fresh fruit."],
    ["תַּפּוּחַ", "tapu'ach", "apple", "n", "תַּפּוּחִים; תַּפּוּחַ אֲדָמָה = potato", "תַּפּוּחַ אָדֹם.", "A red apple."],
    ["אֹרֶז", "orez", "rice", "n", "", "אֹרֶז לָבָן.", "White rice."],
    ["מָרָק", "marak", "soup", "n", "מְרָקִים", "מָרָק חַם.", "Hot soup."],
    ["סֻכָּר", "sukar", "sugar", "n", "", "בְּלִי סֻכָּר, תּוֹדָה.", "No sugar, thanks."],
    ["מֶלַח", "melach", "salt", "n", "", "קְצָת מֶלַח.", "A little salt."],
    ["אֲרוּחַת בֹּקֶר", "aruchat boker", "breakfast", "n", "אֲרוּחָה = meal", "אֲרוּחַת בֹּקֶר בְּשֶׁבַע.", "Breakfast at seven."],
    ["אֲרוּחַת צָהֳרַיִם", "aruchat tsohorayim", "lunch", "n", "", "אֲרוּחַת צָהֳרַיִם בְּיַחַד.", "Lunch together."],
    ["אֲרוּחַת עֶרֶב", "aruchat erev", "dinner", "n", "", "אֲרוּחַת הָעֶרֶב מוּכָנָה.", "Dinner is ready."],
    ["מִסְעָדָה", "mis'ada", "restaurant", "n", "מִסְעָדוֹת", "מִסְעָדָה טוֹבָה.", "A good restaurant."],
    ["תַּפְרִיט", "tafrit", "menu", "n", "", "אֶפְשָׁר תַּפְרִיט?", "Can I have a menu?"],
    ["חֶשְׁבּוֹן", "cheshbon", "the bill; account; arithmetic", "n", "", "חֶשְׁבּוֹן, בְּבַקָּשָׁה!", "The bill, please!"],
    ["לְהַזְמִין", "lehazmin", "to order; to invite", "verb", "מַזְמִין, מַזְמִינָה", "אֲנִי רוֹצֶה לְהַזְמִין.", "I'd like to order."],
    ["רָעֵב", "ra'ev", "hungry", "adj", "רְעֵבָה, רְעֵבִים", "אֲנִי רָעֵב.", "I'm hungry."],
    ["צָמֵא", "tsame", "thirsty", "adj", "צְמֵאָה", "אַתְּ צְמֵאָה?", "Are you (f.) thirsty?"],
    ["טָעִים", "ta'im", "tasty", "adj", "טְעִימָה, טְעִימִים", "זֶה הָיָה טָעִים!", "That was tasty!"],
    ["בְּתֵאָבוֹן", "bete'avon", "bon appétit", "phrase", "", "בְּתֵאָבוֹן!", "Enjoy your meal!"]
  ],
  he_v6: [
    ["לָקוּם", "lakum", "to get up", "verb", "קָם, קָמָה, קָמִים", "אֲנִי קָם בְּשֵׁשׁ.", "I get up at six."],
    ["לְהִתְקַלֵּחַ", "lehitkale'ach", "to shower", "verb", "מִתְקַלֵּחַ, מִתְקַלַּחַת", "אֲנִי מִתְקַלֵּחַ אַחֲרֵי הָאִמּוּן.", "I shower after practice."],
    ["לְהִתְלַבֵּשׁ", "lehitlabesh", "to get dressed", "verb", "מִתְלַבֵּשׁ, מִתְלַבֶּשֶׁת", "תִּתְלַבֵּשׁ!", "Get dressed!"],
    ["לְבַשֵּׁל", "levashel", "to cook", "verb", "מְבַשֵּׁל, מְבַשֶּׁלֶת", "מִי מְבַשֵּׁל הָעֶרֶב?", "Who's cooking tonight?"],
    ["לְנַקּוֹת", "lenakot", "to clean", "verb", "מְנַקֶּה, מְנַקָּה", "אֲנִי מְנַקֶּה בְּשַׁבָּת.", "I clean on Saturday."],
    ["לִרְחֹץ", "lirchots", "to wash", "verb", "רוֹחֵץ; לִרְחֹץ יָדַיִם", "לִרְחֹץ יָדַיִם.", "To wash hands."],
    ["לְהִתְאַמֵּן", "lehit'amen", "to train / practise", "verb", "מִתְאַמֵּן, מִתְאַמֶּנֶת; אִמּוּן = practice", "אֲנִי מִתְאַמֵּן שָׁלוֹשׁ פְּעָמִים בְּשָׁבוּעַ.", "I train three times a week."],
    ["לָנוּחַ", "lanu'ach", "to rest", "verb", "נָח, נָחָה", "תָּנוּחַ קְצָת.", "Rest a little."],
    ["לָשֶׁבֶת", "lashevet", "to sit", "verb", "יוֹשֵׁב, יוֹשֶׁבֶת", "שֵׁב, בְּבַקָּשָׁה.", "Sit down, please."],
    ["לַעֲמֹד", "la'amod", "to stand", "verb", "עוֹמֵד, עוֹמֶדֶת", "הוּא עוֹמֵד שָׁם.", "He is standing there."],
    ["לִפְתֹּחַ", "lifto'ach", "to open", "verb", "פּוֹתֵחַ, פּוֹתַחַת", "תִּפְתַּח אֶת הַדֶּלֶת.", "Open the door."],
    ["לִסְגֹּר", "lisgor", "to close", "verb", "סוֹגֵר, סוֹגֶרֶת", "הַחֲנוּת סוֹגֶרֶת בִּשְׁמוֹנֶה.", "The shop closes at eight."],
    ["בְּגָדִים", "bgadim", "clothes", "n", "בֶּגֶד (sg.)", "בְּגָדִים חֲדָשִׁים.", "New clothes."],
    ["נַעַל", "na'al", "shoe", "n", "נַעֲלַיִם (f.)", "תּוֹרִיד אֶת הַנַּעֲלַיִם.", "Take off your shoes."],
    ["מְעִיל", "me'il", "coat", "n", "מְעִילִים", "מְעִיל חַם.", "A warm coat."],
    ["חֻלְצָה", "chultsa", "shirt", "n", "חֻלְצוֹת", "חֻלְצַת הַהוֹקִי שֶׁלִּי.", "My hockey jersey."],
    ["מִכְנָסַיִם", "michnasayim", "trousers", "n", "", "מִכְנָסַיִם כְּחֻלִּים.", "Blue trousers."],
    ["תִּיק", "tik", "bag", "n", "תִּיקִים", "אֵיפֹה הַתִּיק שֶׁלִּי?", "Where is my bag?"],
    ["מַפְתֵּחַ", "mafte'ach", "key", "n", "מַפְתְּחוֹת (m.)", "אִבַּדְתִּי אֶת הַמַּפְתֵּחַ.", "I've lost the key."],
    ["שָׁעוֹן", "sha'on", "clock / watch", "n", "שְׁעוֹנִים", "שָׁעוֹן חָדָשׁ.", "A new watch."],
    ["מוּזִיקָה", "muzika", "music", "n", "", "אֲנִי אוֹהֵב מוּזִיקָה.", "I like music."],
    ["סֶרֶט", "seret", "film", "n", "סְרָטִים", "רוֹצִים לִרְאוֹת סֶרֶט?", "Want to see a movie?"],
    ["מִשְׂחָק", "mischak", "game", "n", "מִשְׂחָקִים", "נִצַּחְנוּ בַּמִּשְׂחָק!", "We won the game!"],
    ["קְבוּצָה", "kvutsa", "team / group", "n", "קְבוּצוֹת", "הַקְּבוּצָה שֶׁלָּנוּ טוֹבָה.", "Our team is good."],
    ["הוֹקִי", "hoki", "hockey", "n", "", "אֲנִי מְשַׂחֵק הוֹקִי.", "I play hockey."],
    ["זְמַן", "zman", "time", "n", "", "אֵין לִי זְמַן.", "I don't have time."],
    ["לְנַצֵּחַ", "lenatse'ach", "to win", "verb", "מְנַצֵּחַ, מְנַצַּחַת", "אֲנַחְנוּ מְנַצְּחִים!", "We're winning!"],
    ["לְהַפְסִיד", "lehafsid", "to lose", "verb", "מַפְסִיד, מַפְסִידָה", "לֹא רוֹצִים לְהַפְסִיד.", "We don't want to lose."],
    ["שַׂחְקָן", "sachkan", "player; actor", "n", "שַׂחְקָנִים", "שַׂחְקָן טוֹב.", "A good player."],
    ["אִמּוּן", "imun", "practice / training", "n", "אִמּוּנִים", "יֵשׁ אִמּוּן הָעֶרֶב.", "There's practice tonight."]
  ],
  he_v7: [
    ["רְחוֹב", "rechov", "street", "n", "רְחוֹבוֹת (m.)", "אֵיזֶה רְחוֹב?", "Which street?"],
    ["דֶּרֶךְ", "derech", "road / way", "n", "דְּרָכִים (f.)", "הַדֶּרֶךְ לָעִיר.", "The way to the city."],
    ["כִּכָּר", "kikar", "square", "n", "", "נִפְגָּשִׁים בַּכִּכָּר.", "We'll meet at the square."],
    ["חֲנוּת", "chanut", "shop", "n", "חֲנֻיּוֹת (f.)", "הַחֲנוּת פְּתוּחָה.", "The shop is open."],
    ["בַּנְק", "bank", "bank", "n", "", "הַבַּנְק שָׁם.", "The bank is there."],
    ["בֵּית חוֹלִים", "beit cholim", "hospital", "n", "", "לְבֵית הַחוֹלִים!", "To the hospital!"],
    ["בֵּית מִרְקַחַת", "beit mirkachat", "pharmacy", "n", "", "יֵשׁ פֹּה בֵּית מִרְקַחַת?", "Is there a pharmacy here?"],
    ["תַּחֲנָה", "tachana", "station / stop", "n", "תַּחֲנוֹת; תַּחֲנָה מֶרְכָּזִית", "הַתַּחֲנָה הַמֶּרְכָּזִית.", "The central station."],
    ["רַכֶּבֶת", "rakevet", "train", "n", "רַכָּבוֹת", "הָרַכֶּבֶת מְאַחֶרֶת.", "The train is late."],
    ["אוֹטוֹבּוּס", "otobus", "bus", "n", "", "הָאוֹטוֹבּוּס מַגִּיעַ.", "The bus is coming."],
    ["מָטוֹס", "matos", "plane", "n", "טִיסָה = flight", "הַטִּיסָה שֶׁלִּי בְּעֶשֶׂר.", "My flight is at ten."],
    ["כַּרְטִיס", "kartis", "ticket; card", "n", "כַּרְטִיסִים", "כַּרְטִיס לְחֵיפָה.", "A ticket to Haifa."],
    ["יָמִינָה", "yamina", "to the right", "adv", "יָמִין = right", "תִּפְנֶה יָמִינָה.", "Turn right."],
    ["שְׂמֹאלָה", "smola", "to the left", "adv", "שְׂמֹאל = left", "זֶה מִשְּׂמֹאל.", "It's on the left."],
    ["יָשָׁר", "yashar", "straight", "adv", "", "לֵךְ יָשָׁר.", "Go straight."],
    ["קָרוֹב", "karov", "near", "adj", "קְרוֹבָה", "זֶה קָרוֹב.", "It's close."],
    ["רָחוֹק", "rachok", "far", "adj", "רְחוֹקָה", "זֶה רָחוֹק?", "Is it far?"],
    ["פֹּה", "po", "here", "adv", "כָּאן = here (also)", "בּוֹא הֵנָּה!", "Come here!"],
    ["שָׁם", "sham", "there", "adv", "לְשָׁם = to there", "לֵךְ לְשָׁם.", "Go there."],
    ["מַפָּה", "mapa", "map; tablecloth", "n", "", "יֵשׁ לְךָ מַפָּה?", "Do you have a map?"],
    ["מָלוֹן", "malon", "hotel", "n", "בָּתֵּי מָלוֹן", "אֲנַחְנוּ בְּמָלוֹן.", "We're at a hotel."],
    ["טִיּוּל", "tiyul", "trip / hike", "n", "לְטַיֵּל = to travel/hike", "טִיּוּל נָעִים!", "Have a nice trip!"],
    ["לִנְסֹעַ", "linso'a", "to travel / go (by vehicle)", "verb", "נוֹסֵעַ, נוֹסַעַת", "אֲנַחְנוּ נוֹסְעִים בְּרַכֶּבֶת.", "We go by train."],
    ["אוֹפַנַּיִם", "ofanayim", "bicycle", "n", "", "אֲנִי רוֹכֵב עַל אוֹפַנַּיִם.", "I ride a bike."],
    ["לַעֲצֹר", "la'atsor", "to stop", "verb", "עוֹצֵר, עוֹצֶרֶת", "תַּעֲצֹר כָּאן!", "Stop here!"],
    ["לִשְׁאֹל", "lish'ol", "to ask", "verb", "שׁוֹאֵל, שׁוֹאֶלֶת; שְׁאֵלָה = question", "אֶפְשָׁר לִשְׁאֹל מַשֶּׁהוּ?", "May I ask something?"],
    ["לַעֲנוֹת", "la'anot", "to answer", "verb", "עוֹנֶה, עוֹנָה; תְּשׁוּבָה = answer", "תַּעֲנֶה עַל הַשְּׁאֵלָה.", "Answer the question."],
    ["לִמְצֹא", "limtso", "to find", "verb", "מוֹצֵא, מוֹצֵאת", "אֲנִי לֹא מוֹצֵא.", "I can't find it."],
    ["לְהָבִיא", "lehavi", "to bring", "verb", "מֵבִיא, מְבִיאָה", "תָּבִיא מְעִיל.", "Bring a coat."],
    ["אֶפְשָׁר", "efshar", "possible / may I", "adv", "אִי אֶפְשָׁר = impossible", "אֶפְשָׁר לַעֲזֹר?", "Can I help?"]
  ],
  he_v8: [
    ["מוֹרֶה", "more", "teacher (m.)", "n", "מוֹרָה (f.), מוֹרִים", "הַמּוֹרֶה מַסְבִּיר.", "The teacher explains."],
    ["תַּלְמִיד", "talmid", "pupil", "n", "תַּלְמִידָה, תַּלְמִידִים", "עֶשְׂרִים תַּלְמִידִים.", "Twenty pupils."],
    ["סְטוּדֶנְט", "student", "student", "n", "סְטוּדֶנְטִית (f.)", "אֲנִי סְטוּדֶנְט.", "I'm a student."],
    ["אוּנִיבֶרְסִיטָה", "universita", "university", "n", "", "אֲנִי לוֹמֵד בָּאוּנִיבֶרְסִיטָה.", "I study at university."],
    ["קוּרְס", "kurs", "course", "n", "קוּרְסִים", "קוּרְס בְּעִבְרִית.", "A course in Hebrew."],
    ["מִבְחָן", "mivchan", "test / exam", "n", "מִבְחָנִים", "יֵשׁ לִי מִבְחָן בְּיוֹם שִׁשִּׁי.", "I have a test on Friday."],
    ["שִׁעוּרֵי בַּיִת", "shi'urei bayit", "homework", "n", "שִׁעוּר = lesson", "עָשִׂיתָ שִׁעוּרֵי בַּיִת?", "Did you do the homework?"],
    ["מִשְׂרָד", "misrad", "office", "n", "מִשְׂרָדִים", "אֲנִי בַּמִּשְׂרָד.", "I'm at the office."],
    ["מְנַהֵל", "menahel", "boss / manager", "n", "מְנַהֶלֶת (f.)", "הַמְּנַהֵל שֶׁלִּי נֶחְמָד.", "My boss is nice."],
    ["עָמִית", "amit", "colleague", "n", "עֲמִיתִים; חָבֵר לָעֲבוֹדָה", "חָבֵר מֵהָעֲבוֹדָה.", "A friend from work."],
    ["פְּגִישָׁה", "pgisha", "meeting", "n", "פְּגִישׁוֹת", "יֵשׁ לָנוּ פְּגִישָׁה בְּשָׁלוֹשׁ.", "We have a meeting at three."],
    ["מַשְׂכֹּרֶת", "maskoret", "salary", "n", "", "הַמַּשְׂכֹּרֶת מַגִּיעָה בָּעֶשְׂרִים וַחֲמִשָּׁה.", "The salary comes on the 25th."],
    ["חֶבְרָה", "chevra", "company; society", "n", "חֲבָרוֹת", "חֶבְרָה יִשְׂרְאֵלִית.", "An Israeli company."],
    ["לָקוֹחַ", "lako'ach", "customer", "n", "לָקוֹחוֹת", "הַלָּקוֹחַ תָּמִיד צוֹדֵק.", "The customer is always right."],
    ["מְהַנְדֵּס", "mehandes", "engineer", "n", "מְהַנְדֶּסֶת", "הִיא מְהַנְדֶּסֶת.", "She is an engineer."],
    ["רוֹפֵא", "rofe", "doctor", "n", "רוֹפְאָה, רוֹפְאִים", "אֲנִי צָרִיךְ רוֹפֵא.", "I need a doctor."],
    ["שׁוֹטֵר", "shoter", "police officer", "n", "מִשְׁטָרָה = police", "תִּקְרָא לַמִּשְׁטָרָה!", "Call the police!"],
    ["טַבָּח", "tabach", "cook / chef", "n", "", "הַטַּבָּח מְבַשֵּׁל.", "The chef cooks."],
    ["לִלְמֹד", "lilmod", "to study / learn", "verb", "", "אֲנִי לוֹמֵד לַמִּבְחָן.", "I'm studying for the test."],
    ["לְתַרְגֵּל", "letargel", "to practise", "verb", "מְתַרְגֵּל; תַּרְגִּיל = exercise", "לְתַרְגֵּל כָּל יוֹם.", "Practise every day."],
    ["טָעוּת", "ta'ut", "mistake", "n", "טָעֻיּוֹת (f.)", "כֻּלָּם עוֹשִׂים טָעֻיּוֹת.", "Everyone makes mistakes."],
    ["נָכוֹן", "nachon", "correct / right", "adj", "נְכוֹנָה", "נָכוֹן!", "Correct!"],
    ["לֹא נָכוֹן", "lo nachon", "wrong / incorrect", "adj", "", "זֶה לֹא נָכוֹן.", "That's wrong."],
    ["קָשֶׁה", "kashe", "difficult / hard", "adj", "קָשָׁה, קָשִׁים", "עִבְרִית לֹא כָּל כָּךְ קָשָׁה.", "Hebrew isn't that hard."],
    ["קַל", "kal", "easy; light", "adj", "קַלָּה, קַלִּים", "זֶה הָיָה קַל.", "That was easy."],
    ["חָשׁוּב", "chashuv", "important", "adj", "חֲשׁוּבָה", "זֶה חָשׁוּב.", "It's important."],
    ["מוּכָן", "muchan", "ready", "adj", "מוּכָנָה", "אַתָּה מוּכָן?", "Are you ready?"],
    ["שְׁאֵלָה", "she'ela", "question", "n", "שְׁאֵלוֹת", "יֵשׁ לִי שְׁאֵלָה.", "I have a question."],
    ["תְּשׁוּבָה", "tshuva", "answer", "n", "תְּשׁוּבוֹת", "תְּשׁוּבָה נְכוֹנָה.", "A correct answer."],
    ["לִזְכֹּר", "lizkor", "to remember", "verb", "זוֹכֵר, זוֹכֶרֶת", "אֲנִי לֹא זוֹכֵר.", "I don't remember."]
  ],
  he_v9: [
    ["רֹאשׁ", "rosh", "head", "n", "רָאשִׁים; כְּאֵב רֹאשׁ = headache", "יֵשׁ לִי כְּאֵב רֹאשׁ.", "I have a headache."],
    ["יָד", "yad", "hand", "n", "יָדַיִם (f.)", "לִרְחֹץ יָדַיִם.", "Wash hands."],
    ["רֶגֶל", "regel", "foot / leg", "n", "רַגְלַיִם (f.)", "כּוֹאֶבֶת לִי הָרֶגֶל.", "My leg hurts."],
    ["בֶּרֶךְ", "berech", "knee", "n", "בִּרְכַּיִם (f.)", "פָּצַעְתִּי אֶת הַבֶּרֶךְ.", "I hurt my knee."],
    ["זְרוֹעַ", "zro'a", "arm", "n", "זְרוֹעוֹת (f.)", "זְרוֹעַ שְׂמֹאל.", "Left arm."],
    ["עַיִן", "ayin", "eye", "n", "עֵינַיִם (f.)", "עֵינַיִם כְּחֻלּוֹת.", "Blue eyes."],
    ["אֹזֶן", "ozen", "ear", "n", "אָזְנַיִם (f.)", "כּוֹאֶבֶת לִי הָאֹזֶן.", "My ear hurts."],
    ["פֶּה", "pe", "mouth", "n", "", "תִּפְתַּח אֶת הַפֶּה.", "Open your mouth."],
    ["אַף", "af", "nose", "n", "", "אַף אָדֹם.", "A red nose."],
    ["בֶּטֶן", "beten", "stomach / belly", "n", "כְּאֵב בֶּטֶן", "כְּאֵב בֶּטֶן.", "Stomach ache."],
    ["לֵב", "lev", "heart", "n", "לִבּוֹת", "הַלֵּב דּוֹפֵק.", "The heart beats."],
    ["גַּב", "gav", "back", "n", "", "כְּאֵב גַּב.", "Back pain."],
    ["שֵׂעָר", "se'ar", "hair", "n", "", "שֵׂעָר בָּהִיר.", "Light hair."],
    ["כּוֹאֵב", "ko'ev", "hurts", "verb", "כּוֹאֶבֶת; כּוֹאֵב לִי = it hurts me", "כּוֹאֵב לִי הָרֹאשׁ.", "My head hurts."],
    ["חוֹלֶה", "chole", "sick", "adj", "חוֹלָה, חוֹלִים", "אֲנִי חוֹלֶה הַיּוֹם.", "I'm sick today."],
    ["בָּרִיא", "bari", "healthy", "adj", "בְּרִיאָה; בְּרִיאוּת = health", "הוּא בָּרִיא שׁוּב.", "He's healthy again."],
    ["עָיֵף", "ayef", "tired", "adj", "עֲיֵפָה, עֲיֵפִים", "אֲנִי כָּל כָּךְ עָיֵף.", "I'm so tired."],
    ["תְּרוּפָה", "trufa", "medicine", "n", "תְּרוּפוֹת", "קַח אֶת הַתְּרוּפָה.", "Take the medicine."],
    ["חֹם", "chom", "fever; heat", "n", "", "יֵשׁ לָהּ חֹם.", "She has a fever."],
    ["מְצֻנָּן", "metsunan", "having a cold", "adj", "מְצֻנֶּנֶת", "אֲנִי מְצֻנָּן.", "I have a cold."],
    ["פְּצִיעָה", "ptsi'a", "injury", "n", "פְּצִיעוֹת", "פְּצִיעַת הוֹקִי.", "A hockey injury."],
    ["חָזָק", "chazak", "strong", "adj", "חֲזָקָה, חֲזָקִים", "קְבוּצָה חֲזָקָה.", "A strong team."],
    ["חַלָּשׁ", "chalash", "weak", "adj", "חַלָּשָׁה", "אֲנִי מַרְגִּישׁ חַלָּשׁ.", "I feel weak."],
    ["גָּבוֹהַּ", "gavo'ah", "tall / high", "adj", "גְּבוֹהָה, גְּבוֹהִים", "הוּא גָּבוֹהַּ.", "He is tall."],
    ["נָמוּךְ", "namuch", "short / low", "adj", "נְמוּכָה", "כִּסֵּא נָמוּךְ.", "A low chair."],
    ["צָעִיר", "tsa'ir", "young", "adj", "צְעִירָה, צְעִירִים", "קְבוּצָה צְעִירָה.", "A young team."],
    ["זָקֵן", "zaken", "old (person)", "adj", "זְקֵנָה; יָשָׁן = old (thing)", "אִישׁ זָקֵן.", "An old man."],
    ["גּוּף", "guf", "body", "n", "", "גּוּף חָזָק.", "A strong body."],
    ["שֵׁנָה", "shena", "sleep", "n", "", "שֵׁנָה זֶה חָשׁוּב.", "Sleep is important."],
    ["לְהַרְגִּישׁ", "lehargish", "to feel", "verb", "מַרְגִּישׁ, מַרְגִּישָׁה", "אֲנִי מַרְגִּישׁ טוֹב.", "I feel good."]
  ],
  he_v10: [
    ["שָׂמֵחַ", "same'ach", "happy", "adj", "שְׂמֵחָה, שְׂמֵחִים", "אֲנִי שָׂמֵחַ הַיּוֹם.", "I'm happy today."],
    ["עָצוּב", "atsuv", "sad", "adj", "עֲצוּבָה", "אַל תִּהְיֶה עָצוּב.", "Don't be sad."],
    ["כּוֹעֵס", "ko'es", "angry", "adj", "כּוֹעֶסֶת", "הוּא כּוֹעֵס.", "He is angry."],
    ["מְפַחֵד", "mefached", "afraid", "verb", "מְפַחֶדֶת; מְפַחֵד מִ = afraid of", "אֲנִי לֹא מְפַחֵד.", "I'm not afraid."],
    ["לָחוּץ", "lachuts", "stressed / nervous", "adj", "לְחוּצָה", "לָחוּץ לִפְנֵי הַמִּשְׂחָק.", "Nervous before the game."],
    ["רָגוּעַ", "ragu'a", "calm", "adj", "רְגוּעָה", "תִּהְיֶה רָגוּעַ.", "Be calm."],
    ["מְרֻצֶּה", "merutse", "satisfied", "adj", "מְרֻצָּה", "אֲנִי מְרֻצֶּה.", "I'm satisfied."],
    ["מְאֻכְזָב", "me'uchzav", "disappointed", "adj", "מְאֻכְזֶבֶת", "מְאֻכְזָב מֵהַתּוֹצָאָה.", "Disappointed with the result."],
    ["גֵּאֶה", "ge'e", "proud", "adj", "גֵּאָה; גֵּאֶה בְּ", "אֲנִי גֵּאֶה בְּךָ.", "I'm proud of you."],
    ["מְשַׁעֲמֵם", "mesha'amem", "boring", "adj", "מְשַׁעֲמֶמֶת", "סֶרֶט מְשַׁעֲמֵם.", "A boring film."],
    ["כֵּיף", "keif", "fun", "n", "כֵּיפִי = fun (adj.)", "הָיָה כֵּיף!", "That was fun!"],
    ["מְעַנְיֵן", "me'anyen", "interesting", "adj", "מְעַנְיֶנֶת", "סֵפֶר מְעַנְיֵן.", "An interesting book."],
    ["מוּזָר", "muzar", "strange", "adj", "מוּזָרָה", "זֶה מוּזָר.", "That's strange."],
    ["יָפֶה", "yafe", "beautiful / nice", "adj", "יָפָה, יָפִים", "יוֹם יָפֶה.", "A beautiful day."],
    ["נֶחְמָד", "nechmad", "nice / kind", "adj", "נֶחְמָדָה", "הוּא נֶחְמָד.", "He is nice."],
    ["טִפֵּשׁ", "tipesh", "stupid", "adj", "טִפְּשָׁה", "זֶה הָיָה טִפְּשִׁי.", "That was stupid."],
    ["לִשְׂנֹא", "lisno", "to hate", "verb", "שׂוֹנֵא, שׂוֹנֵאת", "אֲנִי שׂוֹנֵא לְהַפְסִיד.", "I hate losing."],
    ["לְקַוּוֹת", "lekavot", "to hope", "verb", "מְקַוֶּה, מְקַוָּה", "אֲנִי מְקַוֶּה.", "I hope so."],
    ["לְהַאֲמִין", "leha'amin", "to believe", "verb", "מַאֲמִין, מַאֲמִינָה", "אֲנִי מַאֲמִין לְךָ.", "I believe you."],
    ["אוּלַי", "ulai", "maybe", "adv", "", "אוּלַי מָחָר.", "Maybe tomorrow."],
    ["בֶּטַח", "betach", "sure / of course", "adv", "", "בֶּטַח!", "Sure!"],
    ["בֶּאֱמֶת", "be'emet", "really / truly", "adv", "", "בֶּאֱמֶת?", "Really?"],
    ["לְמַעֲשֶׂה", "lema'ase", "actually / in fact", "adv", "", "לְמַעֲשֶׂה זֶה טוֹב.", "Actually it's good."],
    ["לְצַעֲרִי", "letsa'ari", "unfortunately", "adv", "", "לְצַעֲרִי לֹא.", "Unfortunately not."],
    ["בְּהֶחְלֵט", "behechlet", "absolutely", "adv", "", "בְּהֶחְלֵט!", "Absolutely!"],
    ["בְּעֵרֶךְ", "be'erech", "approximately", "adv", "", "בְּעֵרֶךְ עֶשֶׂר דַּקּוֹת.", "About ten minutes."],
    ["בִּמְיֻחָד", "bimyuchad", "especially", "adv", "", "לֹא בִּמְיֻחָד.", "Not especially."],
    ["לְהִתְכַּוֵּן", "lehitkaven", "to mean / intend", "verb", "מִתְכַּוֵּן, מִתְכַּוֶּנֶת", "לְמָה אַתָּה מִתְכַּוֵּן?", "What do you mean?"],
    ["כַּמּוּבָן", "kamuvan", "of course", "adv", "", "כֵּן, כַּמּוּבָן.", "Yes, of course."],
    ["דֵּעָה", "de'a", "opinion", "n", "דֵּעוֹת", "מָה דַּעְתְּךָ?", "What's your opinion?"]
  ],
  he_v11: [
    ["מֶזֶג אֲוִיר", "mezeg avir", "weather", "n", "", "אֵיזֶה מֶזֶג אֲוִיר!", "What weather!"],
    ["שֶׁמֶשׁ", "shemesh", "sun", "n", "f.", "הַשֶּׁמֶשׁ זוֹרַחַת.", "The sun is shining."],
    ["גֶּשֶׁם", "geshem", "rain", "n", "יוֹרֵד גֶּשֶׁם = it's raining", "יוֹרֵד גֶּשֶׁם.", "It's raining."],
    ["שֶׁלֶג", "sheleg", "snow", "n", "יוֹרֵד שֶׁלֶג", "יוֹרֵד שֶׁלֶג!", "It's snowing!"],
    ["רוּחַ", "ru'ach", "wind; spirit", "n", "f.", "יֵשׁ רוּחַ חֲזָקָה.", "There's a strong wind."],
    ["עָנָן", "anan", "cloud", "n", "עֲנָנִים; מְעֻנָּן = cloudy", "אֵין עֲנָנִים הַיּוֹם.", "No clouds today."],
    ["קַר", "kar", "cold", "adj", "קָרָה, קָרִים", "קַר בַּחוּץ.", "It's cold outside."],
    ["חַם", "cham", "warm / hot", "adj", "חַמָּה, חַמִּים", "קַיִץ חַם.", "A hot summer."],
    ["מַעֲלָה", "ma'ala", "degree", "n", "מַעֲלוֹת", "מִינוּס עֶשֶׂר מַעֲלוֹת.", "Minus ten degrees."],
    ["קַיִץ", "kayits", "summer", "n", "בַּקַּיִץ = in summer", "בַּקַּיִץ אֲנַחְנוּ שׂוֹחִים.", "In summer we swim."],
    ["חֹרֶף", "choref", "winter", "n", "בַּחֹרֶף", "הַחֹרֶף אָרֹךְ.", "Winter is long."],
    ["סְתָו", "stav", "autumn", "n", "", "בַּסְּתָו מַתְחִילָה הָעוֹנָה.", "In autumn the season starts."],
    ["אָבִיב", "aviv", "spring", "n", "תֵּל אָבִיב = hill of spring", "סוֹף סוֹף אָבִיב!", "Spring at last!"],
    ["יַעַר", "ya'ar", "forest", "n", "יְעָרוֹת", "יַעַר גָּדוֹל.", "A big forest."],
    ["אֲגַם", "agam", "lake", "n", "", "אֲנַחְנוּ שׂוֹחִים בָּאֲגַם.", "We swim in the lake."],
    ["יָם", "yam", "sea", "n", "יַמִּים", "הַיָּם קַר.", "The sea is cold."],
    ["הַר", "har", "mountain", "n", "הָרִים", "הָרִים גְּבוֹהִים.", "High mountains."],
    ["עֵץ", "ets", "tree; wood", "n", "עֵצִים", "עֵץ זָקֵן.", "An old tree."],
    ["פֶּרַח", "perach", "flower", "n", "פְּרָחִים", "פְּרָחִים יָפִים.", "Beautiful flowers."],
    ["חַיָּה", "chaya", "animal", "n", "חַיּוֹת", "חַיּוֹת בַּר.", "Wild animals."],
    ["כֶּלֶב", "kelev", "dog", "n", "כְּלָבִים", "הַכֶּלֶב נוֹבֵחַ.", "The dog is barking."],
    ["חָתוּל", "chatul", "cat", "n", "חֲתוּלִים", "הַחָתוּל יָשֵׁן.", "The cat is sleeping."],
    ["סוּס", "sus", "horse", "n", "סוּסִים", "סוּס חוּם.", "A brown horse."],
    ["צִפּוֹר", "tsipor", "bird", "n", "צִפּוֹרִים (f.)", "הַצִּפּוֹרִים שָׁרוֹת.", "The birds are singing."],
    ["גָּמָל", "gamal", "camel", "n", "גְּמַלִּים", "רָאִינוּ גָּמָל.", "We saw a camel."],
    ["קֶרַח", "kerach", "ice", "n", "", "הַקֶּרַח עָבֶה.", "The ice is thick."],
    ["שָׁמַיִם", "shamayim", "sky; heaven", "n", "m. pl. form", "שָׁמַיִם כְּחֻלִּים.", "A blue sky."],
    ["כּוֹכָב", "kochav", "star", "n", "כּוֹכָבִים", "הַרְבֵּה כּוֹכָבִים.", "Many stars."],
    ["אוֹר", "or", "light", "n", "אוֹרוֹת", "תַּדְלִיק אֶת הָאוֹר.", "Turn on the light."],
    ["חֹשֶׁךְ", "choshech", "darkness", "n", "חָשׁוּךְ = dark", "חָשׁוּךְ.", "It's dark."]
  ],
  he_v12: [
    ["חֲדָשׁוֹת", "chadashot", "news", "n", "", "רָאִיתָ אֶת הַחֲדָשׁוֹת?", "Did you see the news?"],
    ["עִתּוֹן", "iton", "newspaper", "n", "עִתּוֹנִים", "אֲנִי קוֹרֵא עִתּוֹן.", "I read a newspaper."],
    ["מֶמְשָׁלָה", "memshala", "government", "n", "", "הַמֶּמְשָׁלָה מַחְלִיטָה.", "The government decides."],
    ["בְּחִירוֹת", "bchirot", "elections", "n", "בְּחִירָה = choice", "הַבְּחִירוֹת בְּנוֹבֶמְבֶּר.", "The elections are in November."],
    ["לְהַצְבִּיעַ", "lehatsbi'a", "to vote; to point", "verb", "מַצְבִּיעַ, מַצְבִּיעָה", "אֲנִי מַצְבִּיעַ מָחָר.", "I vote tomorrow."],
    ["חֹק", "chok", "law", "n", "חֻקִּים", "יֵשׁ חֹק.", "There is a law."],
    ["מַס", "mas", "tax", "n", "מִסִּים", "מִסִּים גְּבוֹהִים.", "High taxes."],
    ["מְחִיר", "mechir", "price", "n", "מְחִירִים", "הַמְּחִיר גָּבוֹהַּ.", "The price is high."],
    ["לַעֲלוֹת", "la'alot", "to cost; to go up; to immigrate to Israel", "verb", "עוֹלֶה, עוֹלָה; כַּמָּה זֶה עוֹלֶה?", "כַּמָּה זֶה עוֹלֶה?", "How much does it cost?"],
    ["חֶבְרָה", "chevra", "society", "n", "", "הַחֶבְרָה הַיִּשְׂרְאֵלִית.", "Israeli society."],
    ["תַּרְבּוּת", "tarbut", "culture", "n", "", "תַּרְבּוּת יִשְׂרְאֵלִית.", "Israeli culture."],
    ["הִיסְטוֹרְיָה", "historia", "history", "n", "", "הַהִיסְטוֹרְיָה שֶׁל יִשְׂרָאֵל.", "The history of Israel."],
    ["שָׂפָה", "safa", "language; lip", "n", "שָׂפוֹת", "עִבְרִית הִיא שָׂפָה יָפָה.", "Hebrew is a beautiful language."],
    ["עוֹלָם", "olam", "world", "n", "", "כָּל הָעוֹלָם.", "The whole world."],
    ["מִלְחָמָה", "milchama", "war", "n", "מִלְחָמוֹת", "אֵין מִלְחָמָה.", "No war."],
    ["שָׁלוֹם", "shalom", "peace", "n", "", "שָׁלוֹם בָּעוֹלָם.", "Peace in the world."],
    ["סְבִיבָה", "sviva", "environment", "n", "", "טוֹב לַסְּבִיבָה.", "Good for the environment."],
    ["אַקְלִים", "aklim", "climate", "n", "", "הָאַקְלִים מִשְׁתַּנֶּה.", "The climate is changing."],
    ["טֶכְנוֹלוֹגְיָה", "technologia", "technology", "n", "", "טֶכְנוֹלוֹגְיָה חֲדָשָׁה.", "New technology."],
    ["עָתִיד", "atid", "future", "n", "בֶּעָתִיד = in the future", "בֶּעָתִיד.", "In the future."],
    ["בְּעָיָה", "be'aya", "problem", "n", "בְּעָיוֹת; אֵין בְּעָיָה", "אֵין בְּעָיָה!", "No problem!"],
    ["פִּתְרוֹן", "pitron", "solution", "n", "פִּתְרוֹנוֹת", "פִּתְרוֹן טוֹב.", "A good solution."],
    ["לָדוּן", "ladun", "to discuss", "verb", "דָּן, דָּנָה; דִּיּוּן = discussion", "אֲנַחְנוּ דָּנִים בְּפּוֹלִיטִיקָה.", "We discuss politics."],
    ["לְסַפֵּר", "lesaper", "to tell", "verb", "מְסַפֵּר, מְסַפֶּרֶת; סִפּוּר = story", "סַפֵּר לִי עוֹד!", "Tell me more!"],
    ["לְהַסְבִּיר", "lehasbir", "to explain", "verb", "מַסְבִּיר, מַסְבִּירָה", "אַתָּה יָכוֹל לְהַסְבִּיר?", "Can you explain?"],
    ["הִתְפַּתְּחוּת", "hitpatchut", "development", "n", "", "הִתְפַּתְּחוּת מְהִירָה.", "A rapid development."],
    ["לְהַחְלִיט", "lehachlit", "to decide", "verb", "מַחְלִיט, מַחְלִיטָה", "אַתָּה מַחְלִיט.", "You decide."],
    ["לִקְרוֹת", "likrot", "to happen", "verb", "קוֹרֶה; מָה קָרָה? = what happened?", "מָה קָרָה?", "What happened?"],
    ["מַשְׁמָעוּת", "mashma'ut", "meaning", "n", "", "מָה הַמַּשְׁמָעוּת שֶׁל הַמִּלָּה?", "What is the meaning of the word?"],
    ["מִלָּה", "mila", "word", "n", "מִלִּים (f.)", "מִלָּה חֲדָשָׁה.", "A new word."]
  ],
  he_v13: [
    ["כִּי", "ki", "because", "conj", "", "אֲנִי נִשְׁאָר בַּבַּיִת כִּי אֲנִי חוֹלֶה.", "I'm staying home because I'm sick."],
    ["בִּגְלַל", "biglal", "because of", "prep", "בִּגְלַל שֶׁ = because (colloquial)", "בִּגְלַל הַגֶּשֶׁם.", "Because of the rain."],
    ["לָכֵן", "lachen", "therefore", "adv", "", "יוֹרֵד גֶּשֶׁם, לָכֵן אֲנִי לוֹקֵחַ אוֹטוֹבּוּס.", "It's raining, so I take the bus."],
    ["לַמְרוֹת", "lamrot", "despite", "prep", "לַמְרוֹת שֶׁ = although", "שִׂחַקְנוּ לַמְרוֹת הַשֶּׁלֶג.", "We played despite the snow."],
    ["אֲבָל", "aval", "but", "conj", "", "קַר, אֲבָל יָפֶה.", "Cold, but beautiful."],
    ["אִם", "im", "if", "conj", "", "אִם יֵרֵד גֶּשֶׁם, נִשָּׁאֵר בַּבַּיִת.", "If it rains, we'll stay home."],
    ["כַּאֲשֶׁר", "ka'asher", "when (conj.)", "conj", "כְּשֶׁ (kshe-) in speech", "כְּשֶׁאֲנִי עָיֵף, אֲנִי יָשֵׁן.", "When I'm tired, I sleep."],
    ["לִפְנֵי", "lifnei", "before", "prep", "לִפְנֵי שֶׁ = before (conj.)", "תִּתְקַשֵּׁר לִפְנֵי שֶׁאַתָּה בָּא.", "Call before you come."],
    ["אַחֲרֵי", "acharei", "after", "prep", "אַחֲרֵי שֶׁ = after (conj.)", "אַחֲרֵי הָאִמּוּן.", "After practice."],
    ["בְּמֶשֶׁךְ", "bemeshech", "during", "prep", "", "בְּמֶשֶׁךְ הַמִּשְׂחָק.", "During the game."],
    ["חוּץ מִ", "chuts mi", "except / apart from", "prep", "", "כֻּלָּם חוּץ מִמֶּנִּי.", "Everyone except me."],
    ["בְּנוֹסָף", "benosaf", "in addition", "adv", "", "בְּנוֹסָף, זֶה זוֹל.", "Besides, it's cheap."],
    ["לְעֻמַּת זֹאת", "le'umat zot", "on the other hand", "adv", "", "אֲנִי, לְעֻמַּת זֹאת, אוֹהֵב חֹרֶף.", "I, on the other hand, like winter."],
    ["אָז", "az", "so / then", "adv", "", "אָז אַתָּה לֹא בָּא?", "So you're not coming?"],
    ["בְּכָל זֹאת", "bechol zot", "nevertheless", "adv", "", "הָיָה קַר, בְּכָל זֹאת הָלַכְנוּ.", "It was cold; we went anyway."],
    ["עֲדַיִן", "adayin", "still / yet", "adv", "", "אֲנִי עֲדַיִן גָּר פֹּה.", "I still live here."],
    ["כְּבָר", "kvar", "already", "adv", "", "אַתָּה כְּבָר מוּכָן?", "Are you already ready?"],
    ["בְּקָרוֹב", "bekarov", "soon", "adv", "", "נִתְרָאֶה בְּקָרוֹב.", "See you soon."],
    ["לְעִתִּים קְרוֹבוֹת", "le'itim krovot", "often", "adv", "הַרְבֵּה פְּעָמִים (colloquial)", "אֲנִי מִתְאַמֵּן לְעִתִּים קְרוֹבוֹת.", "I train often."],
    ["לְעִתִּים רְחוֹקוֹת", "le'itim rechokot", "rarely", "adv", "", "הוּא מְאַחֵר לְעִתִּים רְחוֹקוֹת.", "He is rarely late."],
    ["תָּמִיד", "tamid", "always", "adv", "", "אֲנִי תָּמִיד רָעֵב.", "I'm always hungry."],
    ["אַף פַּעַם", "af pa'am", "never (with לֹא)", "adv", "", "אֲנִי אַף פַּעַם לֹא מְוַתֵּר.", "I never give up."],
    ["לִפְעָמִים", "lif'amim", "sometimes", "adv", "", "לִפְעָמִים יוֹרֵד גֶּשֶׁם.", "Sometimes it rains."],
    ["רַק", "rak", "only", "adv", "", "רַק פַּעַם אַחַת.", "Only once."],
    ["דֵּי", "dei", "quite / enough", "adv", "", "זֶה דֵּי טוֹב.", "It's quite good."],
    ["יוֹתֵר מִדַּי", "yoter midai", "too much", "adv", "", "זֶה יָקָר מִדַּי.", "It's too expensive."],
    ["כִּמְעַט", "kim'at", "almost", "adv", "", "כִּמְעַט מוּכָן.", "Almost ready."],
    ["בְּדִיּוּק", "bediyuk", "exactly", "adv", "", "בְּדִיּוּק!", "Exactly!"],
    ["מִיָּד", "miyad", "immediately", "adv", "", "בּוֹא מִיָּד!", "Come immediately!"],
    ["אֶחָד אֶת הַשֵּׁנִי", "echad et hasheni", "each other", "pron", "", "אֲנַחְנוּ עוֹזְרִים אֶחָד לַשֵּׁנִי.", "We help each other."]
  ],
  he_v14: [
    ["סַבָּבָּה", "sababa", "great / cool (slang)", "phrase", "from Arabic", "סַבָּבָּה, נִפְגָּשִׁים בְּשֵׁשׁ.", "Cool, we'll meet at six."],
    ["יַאלְלָה", "yalla", "come on / let's go (slang)", "phrase", "from Arabic", "יַאלְלָה, הוֹלְכִים!", "Come on, let's go!"],
    ["בְּכֵיף", "bekeif", "gladly / with pleasure", "phrase", "", "בְּכֵיף!", "With pleasure!"],
    ["אֵין בְּעָיָה", "ein be'aya", "no problem", "phrase", "", "אֵין בְּעָיָה, אֲנִי מְטַפֵּל.", "No problem, I'll handle it."],
    ["מָה נִשְׁמָע", "ma nishma", "how are things? (what's heard?)", "phrase", "", "מָה נִשְׁמָע?", "What's up?"],
    ["מָה הָעִנְיָנִים", "ma ha'inyanim", "how's it going? (what are the matters?)", "phrase", "", "הֵי, מָה הָעִנְיָנִים?", "Hey, how's it going?"],
    ["חֲבָל", "chaval", "pity / too bad", "phrase", "חֲבָל עַל הַזְּמַן = awesome (slang, lit. a pity about the time)", "חֲבָל שֶׁלֹּא בָּאתָ.", "Too bad you didn't come."],
    ["בְּהַצְלָחָה", "behatslacha", "good luck", "phrase", "", "בְּהַצְלָחָה בַּמִּבְחָן!", "Good luck on the test!"],
    ["לְחַיִּים", "lechayim", "cheers (to life)", "phrase", "", "לְחַיִּים!", "Cheers!"],
    ["מַזָּל טוֹב", "mazal tov", "congratulations", "phrase", "", "מַזָּל טוֹב!", "Congratulations!"],
    ["תִּתְחַדֵּשׁ", "titchadesh", "enjoy your new thing (said on a new purchase)", "phrase", "תִּתְחַדְּשִׁי (f.)", "נַעֲלַיִם חֲדָשׁוֹת? תִּתְחַדֵּשׁ!", "New shoes? Enjoy them!"],
    ["לְהַסְפִּיק", "lehaspik", "to manage in time / be enough", "verb", "מַסְפִּיק, מַסְפִּיקָה", "אֲנִי לֹא מַסְפִּיק.", "I don't have time (I can't make it)."],
    ["לְהִסְתַּדֵּר", "lehistader", "to manage / work out", "verb", "מִסְתַּדֵּר; יִסְתַּדֵּר = it'll work out", "זֶה יִסְתַּדֵּר.", "It'll work out."],
    ["לְהַרְגִּישׁ בַּבַּיִת", "lehargish babayit", "to feel at home", "phrase", "", "אֲנִי מַרְגִּישׁ בַּבַּיִת בְּיִשְׂרָאֵל.", "I feel at home in Israel."],
    ["לְהִתְגַּעְגֵּעַ", "lehitga'age'a", "to miss (someone / something)", "verb", "מִתְגַּעְגֵּעַ לְ", "אֲנִי מִתְגַּעְגֵּעַ לַמִּשְׁפָּחָה.", "I miss my family."],
    ["לְהַסְכִּים", "lehaskim", "to agree", "verb", "מַסְכִּים, מַסְכִּימָה; מַסְכִּים עִם", "אֲנִי מַסְכִּים אִתְּךָ.", "I agree with you."],
    ["לְהִסְתַּדֵּר עִם", "lehistader im", "to get along with", "phrase", "", "אֲנַחְנוּ מִסְתַּדְּרִים.", "We get along."],
    ["לְהַרְשׁוֹת לְעַצְמוֹ", "leharshot le'atsmo", "to afford", "phrase", "", "אֲנִי לֹא יָכוֹל לְהַרְשׁוֹת לְעַצְמִי אֶת זֶה.", "I can't afford it."],
    ["לֹא אִכְפַּת לִי", "lo ichpat li", "I don't care", "phrase", "אִכְפַּת לִי = I care", "לֹא אִכְפַּת לִי.", "I don't care."],
    ["לְוַתֵּר", "levater", "to give up / give in", "verb", "מְוַתֵּר, מְוַתֶּרֶת", "אַל תְּוַתֵּר!", "Don't give up!"],
    ["לְצַפּוֹת לְ", "letsapot le", "to look forward to / expect", "verb", "מְצַפֶּה לְ", "אֲנִי מְצַפֶּה לַמִּשְׂחָק.", "I'm looking forward to the game."],
    ["לְבָרֵר", "levarer", "to find out", "verb", "מְבָרֵר, מְבָרֶרֶת", "תְּבָרֵר מָתַי הָרַכֶּבֶת.", "Find out when the train is."],
    ["לְרַחֵם עַל", "lerachem al", "to feel sorry for", "verb", "", "אֲנִי מְרַחֵם עָלָיו.", "I feel sorry for him."],
    ["בָּא לִי", "ba li", "I feel like (it comes to me)", "phrase", "לֹא בָּא לִי = I don't feel like it", "בָּא לִי גְּלִידָה.", "I feel like ice cream."],
    ["לְבַקֵּר", "levaker", "to visit; to criticise", "verb", "מְבַקֵּר, מְבַקֶּרֶת", "אֲנַחְנוּ מְבַקְּרִים אֶת סַבְתָּא.", "We're visiting grandma."],
    ["לֹא מְשַׁנֶּה", "lo meshane", "it doesn't matter", "phrase", "", "לֹא מְשַׁנֶּה מִי מְנַצֵּחַ.", "It doesn't matter who wins."],
    ["בְּכָל מִקְרֶה", "bechol mikre", "in any case / anyway", "phrase", "", "בְּכָל מִקְרֶה, נִתְרָאֶה מָחָר.", "Anyway, see you tomorrow."],
    ["מָה דַּעְתְּךָ עַל", "ma da'atcha al", "what do you think about", "phrase", "", "מָה דַּעְתְּךָ עַל קָפֶה?", "How about a coffee?"],
    ["בִּמְקוֹם", "bimkom", "instead of", "prep", "", "תֵּה בִּמְקוֹם קָפֶה.", "Tea instead of coffee."],
    ["סַקְרָן", "sakran", "curious", "adj", "סַקְרָנִית", "אֲנִי סַקְרָן לְגַבֵּי יִשְׂרָאֵל.", "I'm curious about Israel."]
  ]
};

if (typeof module !== "undefined") module.exports = { HE_VOCAB: HE_VOCAB };
