/* ============================================================
   METHOD: the science the whole hub runs on
   One page that explains, with sources, why the schedule, the
   speed gate, the daily cap, the interleaving and the applied
   sessions are shaped the way they are. Shown under Library,
   and linked from the places where each rule bites.
   ============================================================ */
var METHOD = [
  { id: "spacing", title: "Spaced retrieval", one: "Reviews on the due day, with gaps that grow: 1, 3, 7, 16, 35, 80, 180 days.",
    body: "Ebbinghaus measured forgetting in 1885; Cepeda, Pashler and colleagues (2006, 2008) showed in a meta-analysis of hundreds of studies that spreading study over time beats massing it, and that the best gap scales with how long you need to remember. Retrieving a memory just as it is fading strengthens it most. Every skill, word and rule in this hub sits in a Leitner box with a growing interval; it climbs only on a day it is due, after clean answers in a row. Practising early keeps a skill warm but never promotes it, because only the gap proves it is stored.",
    src: "Cepeda et al., Psychological Bulletin 2006; Cepeda et al., Psychological Science 2008; Leitner 1972." },
  { id: "retrieval", title: "Retrieval practice", one: "Answer before you see the answer. Every drill is a test, and tests are the study.",
    body: "Roediger and Karpicke (2006) had students either reread a passage or take a test on it; a week later the tested group remembered far more, though they had felt less confident. The testing effect is one of the most replicated findings in cognitive psychology. Nothing here is a passive review: recall cards make you say the rule before revealing it, vocabulary graduates from recognition to production to dictation to speech, and checkpoints are tests, not summaries.",
    src: "Roediger & Karpicke, Psychological Science 2006; Karpicke & Blunt, Science 2011." },
  { id: "fluency", title: "The speed gate", one: "Right is not enough. A skill moves up only when the answer is also fast.",
    body: "Logan's instance theory of automaticity (1988) and the broader literature on skill acquisition show that practice turns deliberate computation into direct memory retrieval, and that the signature of the change is speed. Each drill has a time target that tightens as the box climbs. A correct answer over the goal does not count toward promotion, because the clock is the only honest measure of whether something has become reflex, which is what you need at a table, over a board, or in a conversation.",
    src: "Logan, Psychological Review 1988; Ericsson, Krampe & Tesch-Römer 1993." },
  { id: "interleave", title: "Interleaving", one: "Sessions mix skills and never ask the same one twice running when there is a choice.",
    body: "Rohrer and Taylor (2007) taught students four kinds of maths problem either blocked (all of one kind, then the next) or mixed; the mixed group did worse in practice and much better on the test. Mixing forces you to recognise which tool the problem needs, which is the skill exams and games actually test. The schedule interleaves within a course and the calendar interleaves across courses, alternating rather than stacking.",
    src: "Rohrer & Taylor, Instructional Science 2007; Kornell & Bjork, Psychological Science 2008." },
  { id: "difficulty", title: "Desirable difficulties", one: "Harder-feeling practice that sticks beats easy practice that fades.",
    body: "Robert Bjork's term for conditions that slow learning in the moment and improve it in the long run: spacing, testing, interleaving, generating an answer rather than reading it, varying the conditions. Vocabulary here hardens on purpose as a word climbs: pick the meaning, then the word, then type it, then type it into a sentence, then hear it and type it, then say it. The point is not to make it unpleasant; it is that fluent-feeling study is a poor predictor of what you will remember.",
    src: "Bjork, 1994; Bjork & Bjork, 2011; Soderstrom & Bjork, Perspectives on Psychological Science 2015." },
  { id: "feedback", title: "Immediate, specific feedback", one: "A miss shows the working, drops the skill a box, and asks again two questions later.",
    body: "Feedback works best when it is prompt, explains the error, and is followed by another attempt (Hattie & Timperley 2007; the hint ladder in the Math 340 tool is the same idea). Every drill here shows the full solution after a miss, names the rule it comes from, and re-asks the question while the explanation is fresh. The confidence prompt after each answer, borrowed from calibration research, exposes the errors you were sure about, which are the ones that cost most.",
    src: "Hattie & Timperley, Review of Educational Research 2007; Butler, Karpicke & Roediger 2008." },
  { id: "cap", title: "The daily cap and sleep", one: "A budget per day from your calendar, lower on hockey days, nothing after the sleep cutoff.",
    body: "Memories consolidate during sleep (Walker; Rasch & Born 2013): a learned skill tested the next morning after sleep beats one tested the same evening. Learning past fatigue adds little and crowds the schedule a week later, when it all comes due. The planner takes a cap you set, lowers it on days with hockey or five-plus hours of class, keeps 10% of it unallocated, and places nothing after the cutoff. Fifteen minutes a day for a year beats a weekend a month, because the gaps are where the memory forms.",
    src: "Rasch & Born, Physiological Reviews 2013; Walker, Why We Sleep 2017." },
  { id: "newcap", title: "Capped new material", one: "At most two new lessons a day across every skill, never two in one.",
    body: "Each new item generates a stream of future reviews. Anki's community settled on 10 to 20 new cards a day for the same reason the planner caps lessons: adding faster than you review buries you under due items within a fortnight, and the schedule stops being a schedule. The cap keeps the review load flat and the new-material load predictable, and the forecast on the Calendar shows the reviews each day will bring before they arrive.",
    src: "Settles & Meeder, ACL 2016 (half-life regression at Duolingo); the Anki manual." },
  { id: "apply", title: "Learn, drill, apply", one: "Every skill has a simulated setting where the knowledge has to be used under pressure.",
    body: "Transfer is the hard problem of learning: knowing the rule and using it at speed, under uncertainty, with other things going on, are different skills. Ericsson's work on deliberate practice and the transfer literature (Barnett & Ceci 2002) both point the same way: practise the thing itself, with feedback, close to the real conditions. So poker has a graded table, chess a graded engine opponent, the languages scripted conversations and dictation, and Math 340 timed exam rehearsals. Mistakes made there come back as drills, so the loop closes.",
    src: "Ericsson, Krampe & Tesch-Römer 1993; Barnett & Ceci, Psychological Bulletin 2002." },
  { id: "school", title: "Schoolwork first", one: "Due flashcards, the redo queue, quiz and exam rehearsals, and homework deadlines go to the front of every day.",
    body: "Grades are decided under time limits on known dates, which makes them the easiest thing to schedule well and the costliest to schedule badly. The planner reads each course's due cards, missed problems and key dates, places that work first with the time it needs, and starts recommending timed rehearsals two weeks before an exam and the evening before a quiz, because deferred-feedback practice under the clock is the condition the grade is earned under.",
    src: "Dunlosky et al., Psychological Science in the Public Interest 2013 (practice testing and distributed practice rated highest utility)." },
  { id: "language", title: "Languages without immersion", one: "Sounds first, frequency-ordered words, output with feedback, and logged native input.",
    body: "What people call the CIA method is the Foreign Service Institute programme that trains US diplomats, and its evidence is in its hour estimates: Swedish about 600–750 hours, Hebrew about 1,100, with intensive drilling, pattern practice and speaking from day one. Combined with the acquisition research, Krashen's comprehensible input, Swain's output hypothesis, Nation on vocabulary frequency, Wyner on training the ear before the eye, the course order falls out: the sound system; the first 1,000 words by frequency with their sentences; grammar as patterns you produce; scripted conversation, dictation and shadowing as the stand-in for immersion; and extensive reading and listening, logged as hours, from B1 onward. The level model counts all of it.",
    src: "FSI language difficulty rankings; Krashen 1985; Swain 1985; Nation 2001; Wyner, Fluent Forever 2014; Arguelles on shadowing." },
  { id: "measure", title: "Measure the skill, not the study", one: "Each level is computed from what you can do, and it can go down.",
    body: "Poker's level is the quality of your last hundred decisions at the table; chess's is the engine's grade of your last hundred moves plus a tactics rating; the languages use a CEFR estimate from words known, grammar passed, applied scores and hours; Math 340 reports per-topic first-try accuracy and timed sittings. None of these count time spent. Streaks and XP reward the behaviour (showing up, doing the reviews); the levels measure the outcome. Keep them apart and both stay honest.",
    src: "Ericsson & Pool, Peak 2016; Dweck on process praise; Glicko and Elo rating theory." }
];

if (typeof module !== "undefined") module.exports = { METHOD: METHOD };
